Repository neos/neos-development-collection, pull requests merged in 2019-04, with the labels that each got.

#2408 FEATURE: Set crop image adjustment by aspect ratio
  Neos.Media.Browser/Classes/Controller/AssetController.php
  Neos.Media.Browser/Classes/Controller/ImageController.php
  Neos.Media/Classes/Domain/Model/Adjustment/CropImageAdjustment.php
  Neos.Media/Classes/Domain/Repository/AssetRepository.php
  Neos.Media/Migrations/Mysql/Version20190315122900.php
  Neos.Media/Migrations/Postgresql/Version20190315122901.php
  Neos.Media/Tests/Unit/Domain/Model/Adjustment/CropImageAdjustmentTest.php
Labels: Feature, P: Media, T: PHP

#2439 BUGFIX: Fix tag rendering in media module
  Neos.Media.Browser/Classes/Controller/AssetController.php
Labels: Bug, P: Media Browser

#2431 BUGFIX: Apply enforced image format conversions to all generated images
  Neos.Media/Classes/Domain/Model/ThumbnailConfiguration.php
  Neos.Media/Classes/Domain/Model/ThumbnailGenerator/ConvertImageThumbnailGenerator.php
  Neos.Media/Classes/Domain/Model/ThumbnailGenerator/ImageThumbnailGenerator.php
  Neos.Media/Classes/Domain/Service/ThumbnailService.php
  Neos.Media/Configuration/Settings.yaml
  Neos.Neos/Documentation/Appendixes/ReleaseNotes/430.rst
Labels: Bug, P: Media

#2426 FEATURE: Variant view in react and possibility of cropping
  Neos.Media.Browser/.babelrc
  Neos.Media.Browser/.eslintrc
  Neos.Media.Browser/.nvmrc
  Neos.Media.Browser/.stylelintrc
  Neos.Media.Browser/.yarnclean
  Neos.Media.Browser/.yarnrc
  Neos.Media.Browser/Classes/Controller/AssetController.php
  Neos.Media.Browser/Classes/Controller/ImageVariantController.php
  Neos.Media.Browser/Classes/Domain/ImageMapper.php
  Neos.Media.Browser/Configuration/Policy.yaml
  Neos.Media.Browser/Configuration/Routes.yaml
  Neos.Media.Browser/Configuration/Settings.yaml
  Neos.Media.Browser/Resources/Private/Templates/Asset/Edit.html
  Neos.Media.Browser/Resources/Private/Templates/Asset/Variants.html
  Neos.Media.Browser/Resources/Public/JavaScript/Main.js
  Neos.Media.Browser/Resources/Public/JavaScript/Main.js.map
  Neos.Media.Browser/Resources/Public/JavaScript/Vendor.js
  Neos.Media.Browser/Resources/Public/JavaScript/Vendor.js.map
  Neos.Media.Browser/Resources/Public/Styles/Main.css
  Neos.Media.Browser/Resources/Public/Styles/Main.css.map
  Neos.Media.Browser/package.json
  Neos.Media.Browser/packages/neos-media-browser/src/Variants/ImageCropper.js
  Neos.Media.Browser/packages/neos-media-browser/src/Variants/ImageCropperModal.js
  Neos.Media.Browser/packages/neos-media-browser/src/Variants/Original.js
  Neos.Media.Browser/packages/neos-media-browser/src/Variants/Variant.js
  Neos.Media.Browser/packages/neos-media-browser/src/Variants/Variants.js
  Neos.Media.Browser/packages/neos-media-browser/src/Variants/index.js
  Neos.Media.Browser/packages/neos-media-browser/src/Variants/react_crop.vanilla-css
  Neos.Media.Browser/packages/neos-media-browser/src/index.js
  Neos.Media.Browser/tslint.json
  Neos.Media.Browser/webpack.config.js
  Neos.Media.Browser/yarn.lock
  Neos.Media/Configuration/Settings.yaml
  Neos.Media/Documentation/VariantPresets.rst
Labels: Feature, P: Media Browser, T: JS, T: PHP, T: UX

#2461 BUGFIX: Filtering by nodeType that has subtypes causes a php_error
  Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
Labels: P: Content Repository

#2464 BUGFIX: Fix `parents` flowQuery operation accidentally returning the `/sites` and `/` node
  Neos.Neos/Classes/Eel/FlowQueryOperations/ParentsOperation.php
  Neos.Neos/Tests/Unit/FlowQueryOperations/ParentsOperationTest.php
Labels: Bug, P: Content Repository

#2466 WIP: Merge 3.3 into 4.0
  Neos.ContentRepository/Classes/Domain/Model/Node.php
  Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
Labels: I: WIP

#2467 WIP: Merge 4.0 into 4.1
  Neos.ContentRepository/Classes/Domain/Model/Node.php
  Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
Labels: I: WIP

#2468 WIP: Merge 4.1 into 4.2
  Neos.ContentRepository/Classes/Domain/Model/Node.php
  Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
Labels: I: WIP

#2469 WIP: Merge 4.2 into 4.3
  Neos.ContentRepository/Classes/Domain/Model/Node.php
  Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
Labels: I: WIP

#2470 WIP: Merge 4.3 to master
  Neos.ContentRepository/Classes/Domain/Model/Node.php
  Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
  Neos.Neos/Classes/Eel/FlowQueryOperations/ParentsOperation.php
  Neos.Neos/Documentation/Appendixes/ReleaseNotes/430.rst
  Neos.Neos/Tests/Unit/FlowQueryOperations/ParentsOperationTest.php
Labels: I: WIP
