Repository neos/neos-development-collection, pull requests merged in 2021-07, with the labels that each got.

#3367 BUGFIX: Adjust contributing section to composer changes
  Readme.rst
Labels: Bug, T: Documentation

#3364 BUGFIX: Fix depth comparison in hasHiddenNodeParent(…)
  Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php
Labels: P: Neos, T: PHP

#3368 TASK: Replace deprecated guzzle functions with static methods
  Neos.Fusion/Classes/FusionObjects/HttpResponseImplementation.php
  Neos.Fusion/Tests/Unit/FusionObjects/Http/ResponseHeadImplementationTest.php
  Neos.Neos/Classes/Fusion/ExceptionHandlers/PageHandler.php
  Neos.Neos/Classes/View/FusionView.php
Labels: dependencies
