Repository neos/neos-development-collection, pull requests merged in 2021-03, with the labels that each got.

#3291 TASK: Add GH action for builds
  .github/workflows/build.yml
  .travis.yml
Labels: T: Testing

#3277 BUGFIX: Prevent error in route cache aspect
  Neos.Neos/Classes/Routing/Aspects/RouteCacheAspect.php
Labels: Bug, P: Neos

#3316 BUGFIX: Open delete dialog on edit user view
  Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Edit.html
Labels: Good first issue

#3320 FEATURE: Fusion debug to browser console
  Neos.Fusion/Classes/FusionObjects/DebugConsoleImplementation.php
  Neos.Fusion/Resources/Private/Fusion/DebugConsole.fusion
  Neos.Fusion/Resources/Private/Fusion/Root.fusion
  Neos.Fusion/Tests/Functional/FusionObjects/DebugConsoleTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/DebugConsole.fusion
  Neos.Neos/Documentation/References/NeosFusionReference.rst
Labels: Feature, P: Fusion

#3322 TASK: Adjust versions in Readme
  Readme.rst
Labels: Good first issue, T: Documentation
