Repository neos/neos-development-collection, pull requests merged in 2022-11, with the labels that each got.

#3905 TASK: Update code of conduct
  CODE_OF_CONDUCT.md
  CodeOfConduct.rst
Labels: T: Documentation

#3924 FEATURE: Make login logo configurable
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/Documentation/References/Configuration/Configuration.rst
  Neos.Neos/Resources/Private/Fusion/Backend/Component/ImageSource.fusion
  Neos.Neos/Resources/Private/Fusion/Backend/Root.fusion
  Neos.Neos/Resources/Private/Fusion/Backend/Views/Login.fusion
Labels: Feature

#3961 BUGFIX: typo in CSS property border-bottom-left-radius
  Neos.Neos/Resources/Private/Styles/Foundation/_mixins.scss
  Neos.Neos/Resources/Private/Styles/Foundation/_tables.scss
Labels: Bug
