Repository neos/neos-development-collection, pull requests merged in 2023-05, with the labels that each got.

#4225 BUGFIX: HtmlAugmenter & Attributes Rendering
  Neos.Fusion/Classes/Service/HtmlAugmenter.php
  Neos.Fusion/Classes/Service/RenderAttributesTrait.php
  Neos.Fusion/Tests/Unit/Service/HtmlAugmenterTest.php
Labels: Bug, 8.3

#4237 BUGFIX: Add translation keys in translation files
  Neos.Neos/Resources/Private/Translations/en/Main.xlf
Labels: Bug, 7.3

#4239 BUGFIX: ensure mysql compatibility by shortening index length
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepository.php
Labels: Bug, 9.0

#4241 FEATURE: Restrict NodeAggregateId and ContentStreamId to proper length
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/SchemaBuilder/HypergraphSchemaBuilder.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamProjection.php
  Neos.ContentRepository.Core/Classes/Projection/NodeHiddenState/NodeHiddenStateProjection.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeAggregateId.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/ContentStreamId.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepository.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathSchemaBuilder.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: Feature, 9.0

#4242 BUGFIX: Allow events with not existing newWorkspaceOwner
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Event/WorkspaceOwnerWasChanged.php
Labels: Bug, 9.0

#4244 FEATURE: Add `allDimensionValues` to `Neos.Dimension` helper
  Neos.ContentRepository.Core/Classes/Dimension/ContentDimensionValues.php
  Neos.Neos/Classes/Fusion/Helper/DimensionHelper.php
Labels: Feature, 9.0

#4245 TASK: remove remaining non used packages
  .composer.json
  .run-e2e-test.sh
  ESCR/.editorconfig
  ESCR/.run-e2e-test.sh
  ESCR/README.md
  Neos.EventSourcedContentRepository.LegacyApi/Classes/ContextInNodeBasedReadModel/AddContextToNodeBasedReadModelInterfaceAspect.php
  Neos.EventSourcedContentRepository.LegacyApi/Classes/ContextInNodeBasedReadModel/ContextInNodeBasedReadModelInterface.php
  Neos.EventSourcedContentRepository.LegacyApi/Classes/ContextInNodeBasedReadModel/EmulatedLegacyBaseWorkspace.php
  Neos.EventSourcedContentRepository.LegacyApi/Classes/ContextInNodeBasedReadModel/EmulatedLegacyContext.php
  Neos.EventSourcedContentRepository.LegacyApi/Classes/ContextInNodeBasedReadModel/EmulatedLegacySite.php
  Neos.EventSourcedContentRepository.LegacyApi/Classes/ContextInNodeBasedReadModel/EmulatedLegacyWorkspace.php
  Neos.EventSourcedContentRepository.LegacyApi/Classes/FlowQueryContextOperation/ContextOperation.php
  Neos.EventSourcedContentRepository.LegacyApi/Classes/LegacyNodeInterfaceApi/LegacyNodeInterfaceApi.php
  Neos.EventSourcedContentRepository.LegacyApi/Classes/Logging/LegacyLoggerInterface.php
  Neos.EventSourcedContentRepository.LegacyApi/Configuration/Objects.yaml
  Neos.EventSourcedContentRepository.LegacyApi/Configuration/Settings.yaml
  Neos.EventSourcedContentRepository.LegacyApi/composer.json
  Neos.EventSourcedNeosAdjustments/Classes/Ui/Fusion/RenderNonRenderedNodeMetadataImplementation.php
  Neos.EventSourcedNeosAdjustments/Configuration/NodeTypes.yaml
  Neos.EventSourcedNeosAdjustments/Configuration/Policy.yaml
  Neos.EventSourcedNeosAdjustments/Configuration/Settings.yaml
  Neos.EventSourcedNeosAdjustments/Configuration/Testing/Behat/NodeTypes.Test.Routing.yaml
  Neos.EventSourcedNeosAdjustments/Configuration/Testing/Behat/Settings.yaml
  Neos.EventSourcedNeosAdjustments/Configuration/Views.yaml
  Neos.EventSourcedNeosAdjustments/Migrations/Mysql/Version20170921132850.php
  Neos.EventSourcedNeosAdjustments/Migrations/Mysql/Version20200731135535.php
  Neos.EventSourcedNeosAdjustments/Patches/flowpack_elasticsearch_contentrepositoryadaptor.patch
  Neos.EventSourcedNeosAdjustments/Patches/neos_contentrepository_search.patch
  Neos.EventSourcedNeosAdjustments/Patches/neos_neos-development-collection_ReadMe.patch
  Neos.EventSourcedNeosAdjustments/Patches/neos_neos-development-collection_fusionAndSiteService.patch
  Neos.EventSourcedNeosAdjustments/Patches/neos_neos-development-collection_upload-asset.patch
  Neos.EventSourcedNeosAdjustments/Resources/Private/Fusion/Backend/Root.fusion
  Neos.EventSourcedNeosAdjustments/Resources/Private/Fusion/Root.fusion
  Neos.EventSourcedNeosAdjustments/Resources/Public/UiAdapter/Plugin.js
  Neos.EventSourcedNeosAdjustments/Resources/Public/UiAdapter/Plugin.js.map
  Neos.EventSourcedNeosAdjustments/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.EventSourcedNeosAdjustments/Tests/Behavior/Features/EndToEnd/Changes/CreateNode.feature
  Neos.EventSourcedNeosAdjustments/Tests/Behavior/Features/EndToEnd/Changes/HideShowNode.feature
  Neos.EventSourcedNeosAdjustments/Tests/Behavior/Features/EndToEnd/Changes/PropertyChange.feature
  Neos.EventSourcedNeosAdjustments/Tests/Behavior/Features/EndToEnd/Changes/PublishSingleDocument.feature
  Neos.EventSourcedNeosAdjustments/Tests/Behavior/Features/EndToEnd/Frontend/DemoSiteRenders.feature
  Neos.EventSourcedNeosAdjustments/Tests/Behavior/Features/EndToEnd/RenderingInBackend/RenderingInBackend.feature
  Neos.EventSourcedNeosAdjustments/Tests/Behavior/Features/FlowQuery/FindOperation.feature
  Neos.EventSourcedNeosAdjustments/Tests/Behavior/behat.yml.dist
  Neos.EventSourcedNeosAdjustments/composer.json
  Neos.EventSourcedNeosAdjustments/composer.patches.json
  Neos.Neos/Classes/Fusion/NewNodeConverter.php
  Neos.Neos/Configuration/Testing/Behat/NodeTypes.Test.Routing.yaml
  Neos.Neos/NodeTypes/Mixin/Timable.yaml
  Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Basic.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Dimensions.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/DisableNodes.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Lowlevel_ProjectionTests.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/MultiSiteLinking.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Shortcuts.feature
  composer.json
  phpstan.neon
Labels: 9.0, Task

#4247 TASK: Update dependencies to Flow/Neos 9.0
  .composer.json
  Neos.Neos/composer.json
  Neos.SiteKickstarter/composer.json
  composer.json
Labels: 9.0, Task

#4249 TASK: Refactor `Neos.Dimension` helper functions to return `ContentDimensionValue`
  Neos.Neos/Classes/Fusion/Helper/DimensionHelper.php
Labels: 9.0, Task

#4248 BUGFIX: fix `./flow site:create` command
  Neos.Neos/Classes/Command/SiteCommandController.php
  Neos.Neos/Classes/Domain/Service/SiteService.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
Labels: Bug, 9.0

#4258 TASK: Require all collection packages as self.version
  Neos.CliSetup/composer.json
  Neos.Fusion.Afx/composer.json
  Neos.Neos/composer.json
  Neos.NodeTypes.AssetList/composer.json
  Neos.NodeTypes.BaseMixins/composer.json
  Neos.NodeTypes.ColumnLayouts/composer.json
  Neos.NodeTypes.ContentReferences/composer.json
  Neos.NodeTypes.Form/composer.json
  Neos.NodeTypes.Html/composer.json
  Neos.NodeTypes.Navigation/composer.json
Labels: Task, 7.3

#4260 BUGFIX: point too 8.3.x-dev branch in README
  Readme.rst
Labels: Bug, 8.3

#4261 FEATURE: allow replaying projections only up to a certain point
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Service/ProjectionReplayService.php
  Neos.ContentRepositoryRegistry/Classes/Service/ProjectionReplayServiceFactory.php
Labels: Feature, 9.0

#4262 BUGFIX: re-fix content stream cleanup
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
Labels: Bug, 9.0

#4272 !!! TASK: Require PHP 8.2
  .github/workflows/build.yml
  Neos.CliSetup/composer.json
  Neos.ContentRepository.Core/composer.json
  Neos.ContentRepository.Export/composer.json
  Neos.ContentRepository.LegacyNodeMigration/composer.json
  Neos.Diff/composer.json
  Neos.Fusion/composer.json
  Neos.Media.Browser/composer.json
  Neos.Media/composer.json
  Neos.Neos/composer.json
  Neos.NodeTypes.Form/composer.json
  Neos.SiteKickstarter/composer.json
  composer.json
Labels: 9.0, Task

#4273 9.0 BUGFIX: Adjust file path for trait
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
Labels: Bug, 9.0

#4266 !!! BUGFIX: DocumentUriProjection doesn't respect fallback nodes; NodePropertiesWereSet contains affectedDimensionSpacePoints
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/ForkContentStreamWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/Properties.feature
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/EventSourcedTrait.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/PropertyAdjustment.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Basic.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Dimensions.feature
Labels: 9.0

#4274 9.0 BUGFIX: Allow NodeUriBuilder beeing proxied
  Neos.Neos/Classes/FrontendRouting/NodeUriBuilder.php
Labels: Bug, 9.0

#4275 BUGFIX: Use uriPathSuffix from options
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
Labels: Bug, 9.0

#4290 FEATURE: Get ContentRepositoryId of a ContentRepository by ContentRepositoryRegistry
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
  Neos.ContentRepositoryRegistry/Classes/Exception/ContentRepositoryIdNotFoundException.php
  Neos.ContentRepositoryRegistry/Classes/Exception/ContentRepositoryNotFoundException.php
Labels: Feature, 9.0

#4282 TASK: Update .styleci.yml to use PHP 8.2
  .styleci.yml
Labels: 9.0, Task

#4284 BUGFIX: do not crash when node already disabled/enabled
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/01-DisableNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/04-EnableNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandResult.php
  Neos.ContentRepository.Core/Classes/CommandHandler/PendingProjections.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepository.Core/Classes/EventStore/Events.php
  Neos.ContentRepository.Core/Classes/EventStore/EventsToPublish.php
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/NodeDisabling.php
Labels: Bug, 9.0

#4267 BUGFIX: RenderAttributesTrait allows Stringable objects
  Neos.Fusion/Classes/Service/RenderAttributesTrait.php
  Neos.Fusion/Tests/Unit/Service/HtmlAugmenterTest.php
Labels: Bug, 8.3

#4301 BUGFIX: Use correct configuration path for enableObjectTreeCache
  Neos.Neos/Configuration/Objects.yaml
Labels: Bug, 8.3
