Repository neos/neos-development-collection, pull requests merged in 2023-10, with the labels that each got.

#4573 BUGFIX: Add current node to site changes computation
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
Labels: Bug, 9.0, 9.0beta1

#4537 TASK: Remove deprecated Fusion prototypes
  Neos.Fusion.Afx/README.md
  Neos.Fusion/Classes/FusionObjects/AbstractCollectionImplementation.php
  Neos.Fusion/Classes/FusionObjects/ArrayImplementation.php
  Neos.Fusion/Classes/FusionObjects/AttributesImplementation.php
  Neos.Fusion/Classes/FusionObjects/CollectionImplementation.php
  Neos.Fusion/Classes/FusionObjects/RawArrayImplementation.php
  Neos.Fusion/Classes/FusionObjects/RawCollectionImplementation.php
  Neos.Fusion/Resources/Private/Fusion/Deprecated/Array.fusion
  Neos.Fusion/Resources/Private/Fusion/Deprecated/Attributes.fusion
  Neos.Fusion/Resources/Private/Fusion/Deprecated/Collection.fusion
  Neos.Fusion/Resources/Private/Fusion/Deprecated/RawArray.fusion
  Neos.Fusion/Resources/Private/Fusion/Deprecated/RawCollection.fusion
  Neos.Fusion/Resources/Private/Fusion/Deprecated/UriBuilder.fusion
  Neos.Fusion/Tests/Functional/FusionObjects/CollectionTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/ConditionsTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Collection.fusion
  Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Conditions.fusion
  Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/FusionArray.fusion
  Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/NestedOverwritesAndProcessors.fusion
  Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/RawCollection.fusion
  Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Tag.fusion
  Neos.Fusion/Tests/Functional/FusionObjects/FusionArrayTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/RawCollectionTest.php
  Neos.Fusion/Tests/Unit/FusionObjects/AttributesImplementationTest.php
  Neos.Neos/Documentation/References/NeosFusionReference.rst
  Neos.Neos/Resources/Private/Fusion/Backend/History/Root.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/Content.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/DimensionsMenu.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/Menu.fusion
  Neos.NodeTypes.ColumnLayouts/Resources/Private/Fusion/Root.fusion
  Neos.NodeTypes.Navigation/Resources/Private/Fusion/Root.fusion
Labels: 9.0, Task, 9.0beta1

#4501 BUGFIX: Don’t query for abstract nodetypes in nodedata repository
  Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
  Neos.ContentRepository/Classes/Domain/Service/NodeTypeManager.php
Labels: Bug, 7.3

#4585 FEATURE: Refactor login controller and improve translation of flash messages
  Neos.Neos/Classes/Controller/LoginController.php
  Neos.Neos/Classes/Controller/TranslationTrait.php
  Neos.Neos/Resources/Private/Fusion/Backend/Views/Login.fusion
  Neos.Neos/Resources/Private/Translations/en/Main.xlf
Labels: Bug, Feature, 9.0

#4603 TASK: Rename node migration commands
  Neos.ContentRepositoryRegistry/Classes/Command/NodeMigrationCommandController.php
Labels: 9.0, Task

#4602 TASK: Remove legacy directory support for node migrations
  Neos.ContentRepositoryRegistry/Classes/Migration/Configuration/YamlConfiguration.php
Labels: 9.0, Task

#4604 TASK: Update nodemigration documentation
  Neos.Neos/Documentation/References/NodeMigrations.rst
Labels: 9.0, Task

#4601 TASK: Leverage `findClosestNode` for "Neos.Neos:Document"
  Neos.Neos/Classes/Controller/Backend/ContentController.php
  Neos.Neos/Classes/View/FusionView.php
  Neos.Neos/Classes/ViewHelpers/Node/ClosestDocumentViewHelper.php
Labels: 9.0, Task

#4607 TASK: Fix documentation builds
  Neos.Media/Documentation/requirements.in
  Neos.Media/Documentation/requirements.txt
  Neos.Neos/Documentation/requirements.in
  Neos.Neos/Documentation/requirements.txt
Labels: Task, 7.3

#4611 TASK: Update nodemigration documentation
  Neos.Neos/Documentation/References/NodeMigrations.rst
Labels: 9.0, Task

#4613 TASK: Remove old node migrations
  Neos.Neos/Migrations/ContentRepository/Version20120921140942.yaml
  Neos.Neos/Migrations/ContentRepository/Version20140723115900.yaml
  Neos.Neos/Migrations/ContentRepository/Version20140930125621.yaml
  Neos.Neos/Migrations/ContentRepository/Version20141103100401.yaml
  Neos.Neos/Migrations/ContentRepository/Version20150907194505.yaml
  Neos.NodeTypes/Migrations/ContentRepository/Version20121030105142.yaml
  Neos.NodeTypes/Migrations/ContentRepository/Version20130326131600.yaml
  Neos.NodeTypes/Migrations/ContentRepository/Version20130515214324.yaml
  Neos.NodeTypes/Migrations/ContentRepository/Version20130516212400.yaml
  Neos.NodeTypes/Migrations/ContentRepository/Version20130911165510.yaml
  Neos.NodeTypes/Migrations/ContentRepository/Version20141210114800.yaml
  Neos.NodeTypes/Migrations/ContentRepository/Version20190304111200.yaml
Labels: 9.0, Task

#4615 FEATURE: Add nodemigrations command to list all available node migration
  Neos.ContentRepositoryRegistry/Classes/Command/NodeMigrationCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Migration/Factory/MigrationFactory.php
Labels: Feature, 9.0

#4599 TASK: Migrate `Neos.Neos:FallbackNode` to fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/FallbackNode.fusion
  Neos.Neos/Resources/Private/Templates/FusionObjects/FallbackNode.html
Labels: 9.0, Task

#4605 TASK: Cleanup format and remove unused imports
  Neos.ContentRepository.Export/src/ImportServiceFactory.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/LegacyMigrationService.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/LegacyMigrationServiceFactory.php
  Neos.ContentRepository.NodeMigration/src/Filter/DimensionSpacePointsFilterFactory.php
  Neos.ContentRepository.NodeMigration/src/NodeMigrationService.php
  Neos.ContentRepository.NodeMigration/src/Transformation/AddNewPropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/ChangeNodeTypeTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RemoveNodeTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RenameNodeAggregateTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/TransformationsFactory.php
  Neos.ContentRepository.StructureAdjustment/src/StructureAdjustmentService.php
  Neos.ContentRepositoryRegistry/Classes/Command/NodeMigrationCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Configuration/NodeTypeEnrichmentService.php
  Neos.ContentRepositoryRegistry/Classes/Factory/EventStore/DoctrineEventStoreFactory.php
  Neos.ContentRepositoryRegistry/Classes/Factory/NodeTypeManager/DefaultNodeTypeManagerFactory.php
  Neos.ContentRepositoryRegistry/Classes/Factory/ProjectionCatchUpTrigger/CatchUpTriggerWithSynchronousOption.php
  Neos.ContentRepositoryRegistry/Classes/Factory/ProjectionCatchUpTrigger/SubprocessProjectionCatchUpTrigger.php
  Neos.ContentRepositoryRegistry/Classes/Service/NodeMigrationGeneratorService.php
Labels: 9.0, Task

#4598 TASK: Remove fluid error view Neos.Neos/Private/Templates/Error/Index.html
  Neos.Neos/Classes/Fusion/Helper/BackendHelper.php
  Neos.Neos/Resources/Private/Fusion/Error/Root.fusion
  Neos.Neos/Resources/Private/Fusion/Error/Views/FusionParserException.fusion
  Neos.Neos/Resources/Private/Fusion/ErrorCase.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/ErrorPage.fusion
  Neos.Neos/Resources/Private/Templates/Error/Index.html
Labels: 9.0, Task

#4563 !!! FEATURE: `Neos.Neos:Site` NodeType
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Assets.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Basic.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Errors.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/References.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Variants.feature
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ParentsOperation.php
  Neos.Media.Browser/Classes/Controller/UsageController.php
  Neos.Neos/Classes/Command/SiteCommandController.php
  Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Domain/Exception/CurrentUserIsMissing.php
  Neos.Neos/Classes/Domain/Exception/LiveWorkspaceIsMissing.php
  Neos.Neos/Classes/Domain/Exception/SiteNodeTypeIsInvalid.php
  Neos.Neos/Classes/Domain/Exception/SitesNodeIsMissing.php
  Neos.Neos/Classes/Domain/Repository/SiteRepository.php
  Neos.Neos/Classes/Domain/Service/NodeSiteResolvingService.php
  Neos.Neos/Classes/Domain/Service/SiteNodeUtility.php
  Neos.Neos/Classes/Domain/Service/SiteService.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.Neos/Classes/Fusion/Helper/SiteHelper.php
  Neos.Neos/Classes/View/FusionExceptionView.php
  Neos.Neos/Classes/View/FusionView.php
  Neos.Neos/NodeTypes/Mixin/Document.yaml
  Neos.Neos/NodeTypes/Mixin/Site.yaml
  Neos.Neos/NodeTypes/Root/Sites.yaml
Labels: 9.0

#4520 !!!TASK: Remove NodeTypeManager from NodeType
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/NodeAggregateCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/NodeTypeChange.php
  Neos.ContentRepository.Core/Classes/NodeType/ConstraintCheck.php
  Neos.ContentRepository.Core/Classes/NodeType/Exception/TetheredNodeNotConfigured.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeManager.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeManagerTest.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeTest.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DisallowedChildNodeAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.Neos/Classes/Service/NodeTypeSchemaBuilder.php
  Neos.Neos/Tests/Unit/NodeTypePostprocessor/DefaultPropertyEditorPostprocessorTest.php
Labels: 9.0

#4588 BUGFIX: Show and apply all changes in workspace review
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Resources/Private/Partials/Module/Management/Workspaces/ContentChangeAttributes.html
  Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html
Labels: Bug, 9.0, 9.0beta1

#4516 BUGFIX: Allow unsetting thumbnail presets
  Neos.Media/Classes/Domain/Service/ThumbnailGenerator.php
Labels: Bug, 7.3

#4624 BUGFIX: Load all thumbnails for an asset to skip further requests
  Neos.Media/Classes/Domain/Model/Thumbnail.php
  Neos.Media/Classes/Domain/Service/ThumbnailService.php
Labels: P: Media, Bug, 7.3

#4627 BUGFIX: Set correct siteNode in WorkspaceController
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
Labels: Bug, 9.0

#4628 TASK: `Workspace::workspaceTitle` is never null
  Neos.ContentRepository.Core/Classes/Projection/Workspace/Workspace.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceFinder.php
  Neos.Neos/Classes/Command/WorkspaceCommandController.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
Labels: 9.0, Task

#4536 BUGFIX: Make `Subtree` immutable and remove `Subtrees`
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Subtree.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Subtrees.php
Labels: Bug, 9.0

#4626 TASK: Remove internal `ContentGraph::findNodeByIdAndOriginDimensionSpacePoint`
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphInterface.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeTrait.php
Labels: 9.0, Task

#4578 BUGFIX: Only discard nodes in same workspace
  Neos.ContentRepository/Classes/Domain/Service/PublishingService.php
Labels: Bug, 8.3, 7.3

#4629 Iterator refactoring
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/NodeAggregateIds.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/NodeRelationAnchorPoints.php
  Neos.ContentRepository.Core/Classes/Dimension/ConfigurationBasedContentDimensionSource.php
  Neos.ContentRepository.Core/Classes/Dimension/ContentDimensionConstraintSet.php
  Neos.ContentRepository.Core/Classes/Dimension/ContentDimensionValueVariationEdges.php
  Neos.ContentRepository.Core/Classes/Dimension/ContentDimensionValues.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/DimensionSpacePointSet.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/OriginDimensionSpacePointSet.php
  Neos.ContentRepository.Core/Classes/EventStore/Events.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Dto/NodeReferencesSnapshot.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/SerializedPropertyValues.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Dto/CoverageNodeMoveMappings.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Dto/OriginNodeMoveMappings.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/NodeReferencesToWrite.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/SerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Dto/NodeIdsToPublishOrDiscard.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeNames.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/CoverageByOrigin.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/Ordering/Ordering.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeAggregates.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Nodes.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/OriginByCoverage.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/References.php
  Neos.ContentRepository.Core/Classes/Projection/Projections.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/Workspaces.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeAggregateIds.php
  Neos.ContentRepository.Core/Tests/Unit/Dimension/ContentDimensionTest.php
  Neos.ContentRepository.Core/Tests/Unit/DimensionSpace/Fixtures/VariationExampleDimensionSource.php
  Neos.ContentRepository.Export/src/Asset/ValueObject/SerializedImageAdjustments.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Helpers/GherkinTableNodeBasedContentDimensionSource.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Helpers/NodeDiscriminators.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeAggregateTrait.php
  Neos.Fusion/Classes/Core/FusionSourceCodeCollection.php
  Neos.Fusion/Tests/Unit/Core/FusionSourceCodeDtosTest.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetIdsByProperty.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsagesByContentRepository.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/UriPathResolver/SegmentMapping.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentNodeInfos.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
Labels: 9.0

#4617 BUGFIX 4608 - tethered site children uri path segment
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeModification.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/TetheredSiteChildDocuments.feature
Labels: 9.0

#4640 BUGFIX: Fix `DocumentUriPathProjection` for newly created child nodes of disabled nodes
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/DisableNodes.feature
Labels: Bug, 9.0

#4561 BUGFIX: Reduce nodetype schema size
  Neos.Neos/Classes/Service/NodeTypeSchemaBuilder.php
  Neos.Neos/Tests/Functional/Service/NodeTypeSchemaBuilderTest.php
Labels: P: Node Types, Bug, 8.3

#4643 TASK: Improve phpstan coverage
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjectionFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/ProjectionHypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/Query/ProjectionHypergraphQuery.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/Query/ProjectionHypergraphQueryInterface.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/InterDimensionalVariationGraph.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionInterface.php
  Neos.ContentRepository.Core/Classes/Projection/Projections.php
  Neos.ContentRepository.Export/src/Asset/ValueObject/SerializedImageVariant.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Command/CrCommandController.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Helpers/AssetExtractor.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Helpers/NodeDataLoader.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/LegacyMigrationService.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToAssetsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Security/ImpersonateAspect.php
  phpstan.neon
Labels: 9.0, Task

#4646 TASK: Command constructor followup to #4489
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/Command/RemoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Command/PublishIndividualNodesFromWorkspace.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeReferencing.php
Labels: 9.0, Task

#4623 TASK: Render menu prototypes without fluid
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeAggregateIds.php
  Neos.Fusion/Classes/Service/RenderAttributesTrait.php
  Neos.Fusion/Tests/Unit/Service/HtmlAugmenterTest.php
  Neos.Neos/Classes/Fusion/AbstractMenuItemsImplementation.php
  Neos.Neos/Classes/Fusion/DimensionMenuItem.php
  Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php
  Neos.Neos/Classes/Fusion/MenuItem.php
  Neos.Neos/Classes/Fusion/MenuItemState.php
  Neos.Neos/Classes/Fusion/MenuItemsImplementation.php
  Neos.Neos/Documentation/References/NeosFusionReference.rst
  Neos.Neos/Resources/Private/Fusion/Prototypes/BreadcrumbMenu.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/BreadcrumbMenuItems.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/DimensionsMenu.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/Menu.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/MenuItemListRenderer.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/MenuItems.fusion
  Neos.Neos/Resources/Private/Templates/FusionObjects/BreadcrumbMenu.html
  Neos.Neos/Resources/Private/Templates/FusionObjects/DimensionsMenu.html
  Neos.Neos/Resources/Private/Templates/FusionObjects/Menu.html
Labels: 9.0, Task, 9.0beta1

#4555 !!! TASK: Remove NodeSearchServiceInterface and implementation
  Neos.Neos/Classes/Domain/Service/NodeSearchService.php
  Neos.Neos/Classes/Domain/Service/NodeSearchServiceInterface.php
  Neos.Neos/Configuration/Objects.yaml
Labels: 9.0

#4526 BUGFIX: `props` will be unset after an exception
  Neos.Fusion/Classes/FusionObjects/ComponentImplementation.php
Labels: Bug, 7.3

#4632 TASK: improve dimension space point documentation
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/Feature/NodeCreation.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/AbstractDimensionSpacePoint.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/DimensionSpacePoint.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/DimensionSpacePointSet.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/OriginDimensionSpacePoint.php
  Neos.ContentRepository.TestSuite/Classes/Unit/NodeSubjectProvider.php
  Neos.Neos/Classes/Domain/Service/SiteNodeUtility.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/RequestToDimensionSpacePointContext.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/UriPathResolver.php
  Neos.Neos/Tests/Functional/Fusion/NodeHelperTest.php
Labels: 9.0, Task

#4641 TASK: Behat-based Fusion tests (v1)
  Neos.ContentRepository/Tests/Behavior/Features/Bootstrap/NodeOperationsTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FusionTrait.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCase.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCollection.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/ConvertUris.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/Menu.feature
Labels: 8.3, Task

#4652 TASK: Restore functionality of RenderingMode view-helpers
  Neos.Fusion/Classes/ViewHelpers/FusionContextTrait.php
  Neos.Neos/Classes/ViewHelpers/Rendering/AbstractRenderingStateViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Rendering/InBackendViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Rendering/InEditModeViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Rendering/InPreviewModeViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Rendering/LiveViewHelper.php
Labels: 9.0, Task, 9.0beta1

#4662 4610 - save thered nodes from disallowedChildnodes structure adjustments
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/DisallowedChildNodesAndTetheredNodes.feature
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DisallowedChildNodeAdjustment.php
Labels: 9.0

#4658 FEATURE: Add additional factory methods `createWithAllowedNodeTypeNames` and `createWithDisallowedNodeTypeNames` to the nodeTypeConstraints.
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeTypeConstraints.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ParentsOperation.php
Labels: Feature, 9.0

#4667 TASK: Static Node constructor
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php
  Neos.ContentRepository.TestSuite/Classes/Unit/NodeSubjectProvider.php
  Neos.Neos/Tests/Functional/Fusion/NodeHelperTest.php
Labels: 9.0, Task

#4666 TASK: All dependencies within collection point to `self.version`
  Neos.Neos/composer.json
Labels: Task, 7.3

#4651 TASK: Behat-based Fusion tests (v1)
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FusionTrait.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCase.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCollection.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/ConvertUris.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/Menu.feature
Labels: 9.0, Task

#4670 BUGFIX: Html prototype is now a ContentComponent
  Neos.NodeTypes.Html/Resources/Private/Fusion/Html.fusion
  Neos.NodeTypes.Html/Resources/Private/Templates/NodeTypes/Html.html
Labels: Bug, 9.0

#4664 FEATURE: Add `Neos.Node.subgraphForNode()` to EEL helper
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
Labels: Feature, 9.0
