Repository neos/neos-development-collection, pull requests merged in 2023-06, with the labels that each got.

#4210 TASK: Adjust link editor documentation
  Neos.Neos/Documentation/References/PropertyEditorReference.rst
Labels: T: Documentation, 8.3, Task

#4319 DOCS: Add import example to the 9.0 readme
  Readme.rst
Labels: 9.0

#4281 BUGFIX: Newly created node not selected
  Neos.Neos/Classes/Fusion/ExceptionHandlers/PageHandler.php
  Neos.Neos/Classes/Service/ContentElementWrappingService.php
Labels: Bug, 9.0

#4349 FEATURE: 9.0 Implement `ContentSubgraphInterface::findAncestorNodes` and `countAncestorNodes`
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/AncestorNodes.feature
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountAncestorNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindAncestorNodesFilter.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/EventSourcedTrait.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/NodeOperationsTrait.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/Fusion/AbstractMenuItemsImplementation.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
Labels: Feature, 9.0

#4306 BUGFIX: flow command typo in exception in nearestContentCollection method
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
Labels: Bug, 7.3

#4367 TASK: Change variablename in Neos Fusion documentation
  Neos.Neos/Documentation/References/NeosFusionReference.rst
Labels: Task, 7.3

#4288 BUGFIX: Undefined array key "ui" in nodeType creationDialog
  Neos.Neos/Classes/NodeTypePostprocessor/DefaultPropertyEditorPostprocessor.php
  Neos.Neos/Tests/Unit/NodeTypePostprocessor/DefaultPropertyEditorPostprocessorTest.php
Labels: Bug, 7.3

#4352 TASK: PHP 8.1 deprecations compatibility
  Neos.ContentRepository/Classes/Domain/ContentSubgraph/NodePath.php
  Neos.ContentRepository/Classes/Domain/NodeAggregate/NodeAggregateIdentifier.php
  Neos.ContentRepository/Classes/Domain/NodeType/NodeTypeName.php
  Neos.Fusion/Classes/FusionObjects/AbstractFusionObject.php
  Neos.Fusion/Classes/FusionObjects/Helpers/LazyProps.php
  Neos.Fusion/Tests/Unit/Core/ParserTest.php
  Neos.Media/Classes/Domain/Model/AssetSource/Neos/NeosAssetProxyQueryResult.php
  Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
  Neos.Neos/Tests/Unit/Domain/Service/DomainMatchingStrategyTest.php
  Neos.Neos/Tests/Unit/Routing/FrontendNodeRoutePartHandlerTest.php
Labels: Task, 7.3

#4209 BUGFIX: Allow string position values in NodeType schema
  Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
Labels: Bug, 7.3

#4214 TASK: add default value for generatorName at kickstart command in SiteKickstarter
  Neos.SiteKickstarter/Classes/Command/KickstartCommandController.php
Labels: Task, 7.3

#4335 TASK: Use command instead of event in Behat scenarios to create root nodes in order to prevent impossible states
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Projection/ProjectionIntegrityViolationDetection/HierarchyIntegrityIsProvided.feature
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Projection/ProjectionIntegrityViolationDetection/NodesHaveAtMostOneParentPerSubgraph.feature
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Projection/ProjectionIntegrityViolationDetection/ReferenceIntegrityIsProvided.feature
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Projection/ProjectionIntegrityViolationDetection/RestrictionIntegrityIsProvided.feature
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Projection/ProjectionIntegrityViolationDetection/RestrictionsArePropagatedRecursively.feature
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Projection/ProjectionIntegrityViolationDetection/SiblingsAreDistinctlySorted.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/ForkContentStreamWithDisabledNodesWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/ForkContentStreamWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/AddDimensionShineThrough.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/AddNewProperty_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/ChangePropertyValue_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/ChangePropertyValue_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/Filter_NodeName_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/Filter_PropertyNotEmpty_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/Filter_PropertyValue_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/MoveDimensionSpacePoint.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/NodeTypeAdjustment_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/NodeTypeAdjustment_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/RemoveNodes_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/RemoveProperty_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/RenameNodeAggregate_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/RenameProperty_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/StripTagsOnProperty_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeCopying/CopyNode_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeMove/MoveNodeAggregate.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeMove/MoveNodeAggregateConsideringDisableStateWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeMove/MoveNodeAggregateWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeMove/MoveNodeAggregate_NewParent_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeMove/MoveNodeAggregate_NoNewParent_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodePropertyConversion/NodePropertyConversion.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodePublishing/AllCommandsAreImplemented.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodePublishing/PublishAndDiscardIndividualNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodePublishing/PublishMovedNodesWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRenaming/ChangeNodeAggregateName.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRetyping/ChangeNodeAggregateType_BasicErrorCases.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRetyping/ChangeNodeAggregateType_DeleteStrategy.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRetyping/ChangeNodeAggregateType_HappyPathStrategy.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ProjectionIntegrityViolationDetection/AllNodesCoverTheirOrigin.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ProjectionIntegrityViolationDetection/NodeAggregateIdentifiersAreUniquePerSubgraph.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ProjectionIntegrityViolationDetection/NodeAggregatesAreConsistentlyClassifiedPerContentStream.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ProjectionIntegrityViolationDetection/NodeAggregatesAreConsistentlyTypedPerContentStream.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ProjectionIntegrityViolationDetection/ReferenceIntegrityIsProvided.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ProjectionIntegrityViolationDetection/TetheredNodesAreNamed.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/DimensionMismatch.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/DisallowedChildNode.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/Properties.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/TetheredNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/TetheredNodesReordering.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/UnknownNodeType.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/WorkspacePublishing/RebasingAutoCreatedNodesWorks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/WorkspacePublishing/WorkspaceBasedContentPublishing.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/NodeOperationsOnMultipleWorkspaces.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/SingleNodeOperationsOnLiveWorkspace.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Basic.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Dimensions.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/DisableNodes.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Lowlevel_ProjectionTests.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/MultiSiteLinking.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Shortcuts.feature
Labels: 9.0, Task

#4363 9.0 FEATURE: Allow route resolving of disabled nodes
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/DisableNodes.feature
Labels: 9.0

#4215 SiteKickstarter: remove package sugestion for neos/seo
  Neos.SiteKickstarter/Classes/Generator/AfxTemplateGenerator.php
Labels: 7.3

#4359 BUGFIX: Fusion's FilePatternResolver windows compatible
  Neos.Fusion/Classes/Core/ObjectTreeParser/FilePatternResolver.php
Labels: Bug, 8.0
