Repository neos/neos-development-collection, pull requests merged in 2023-08, with the labels that each got.

#4382 BUGFIX: Flush route caches with DocumentUriPathProjection CatchUpHook
  Neos.Neos/Classes/FrontendRouting/CatchUpHook/RouterCacheHook.php
  Neos.Neos/Classes/FrontendRouting/CatchUpHook/RouterCacheHookFactory.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathFinder.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/Package.php
  Neos.Neos/Configuration/Settings.ContentRepositoryRegistry.yaml
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/RouteCache.feature
Labels: Bug, 9.0

#3562 BUGFIX: Assign original asset collections to variant
  Neos.Media/Classes/Domain/Model/Image.php
  Neos.Media/Classes/Domain/Model/ImageVariant.php
Labels: P: Media, T: PHP, Bug, 7.3

#4432 BUGFIX: Fix casing of contentStreamId in ContentStreamFinder::findAllIds()
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamFinder.php
Labels: Bug, 9.0

#4330 !!! TASK: Remove plugin views
  Neos.Neos/Classes/Aspects/PluginUriAspect.php
  Neos.Neos/Classes/Controller/Backend/ContentController.php
  Neos.Neos/Classes/Domain/Model/PluginViewDefinition.php
  Neos.Neos/Classes/Fusion/PluginViewImplementation.php
  Neos.Neos/Classes/NodeTypePostprocessor/PluginNodeTypePostprocessor.php
  Neos.Neos/Classes/Service/PluginService.php
  Neos.Neos/NodeTypes/Content/PluginView.yaml
  Neos.Neos/NodeTypes/Mixin/Plugin.yaml
  Neos.Neos/Resources/Private/Fusion/Prototypes/PluginView.fusion
Labels: 9.0, Task

#4393 !!!FEATURE: (Neos.Neos) Track created nodes in PendingChangesProjection
  Neos.Neos/Classes/PendingChangesProjection/Change.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: 9.0

#4368 !!! BUGFIX: Docs references and make Reference::$name a ReferenceName
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Reference.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/References.php
Labels: 9.0, Task

#4365 TASK: Test create node aggregate with node with tethered child node of invalid configured name
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/02-CreateNodeAggregateWithNode_WithoutDimensions.feature
Labels: 9.0, Task

#4433 FEATURE: Allow uriPathSuffix to be specified per site
  Neos.Neos/Classes/Domain/Model/SiteConfiguration.php
  Neos.Neos/Classes/FrontendRouting/CrossSiteLinking/CrossSiteLinker.php
  Neos.Neos/Classes/FrontendRouting/CrossSiteLinking/CrossSiteLinkerInterface.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/DelegatingResolver.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/DimensionResolverInterface.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/RequestToDimensionSpacePointContext.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/CompositeResolver.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/NoopResolver.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/UriPathResolver.php
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
  Neos.Neos/Classes/FrontendRouting/Exception/ResolvedSiteNotFoundException.php
  Neos.Neos/Classes/FrontendRouting/Exception/TargetSiteNotFoundException.php
  Neos.Neos/Configuration/Routes.Frontend.yaml
  Neos.Neos/Configuration/Routes.yaml
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/Migrations/Code/Version20230801154834.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
Labels: Feature, 9.0

#4440 TASK: Use NodeAddressFactory for NodeAddress creation
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
  Neos.Neos/Classes/FrontendRouting/NodeAddressFactory.php
Labels: 9.0, Task

#4325 TASK: Revert wip nullable PropertyType `type: ?string`
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/PropertyType.php
  Neos.ContentRepository.Core/Tests/Unit/Infrastructure/Property/PropertyTypeTest.php
Labels: 9.0, Task

#4444 BUGFIX: Don't allow explicit ordering of projections
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
Labels: Bug, 9.0

#4416 TASK: Remove `contentstream:import` and `contentstream:export` CLI commands
  Neos.ContentRepositoryRegistry/Classes/Command/ContentStreamCommandController.php
Labels: 9.0, Task

#4453 BUGFIX: Use correct URL to FontAwesome icons
  Neos.Neos/Documentation/References/NodeTypeDefinition.rst
Labels: Bug, 7.3

#4438 BUGFIX: show title on hover in ImpersonateButton
  Neos.Neos/Resources/Public/JavaScript/Main.min.js
  Neos.Neos/Resources/Public/JavaScript/Main.min.js.map
  Neos.Neos/Resources/Public/JavaScript/Templates/ImpersonateButton.js
Labels: Bug, 8.0

#4405 !!! FEATURE: Overhaul catch up implementation
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjectionFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/HypergraphProjection.php
  Neos.ContentGraph.PostgreSQLAdapter/src/HypergraphProjectionFactory.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandResult.php
  Neos.ContentRepository.Core/Classes/CommandHandler/PendingProjections.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/EventStore/EventNormalizer.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepository.Core/Classes/EventStore/Events.php
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositoryFactory.php
  Neos.ContentRepository.Core/Classes/Factory/ProjectionsAndCatchUpHooksFactory.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUpHookFactories.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUpOptions.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphProjection.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamProjection.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamProjectionFactory.php
  Neos.ContentRepository.Core/Classes/Projection/NodeHiddenState/NodeHiddenStateProjection.php
  Neos.ContentRepository.Core/Classes/Projection/NodeHiddenState/NodeHiddenStateProjectionFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionFactoryInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionInterface.php
  Neos.ContentRepository.Core/Classes/Projection/Projections.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionsAndCatchUpHooks.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjectionFactory.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/EventSourcedTrait.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Command/CrCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/SubprocessProjectionCatchUpCommandController.php
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
  Neos.ContentRepositoryRegistry/Classes/Factory/ProjectionCatchUpTrigger/CatchUpTriggerWithSynchronousOption.php
  Neos.ContentRepositoryRegistry/Classes/Service/ProjectionReplayService.php
  Neos.ContentRepositoryRegistry/Classes/Service/ProjectionReplayServiceFactory.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjection.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjectionFactory.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjectionFactory.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjectionFactory.php
Labels: Feature, 9.0
