Repository neos/neos-development-collection, pull requests merged in 2023-11, with the labels that each got.

#3372 TASK: Rewrite Neos.Neos:Shortcut to pure fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/Shortcut.fusion
  Neos.Neos/Resources/Private/Fusion/RootCase.fusion
  Neos.Neos/Resources/Private/Styles/Main.scss
  Neos.Neos/Resources/Private/Styles/Shortcut.scss
  Neos.Neos/Resources/Private/Styles/_Global.scss
  Neos.Neos/Resources/Private/Templates/FusionObjects/Shortcut.html
  Neos.Neos/Resources/Public/Styles/Shortcut.css
  Neos.Neos/webpack.styles.config.js
Labels: 9.0, Task

#4303 BUGFIX: Allow disabling of auto-created Image Variants
  Neos.Media.Browser/Classes/Controller/AssetController.php
  Neos.Media.Browser/Configuration/Policy.yaml
  Neos.Media.Browser/Resources/Private/Templates/Asset/Variants.html
  Neos.Media.Browser/Resources/Private/Translations/en/Main.xlf
  Neos.Media/Classes/Domain/Service/AssetVariantGenerator.php
  Neos.Media/Classes/Package.php
  Neos.Media/Configuration/Settings.yaml
  Neos.Media/Documentation/VariantPresets.rst
Labels: Bug, 7.3

#4676 TASK: NodeController::show drop support for showInvisible
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
Labels: 9.0, Task

#4675 Sort siblings before reassigning positions
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/NodeMove.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/MoveNodeAggregate.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/MoveNodeAggregateConsideringDisableStateWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/MoveNodeAggregateWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/MoveNodeAggregate_NewParent_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/MoveNodeAggregate_NoNewParent_Dimensions.feature
Labels: 9.0

#4678 FEATURE 4327 - Expose a subgraph's identity
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjectionFactory.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/HypergraphProjection.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/HypergraphProjectionFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphInterface.php
Labels: 9.0

#4654 !!! TASK: Change default value for `body` of `Neos.Neos:Page` from `Neos.Fusion:Template` to `Neos.Fusion:Join`
  Neos.Neos/Documentation/References/NeosFusionReference.rst
  Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion
Labels: 9.0, Task

#4661 BUGFIX 4343 - Apply constraint checks to ChangeNodeAggregateName
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/01-RemoveNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRenaming/01_ChangeNodeAggregateName_ConstraintChecks.feature
  Neos.ContentRepository.Core/Classes/Feature/NodeRenaming/NodeRenaming.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeRenaming.php
Labels: 9.0

#4647 BUGFIX: Fix typos in deprecated Fusion object reference
  Neos.Neos/Documentation/References/NeosFusionReference.rst
Labels: Bug, 9.0

#4645 TASK: Remove legacy `unstructured` node type
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToAssetsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Assets.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Basic.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Errors.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/References.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Variants.feature
  Neos.Neos/NodeTypes/Unstructured.yaml
Labels: 9.0, Task

#4480 !!! TASK Make NodeType::getPropertyType throw
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PropertyOperation.php
Labels: 9.0

#4668 FEATURE / BUGFIX - 4663 tethered root children
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/01-RootNodeCreation/03-CreateRootNodeAggregateWithNodeAndTetheredChildren_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/01-RootNodeCreation/04-CreateRootNodeAggregateWithNodeAndTetheredChildren_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/01-RootNodeCreation/05-CreateRootNodeAggregateWithNode_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/TetheredNodes.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/TetheredNodeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/NodeTypeChange.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Command/CreateRootNodeAggregateWithNode.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/RootNodeHandling.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DimensionAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/StructureAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.StructureAdjustment/src/StructureAdjustmentService.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeCreation.php
Labels: 9.0

#4671 TASK: Ensure `Neos.Neos:*Menu` prototypes behave according to tests in Neos 9
  Neos.Neos/Classes/Fusion/AbstractMenuItemsImplementation.php
  Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php
  Neos.Neos/Classes/Fusion/MenuItemsImplementation.php
  Neos.Neos/Documentation/References/NeosFusionReference.rst
  Neos.Neos/Resources/Private/Fusion/Prototypes/BreadcrumbMenu.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/BreadcrumbMenuItems.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/DimensionsMenu.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/DimensionsMenuItems.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/Menu.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/MenuItems.fusion
  Neos.Neos/Tests/Behavior/Features/Fusion/Menu.feature
Labels: 9.0, Task

#4681 BUGFIX: broken references in NeosFusionReference.rst
  Neos.Neos/Documentation/References/NeosFusionReference.rst
Labels: Bug, 9.0

#4679 TASK: Cleanup usage of `NodeTypeConstraintsWithSubNodeTypes`
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/NodeType/ConstraintCheck.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeManager.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeTypeConstraintsWithSubNodeTypes.php
Labels: 9.0, Task

#4686 TASK: 2nd fixup for PR #4641 ContentCollection.feature
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FusionTrait.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCollection.feature
Labels: 8.3, Task

#4669 TASK: Use new Behat `FlowBootstrapTrait`
  .composer.json
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/ProjectionIntegrityViolationDetectionTrait.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepositoryRegistry/Classes/TestSuite/Behavior/CRRegistrySubjectProvider.php
  Neos.Neos/Classes/Service/EditorContentStreamZookeeper.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/BrowserTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Basic.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Dimensions.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/DisableNodes.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Lowlevel_ProjectionTests.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/MultiSiteLinking.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/RouteCache.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Shortcuts.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/TetheredSiteChildDocuments.feature
  composer.json
Labels: 9.0, Task

#4690 TASK: Add support information to package composer.json
  Neos.ContentRepository/composer.json
  Neos.Diff/composer.json
  Neos.Fusion.Afx/composer.json
  Neos.Fusion/composer.json
  Neos.Media.Browser/composer.json
  Neos.Media/composer.json
  Neos.Neos/composer.json
  Neos.NodeTypes.AssetList/composer.json
  Neos.NodeTypes.BaseMixins/composer.json
  Neos.NodeTypes.ColumnLayouts/composer.json
  Neos.NodeTypes.ContentReferences/composer.json
  Neos.NodeTypes.Form/composer.json
  Neos.NodeTypes.Html/composer.json
  Neos.NodeTypes.Navigation/composer.json
  Neos.NodeTypes/composer.json
  Neos.SiteKickstarter/composer.json
Labels: Task, 7.3

#4551 !!! TASK: Rename `NodeTypeConstraints` to `NodeTypeCriteria`
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/Query/CommonGraphQueryOperations.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/Query/QueryUtility.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/AncestorNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/ChildNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/ClosestNode.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/DescendantNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindSubtree.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/References.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/SiblingNodes.feature
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache/AllChildNodesByNodeIdCache.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountAncestorNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountBackReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountDescendantNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindAncestorNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindBackReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindClosestNodeFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindDescendantNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindPrecedingSiblingNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindSubtreeFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindSucceedingSiblingNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/NodeType/ExpandedNodeTypeCriteria.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/NodeType/NodeTypeCriteria.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ChildrenOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/FindOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ParentsOperation.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/Domain/Repository/SiteRepository.php
  Neos.Neos/Classes/Domain/Service/NodeSiteResolvingService.php
  Neos.Neos/Classes/Domain/Service/SiteService.php
  Neos.Neos/Classes/Fusion/MenuItemsImplementation.php
  Neos.Neos/Classes/View/FusionView.php
  Neos.Neos/Classes/ViewHelpers/Node/ClosestDocumentViewHelper.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FusionTrait.php
Labels: 9.0

#4682 !!! TASK: Deprecate and refactor `Neos.Neos:PrimaryContent`
  Neos.Fusion/Tests/Unit/FusionObjects/CaseImplementationTest.php
  Neos.Neos/Documentation/References/NeosFusionReference.rst
  Neos.Neos/Resources/Private/Fusion/Deprecated/PrimaryContent.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/PrimaryContent.fusion
  Neos.Neos/Tests/Functional/Fusion/Fixtures/Base.fusion
  Neos.NodeTypes/Resources/Private/Fusion/Documents/Page.fusion
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/Fusion/Document/AbstractPage.fusion
Labels: 9.0

#4695 TASK: Add behat tests for flowQuery cr operations
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
Labels: 8.3, Task

#4558 BUGFIX: SiteDetectionMiddleware continue if no site exists
  Neos.Neos/Classes/FrontendRouting/SiteDetection/SiteDetectionMiddleware.php
Labels: Bug, 9.0

#4700 TASK: Drop `provide` from template [skip ci]
  .composer.json
Labels: 9.0, Task

#4698 TASK: Improve performance of `DocumentUriPathProjection`
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
Labels: 9.0, Task

#4702 TASK: Add tests for FlowQuery `nextUntil`, `prevUntil`, `siblings` and `find`
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
Labels: 8.3, Task

#4704 BUGFIX: Adjust Neos.NodeTypes:Page to updated Neos.Neos:Page
  Neos.NodeTypes/Resources/Private/Fusion/Documents/Page.fusion
  Neos.NodeTypes/Resources/Private/Templates/Documents/Page.html
Labels: Bug, 9.0, 9.0beta1

#4619 BUGFIX: Fix and make `nodeTypes:show` command usable
  Neos.ContentRepository/Classes/Command/NodeTypesCommandController.php
Labels: Bug, Feature, 8.3

#4713 TASK: Fix declared dependencies of Neos.Neos
  .composer.json
  .github/workflows/build.yml
  Neos.Neos/composer.json
  composer.json
Labels: 9.0, Task

#4703 TASK: Improve PhpStan By Fixing Flow
  Neos.ContentRepository.LegacyNodeMigration/Classes/Command/CrCommandController.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/FilterOperation.php
  Neos.ContentRepositoryRegistry/Classes/Command/NodeTypesCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Configuration/NodeTypesLoader.php
  Neos.ContentRepositoryRegistry/Classes/Package.php
  Neos.Neos/Classes/Controller/LoginController.php
  Neos.Neos/Classes/Controller/Module/AbstractModuleController.php
  Neos.Neos/Classes/Controller/Module/Administration/PackagesController.php
  Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Service/Controller/AbstractServiceController.php
  bootstrap-phpstan.php
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: 9.0, Task

#4620 TASK: Add test for nodeType property unset behaviour
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeManagerTest.php
Labels: 9.0, Task

#4720 TASK: Reimplement `workspace:delete`
  Neos.Neos/Classes/Command/WorkspaceCommandController.php
Labels: 9.0, Task

#4715 BUGFIX: `SiteDetectionMiddleware` should not crash without doctrine migrations
  Neos.Neos/Classes/FrontendRouting/SiteDetection/SiteDetectionMiddleware.php
  Neos.Neos/Classes/FrontendRouting/SiteDetection/SiteDetectionResult.php
Labels: Bug, 9.0

#4740 TASK: Fix documentation of `cr:import`
  Neos.Neos/Classes/Command/CrCommandController.php
Labels: 9.0, Task

#4691 TASK: Adjust neos/neos css build to work on apple silicon
  Neos.Neos/Resources/Private/Styles/Typeplate/_Typeplate.scss
  Neos.Neos/Resources/Public/Styles/Error.css
  Neos.Neos/Resources/Public/Styles/Error.css.map
  Neos.Neos/Resources/Public/Styles/Lite.css
  Neos.Neos/Resources/Public/Styles/Lite.css.map
  Neos.Neos/Resources/Public/Styles/Login.css
  Neos.Neos/Resources/Public/Styles/Login.css.map
  Neos.Neos/Resources/Public/Styles/Main.css
  Neos.Neos/Resources/Public/Styles/Main.css.map
  Neos.Neos/Resources/Public/Styles/Minimal.css
  Neos.Neos/Resources/Public/Styles/Minimal.css.map
  Neos.Neos/Resources/Public/Styles/RawContentMode.css
  Neos.Neos/Resources/Public/Styles/RawContentMode.css.map
  Neos.Neos/Resources/Public/Styles/Welcome.css
  Neos.Neos/Resources/Public/Styles/Welcome.css.map
  Neos.Neos/package.json
  Neos.Neos/yarn.lock
Labels: Task, 7.3

#4753 BUGFIX: Check if image is possible to refit on replacement
  Neos.Media/Classes/Domain/Service/AssetService.php
Labels: Bug, 7.3

#4744 BUGFIX: Partially repair convert uris implementation according to some 8.3 tests
  Neos.Neos/Classes/FrontendRouting/NodeUriBuilder.php
  Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/AssetTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ConvertUris.feature
Labels: Bug, 9.0

#4733 TASK: #4396 prefer renderingMode::isEdit over node::isLive
  Neos.Neos/Classes/Domain/Service/UserService.php
  Neos.Neos/Classes/Fusion/ContentElementEditableImplementation.php
  Neos.Neos/Classes/Fusion/ContentElementWrappingImplementation.php
  Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
  Neos.Neos/Classes/Fusion/ExceptionHandlers/NodeWrappingHandler.php
  Neos.Neos/Classes/Fusion/ExceptionHandlers/PageHandler.php
  Neos.Neos/Classes/Service/ContentElementEditableService.php
  Neos.Neos/Classes/Service/ContentElementWrappingService.php
  Neos.Neos/Classes/ViewHelpers/ContentElement/EditableViewHelper.php
  Neos.Neos/Classes/ViewHelpers/ContentElement/WrapViewHelper.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FusionTrait.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ConvertUris.feature
Labels: 9.0, Task

#4757 TASK: 4305 Mark *Serialized* commands `@internal`
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNode.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNodeAndSerializedProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Command/SetSerializedNodeProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetSerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/SerializedNodeReference.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/SerializedNodeReferences.php
Labels: 9.0, Task

#4750 TASK: Speed up Behat tests
  Neos.ContentRepository.BehavioralTests/Classes/TestSuite/Behavior/CRBehavioralTestsSubjectProvider.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
  Neos.ContentRepositoryRegistry.TestSuite/Classes/Behavior/CRRegistrySubjectProvider.php
  Neos.ContentRepositoryRegistry/Configuration/Settings.yaml
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
Labels: 9.0, Task

#4743 TASK: Fusion Behat Test Make Sure To Throw Runtime Exceptions
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FusionTrait.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCollection.feature
Labels: 8.3, Task

#4328 TASK: docs and readability of `Node::getProperty`
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/SerializedPropertyValue.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/SerializedPropertyValues.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/PropertyCollection.php
  Neos.ContentRepository.NodeMigration/src/Transformation/StripTagsOnPropertyTransformationFactory.php
Labels: 9.0, Task

#4765 BUGFIX: flashmessages in legacy modules work as expected
  Neos.Neos/Resources/Public/JavaScript/Main.min.js
  Neos.Neos/Resources/Public/JavaScript/Main.min.js.LICENSE.txt
  Neos.Neos/Resources/Public/JavaScript/Main.min.js.map
  Neos.Neos/Resources/Public/JavaScript/Services/Notification.js
  Neos.Neos/Resources/Public/Styles/Error.css.map
  Neos.Neos/Resources/Public/Styles/Lite.css.map
  Neos.Neos/Resources/Public/Styles/Login.css.map
  Neos.Neos/Resources/Public/Styles/Main.css.map
  Neos.Neos/Resources/Public/Styles/Minimal.css.map
  Neos.Neos/Resources/Public/Styles/RawContentMode.css.map
  Neos.Neos/Resources/Public/Styles/Welcome.css.map
Labels: Bug, 7.3

#4730 TASK: Deterministic projection schema with sensible defaults
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalSchemaFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamProjection.php
  Neos.ContentRepository.Core/Classes/Projection/NodeHiddenState/NodeHiddenStateProjection.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepository.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathSchemaBuilder.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: Bug, 9.0, Task

#4770 BUGFIX: Respect position when ordering nodes
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/NodeTraversalTrait.php
Labels: Bug, 9.0

#4755 !!! TASK: Substitute `findChildNodeConnectedThroughEdgeName` with `findNodeByPath `
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodeByPathAsNodeName.feature
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNode.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/NodeTypeChange.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Command/CreateRootNodeAggregateWithNode.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/AbsoluteNodePath.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodePath.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeName.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ChildrenOperation.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteRuntimeVariables.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeTrait.php
  Neos.Neos/Classes/Domain/Service/SiteNodeUtility.php
Labels: 9.0

#4771 TASK: Use DBAL QueryBuilder in `ContentGraph`
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
Labels: 9.0, Task
