Repository neos/neos-development-collection, pull requests merged in 2023-12, with the labels that each got.

#4789 TASK Fix phpstan complains about QueryBuilder::execute return value
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
Labels: 9.0

#4793 TASK: Use role label in list users/new user view if available
  Neos.Neos/Resources/Private/Partials/Module/Shared/Roles.html
  Neos.Neos/Resources/Private/Templates/Module/Administration/Users/New.html
Labels: Task, 7.3

#4724 BUGFIX: Filter for assets by asset collection without overriding existing WHERE conditions
  Neos.Media/Classes/Domain/Repository/AssetRepository.php
  Neos.Media/Tests/Functional/Domain/Repository/AssetRepositoryTest.php
Labels: Bug, 7.3

#4782 BUGFIX: Add workspace hash to NodeDynamicTag_ and AssetDynamicTag_ cache tags
  Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
  Neos.Neos/Tests/Unit/Fusion/ConvertUrisImplementationTest.php
Labels: Bug, 7.3

#4785 BUGFIX: Replace incorrect mention of itemRenderer to itemReducer
  Neos.Neos/Documentation/References/NeosFusionReference.rst
Labels: Bug, 8.3

#4648 BUGFIX: Remove unnecessary basemixins dependency for ContentReferences
  Neos.NodeTypes.ContentReferences/composer.json
Labels: Bug, dependencies, 8.3, 7.3

#4802 BUGFIX: Filter for assets by asset collection by using constraints
  Neos.Media/Classes/Domain/Repository/AssetRepository.php
Labels: Bug, 7.3

#4805 BUGFIX Use nodeTypes as method named argument name
  Neos.Media.Browser/Classes/Controller/UsageController.php
Labels: 9.0

#4807 BUGFIX: Skip node data processing for invalid properties
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToAssetsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Assets.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/References.feature
Labels: Bug, 9.0

#4803 TASK: Removes neos/neos-setup
  .composer.json
  composer.json
Labels: Bug, Task, 8.0

#4806 TASK: Extends exception message with NodeType name
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
Labels: 9.0, Task

#4795 BUGFIX: node:repair fails with could not be converted to string
  Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php
Labels: Bug, 7.3

#4792 TASK: Make restrictionrelation less dependent subquery
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
Labels: 9.0, Task

#4490 FEATURE: Add HTTP Status Code to Shortcuts
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Configuration/Settings.yaml
Labels: Feature, 9.0
