Repository neos/neos-development-collection, pull requests merged in 2023-04, with the labels that each got.

#4116 TASK: Use NodeTypes folder in core packages
  Neos.ContentRepository/NodeTypes/Unstructured.yaml
  Neos.Neos/NodeTypes/Content/ContentCollection.yaml
  Neos.Neos/NodeTypes/Content/FallbackNode.yaml
  Neos.Neos/NodeTypes/Content/PluginView.yaml
  Neos.Neos/NodeTypes/Document/Shortcut.yaml
  Neos.Neos/NodeTypes/Mixin/Content.yaml
  Neos.Neos/NodeTypes/Mixin/Document.yaml
  Neos.Neos/NodeTypes/Mixin/Hidable.yaml
  Neos.Neos/NodeTypes/Mixin/Node.yaml
  Neos.Neos/NodeTypes/Mixin/Plugin.yaml
  Neos.Neos/NodeTypes/Mixin/Timable.yaml
  Neos.NodeTypes.AssetList/NodeTypes/Content/AssetList.yaml
  Neos.NodeTypes.BaseMixins/NodeTypes/Mixin/ContentImage.yaml
  Neos.NodeTypes.BaseMixins/NodeTypes/Mixin/Image.yaml
  Neos.NodeTypes.BaseMixins/NodeTypes/Mixin/ImageAlignment.yaml
  Neos.NodeTypes.BaseMixins/NodeTypes/Mixin/ImageCaption.yaml
  Neos.NodeTypes.BaseMixins/NodeTypes/Mixin/Link.yaml
  Neos.NodeTypes.BaseMixins/NodeTypes/Mixin/Text.yaml
  Neos.NodeTypes.BaseMixins/NodeTypes/Mixin/Title.yaml
  Neos.NodeTypes.ColumnLayouts/NodeTypes/Content/Column.yaml
  Neos.NodeTypes.ColumnLayouts/NodeTypes/Content/FourColumn.yaml
  Neos.NodeTypes.ColumnLayouts/NodeTypes/Content/ThreeColumn.yaml
  Neos.NodeTypes.ColumnLayouts/NodeTypes/Content/TwoColumn.yaml
  Neos.NodeTypes.ContentReferences/NodeTypes/Content/ContentReferences.yaml
  Neos.NodeTypes.Form/NodeTypes/Content/Form.yaml
  Neos.NodeTypes.Html/NodeTypes/Content/Html.yaml
  Neos.NodeTypes.Navigation/NodeTypes/Content/Navigation.yaml
  Neos.NodeTypes/Configuration/NodeTypes.Mixins.yaml
  Neos.NodeTypes/NodeTypes/Content/Headline.yaml
  Neos.NodeTypes/NodeTypes/Content/Image.yaml
  Neos.NodeTypes/NodeTypes/Content/Text.yaml
  Neos.NodeTypes/NodeTypes/Content/TextWithImage.yaml
  Neos.NodeTypes/NodeTypes/Document/Page.yaml
  Neos.NodeTypes/NodeTypes/Mixin/ContentImage.yaml
  Neos.NodeTypes/NodeTypes/Mixin/Image.yaml
  Neos.NodeTypes/NodeTypes/Mixin/ImageAlignment.yaml
  Neos.NodeTypes/NodeTypes/Mixin/ImageCaption.yaml
  Neos.NodeTypes/NodeTypes/Mixin/Link.yaml
  Neos.NodeTypes/NodeTypes/Mixin/Text.yaml
  Neos.NodeTypes/NodeTypes/Mixin/Title.yaml
Labels: P: Neos, 8.3, Task

#4069 TASK: Deprecate PluginView
  Neos.Neos/Classes/Aspects/PluginUriAspect.php
  Neos.Neos/Classes/Domain/Model/PluginViewDefinition.php
  Neos.Neos/Classes/Fusion/PluginViewImplementation.php
  Neos.Neos/Classes/NodeTypePostprocessor/PluginNodeTypePostprocessor.php
  Neos.Neos/Classes/Service/PluginService.php
  Neos.Neos/Resources/Private/Fusion/Prototypes/PluginView.fusion
Labels: 8.3, Task

#4143 ! 9.0 BUGFIX: fix content stream cleanup
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamFinder.monopic
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamFinder.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamProjection.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentStreamCommandController.php
  Neos.ContentRepositoryRegistry/Migrations/Mysql/Version20230318200512.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: 9.0

#4134 BUGFIX: Fix return type for `itemCollection` in `MenuItemsImplementation`
  Neos.Neos/Classes/Fusion/MenuItemsImplementation.php
Labels: Bug, 9.0

#4147 FEATURE: `references` and `backReferences` FlowQuery operations
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/BackReferencesOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/NodesOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PropertyOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ReferencePropertyOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ReferencesOperation.php
Labels: Feature, 9.0

#4165 BUGIFX: Check optional array key if exisits in workspace map
  Neos.ContentRepository.Core/Classes/Projection/Workspace/Workspaces.php
Labels: Bug, 9.0

#4169 BUGFIX: Make functional tests run
  Neos.Neos/Tests/Functional/Service/LinkingServiceTest.php
  Neos.Neos/Tests/Functional/ViewHelpers/Link/NodeViewHelperTest.php
  Neos.Neos/Tests/Functional/ViewHelpers/Uri/NodeViewHelperTest.php
Labels: Bug, 8.3

#4038 FEATURE: Introduce node:migrationcreate command
  Neos.ContentRepository/Classes/Migration/Command/NodeCommandController.php
  Neos.ContentRepository/Classes/Migration/Service/MigrationGeneratorService.php
  Neos.ContentRepository/Resources/Private/Generator/Migrations/ContentRepository/NodeMigrationTemplate.yaml.tmpl
  Neos.Neos/Documentation/References/CommandReference.rst
Labels: Feature, 8.3

#4168 FEATURE: Support `iterables` that do not implement `countable` in `Neos.Fusion:Map`, `Neos.Fusion:Loop` and `Neos.Fusion:Reduce`
  Neos.Fusion/Classes/FusionObjects/MapImplementation.php
  Neos.Fusion/Classes/FusionObjects/ReduceImplementation.php
  Neos.Fusion/Tests/Functional/FusionObjects/LoopTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/MapTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/ReduceTest.php
  Neos.Neos/Documentation/References/NeosFusionReference.rst
Labels: Feature, 8.3

#4088 TASK: Rework asset usage for current state of CR
  Neos.ContentRepository.Export/src/Processors/AssetExportProcessor.php
  Neos.ESCR.AssetUsage/Classes/AssetUsageFinder.php
  Neos.ESCR.AssetUsage/Classes/Command/AssetUsageCommandController.php
  Neos.ESCR.AssetUsage/Classes/Dto/AssetIdsByProperty.php
  Neos.ESCR.AssetUsage/Classes/Dto/AssetUsage.php
  Neos.ESCR.AssetUsage/Classes/Dto/AssetUsageFilter.php
  Neos.ESCR.AssetUsage/Classes/Dto/AssetUsages.php
  Neos.ESCR.AssetUsage/Classes/Package.php
  Neos.ESCR.AssetUsage/Classes/Projector/AssetUsageProjection.php
  Neos.ESCR.AssetUsage/Classes/Projector/AssetUsageProjectorFactory.php
  Neos.ESCR.AssetUsage/Classes/Projector/AssetUsageRepository.php
  Neos.ESCR.AssetUsage/Configuration/Settings.yaml
  Neos.ESCR.AssetUsage/README.md
  Neos.ESCR.AssetUsage/Screenshot.png
  Neos.ESCR.AssetUsage/composer.json
  Neos.Media.Browser/Classes/Controller/UsageController.php
  Neos.Media.Browser/Resources/Private/Templates/Usage/RelatedNodes.html
  Neos.Neos/Classes/AssetUsage/AssetUsageStrategy.php
  Neos.Neos/Classes/AssetUsage/Command/AssetUsageCommandController.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetIdAndOriginalAssetId.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetIdsByProperty.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsage.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsageFilter.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsageReference.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsages.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsagesByContentRepository.php
  Neos.Neos/Classes/AssetUsage/Dto/NodeAddress.php
  Neos.Neos/Classes/AssetUsage/GlobalAssetUsageService.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageFinder.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjection.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjectionFactory.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepository.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepositoryFactory.php
  Neos.Neos/Classes/AssetUsage/README.md
  Neos.Neos/Classes/AssetUsage/Service/AssetUsageSyncService.php
  Neos.Neos/Classes/AssetUsage/Service/AssetUsageSyncServiceFactory.php
  Neos.Neos/Classes/Domain/Model/Dto/AssetUsageInNodeProperties.php
  Neos.Neos/Classes/Package.php
  Neos.Neos/Classes/Service/ImageVariantGarbageCollector.php
  Neos.Neos/Configuration/Objects.yaml
  Neos.Neos/Configuration/Settings.AssetUsage.yaml
  Neos.Neos/Configuration/Settings.ContentRepositoryRegistry.yaml
  Neos.Neos/Configuration/Testing/Settings.AssetUsage.yaml
  Neos.Neos/Migrations/Mysql/Version20220225092238.php
  Neos.Neos/Migrations/Mysql/Version20230303145522.php
  Neos.Neos/Resources/Private/Partials/Module/Shared/NodeContentDimensionsInformation.html
  composer.json
Labels: 9.0

#4084 9.0 FEATURE: Check for empty live workspace before import a new content repository
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceEventStreamName.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner.php
  Neos.ContentRepository.Export/src/ExportService.php
  Neos.ContentRepository.Export/src/ExportServiceFactory.php
  Neos.ContentRepository.Export/src/ImportService.php
  Neos.ContentRepository.Export/src/Processors/EventExportProcessor.php
  Neos.ContentRepository.Export/src/Processors/EventStoreImportProcessor.php
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
Labels: Feature, 9.0

#4166 BUGFIX: Set workspace owner on creation of personal workspace
  Neos.Neos/Classes/Service/EditorContentStreamZookeeper.php
Labels: Bug, 9.0

#4174 FEATURE: Set InitiatingUserId from authenticated Neos user
  Neos.Neos/Classes/UserIdProvider/UserIdProvider.php
  Neos.Neos/Classes/UserIdProvider/UserIdProviderFactory.php
  Neos.Neos/Configuration/Settings.ContentRepositoryRegistry.yaml
Labels: Feature, 9.0

#4182 BUGFIX: Allow installation in Neos < 9.0
  Neos.ContentRepositoryRegistry/composer.json
Labels: Bug, 9.0

#4181 FEATURE: Import and export of content repositories with assets
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamEventStreamName.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceEventStreamName.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner.php
  Neos.ContentRepository.Core/Classes/Service/WorkspaceMaintenanceService.php
  Neos.ContentRepository.Core/Classes/Service/WorkspaceMaintenanceServiceFactory.php
  Neos.ContentRepository.Export/src/Exception/LiveWorkspaceContentStreamExistsException.php
  Neos.ContentRepository.Export/src/ExportService.php
  Neos.ContentRepository.Export/src/ExportServiceFactory.php
  Neos.ContentRepository.Export/src/ImportService.php
  Neos.ContentRepository.Export/src/ImportServiceFactory.php
  Neos.ContentRepository.Export/src/Processors/AssetExportProcessor.php
  Neos.ContentRepository.Export/src/Processors/EventExportProcessor.php
  Neos.ContentRepository.Export/src/Processors/EventStoreImportProcessor.php
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Command/CrCommandController.php
Labels: Feature, 9.0

#4189 BUGFIX: Mark reference changes as changed
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: Bug, 9.0

#4184 BUGFIX: Deserialize node properties when iterating
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/SerializedPropertyValues.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/PropertyCollection.php
  Neos.ContentRepository.Core/Tests/Unit/Projection/ContentGraph/PropertyCollectionTest.php
Labels: Bug, 9.0

#4196 BUGFIX: Fix `DateStringConverter` to also accept `DateTimeImmutable`
  Neos.Neos/Classes/Service/Mapping/DateStringConverter.php
Labels: Bug, 9.0

#4186 FEATURE: Edit, delete and switch workspaces
  Neos.ContentRepository.Core/Classes/EventStore/EventNormalizer.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Command/ChangeBaseWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Command/ChangeWorkspaceOwner.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Command/DeleteWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Command/RenameWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Event/WorkspaceBaseWorkspaceWasChanged.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Event/WorkspaceOwnerWasChanged.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Event/WorkspaceWasRemoved.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Event/WorkspaceWasRenamed.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Exception/BaseWorkspaceEqualsWorkspaceException.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Exception/CircularRelationBetweenWorkspacesException.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Exception/WorkspaceIsNotEmptyException.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/WorkspaceDescription.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentStreamCommandController.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Edit.html
  Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Index.html
Labels: Feature, 9.0

#4197 BUGFIX: Fix usage of value object `ContentStreamId` in `ContentStreamCommandController`
  Neos.ContentRepositoryRegistry/Classes/Command/ContentStreamCommandController.php
Labels: Bug, 9.0

#4155 FEATURE: Assets Eel helper for Neos.Media
  Neos.Media/Classes/Eel/AssetsHelper.php
  Neos.Media/Configuration/Settings.yaml
  Neos.Media/Tests/Functional/Eel/AssetsHelperTest.php
  Neos.Neos/Documentation/References/EelHelpersReference.rst
Labels: P: Media, Feature, 8.3

#4195 FEATURE: add Eel helper to access Site from SiteNode
  Neos.Neos/Classes/Fusion/Helper/SiteHelper.php
  Neos.Neos/Configuration/Settings.yaml
Labels: Feature, 9.0

#4203 TASK: Update readme after renaming of `ContentRepositoryMigrateCommandController`
  Readme.rst
Labels: 9.0, Task

#4202 BUGFIX: Fix type errors for configuration backend module
  Neos.Neos/Classes/ViewHelpers/Backend/ConfigurationTreeViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Backend/TranslateViewHelper.php
Labels: Bug, 9.0

#4091 FEATURE: NodeType configuration command controller
  Neos.ContentRepository/Classes/Command/NodeTypesCommandController.php
  Neos.Neos/Documentation/References/CommandReference.rst
Labels: Feature, 8.3

#4206 FEATURE: Change wallpaper images
  Neos.Neos/Resources/Public/Images/Login/Wallpaper.jpg
  Neos.Neos/Resources/Public/Images/Login/Wallpaper.webp
Labels: Feature, 8.3

#4207 BUGFIX: Adjust version and release variables
  Neos.Neos/Documentation/conf.py
Labels: Bug

#4212 BUGFIX: Add php version declaration to neos/fusion-afx
  Neos.Fusion.Afx/composer.json
Labels: Bug, 8.3

#4220 BUGFIX: make pagination work with Traversable
  Neos.ContentRepository/Classes/ViewHelpers/Widget/Controller/PaginateController.php
Labels: Bug, 7.3

#4224 BUGFIX: Fix missing icon in case of fusion errors
  Neos.Fusion/Classes/Core/ExceptionHandlers/HtmlMessageHandler.php
Labels: Bug, 7.3

#4204 (9.0) FEATURE: some performance optimizations
  Neos.Neos/Classes/Aspects/SiteRepositoryCachingAspect.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathFinder.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
Labels: 9.0

#4235 BUGFIX: Ensure cr:migrateLegacyData runs on first try
  Neos.ContentRepository.Export/src/Processors/EventStoreImportProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Command/CrCommandController.php
Labels: 9.0

#4233 FEATURE: Unify Content Subgraph filters
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/ChildNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/CountBackReferences.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/CountNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/CountReferences.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/DescendantNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindBackReferences.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindChildNodeConnectedThroughEdgeName.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodeById.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodeByPath.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindParentNode.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindPrecedingSiblingNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindReferences.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindSubtree.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/References.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/RetrieveNodePath.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/SiblingNodes.feature
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/NodeMove.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountBackReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountDescendantNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindBackReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindDescendantNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindPrecedingSiblingNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindRootNodeAggregatesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindSubtreeFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindSucceedingSiblingNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/PropertyValueCriteriaParser.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/EventSourcedTrait.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ChildrenOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/FindOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PropertyOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ReferencePropertyOperation.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/Fusion/MenuItemsImplementation.php
  Neos.Neos/Classes/Service/PluginService.php
  Neos.Neos/Classes/Service/View/NodeView.php
Labels: Feature, 9.0

#4234 BUGFIX: Specify default values for the creation timestamp columns
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
Labels: Bug, 9.0

#4222 BUGFIX: clear cache properly when moving nodes
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.monopic
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
Labels: Bug, 9.0

#4216 TASK: Add additional neos 9 steps too flow welcome screen
  Neos.CliSetup/Classes/Command/WelcomeCommandController.php
Labels: 9.0, Task, Neos Setup
