Repository neos/neos-development-collection, pull requests merged in 2023-09, with the labels that each got.

#4364 9.0 FEATURE: Add flowQuery operations `referenceNodes` and `backReferenceNodes`
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/BackReferenceNodesOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/NodesOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ReferenceNodesOperation.php
Labels: Feature, 9.0

#4355 9.0 FEATURE: Add flowQuery operation `unique` and `remove` for Nodes
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/CreateNodeHashTrait.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/RemoveOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/UniqueOperation.php
  Neos.ContentRepository.NodeAccess/Tests/Unit/FlowQueryOperations/RemoveOperationTest.php
  Neos.ContentRepository.NodeAccess/Tests/Unit/FlowQueryOperations/UniqueOperationTest.php
Labels: Feature, 9.0

#4452 FEATURE: Progress bar for projection replay
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUpOptions.php
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
Labels: Feature, 9.0

#4491 BUGFIX: Update exception message to use structureadjustments:fix
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
Labels: Bug, 9.0, 9.0beta1

#4492 BUGFIX: Add type hint to prevent static analysis to fail
  Neos.Neos/Classes/Domain/Model/Site.php
Labels: Bug, 9.0

#4472 TASK: migrate NodeTypesCommandController
  Neos.ContentRepositoryRegistry/Classes/Command/NodeTypesCommandController.php
Labels: 9.0, Task, 9.0beta1

#4459 FEATURE: re-implement nodemigration:migrationcreate command
  Neos.ContentRepositoryRegistry/Classes/Command/NodeMigrationCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Service/NodeMigrationGeneratorService.php
  Neos.ContentRepositoryRegistry/Resources/Private/Generator/Migrations/ContentRepository/NodeMigrationTemplate.yaml.tmpl
  Neos.Neos/Documentation/References/CommandReference.rst
Labels: Feature, 9.0

#4473 TASK #4471 lint distributionintegrity
  composer.json
Labels: 9.0

#4494 TASK: improve codestyle in NodeMigrationCommandController
  Neos.ContentRepositoryRegistry/Classes/Command/NodeMigrationCommandController.php
Labels: 9.0, Task

#4425 !!! FEATURE: Global variables for the Fusion runtime `FusionGlobals`
  Neos.Fusion/Classes/Core/FusionGlobals.php
  Neos.Fusion/Classes/Core/Runtime.php
  Neos.Fusion/Classes/Core/RuntimeFactory.php
  Neos.Fusion/Classes/View/FusionView.php
  Neos.Fusion/Tests/Benchmark/RuntimeBench.php
  Neos.Fusion/Tests/Functional/FusionObjects/ExpressionsTest.php
  Neos.Fusion/Tests/Unit/Core/RuntimeTest.php
  Neos.Neos/Classes/Domain/Repository/SiteRepository.php
  Neos.Neos/Classes/Domain/Service/FusionService.php
  Neos.Neos/Classes/View/FusionExceptionView.php
  Neos.Neos/Classes/View/FusionView.php
  Neos.Neos/Tests/Unit/View/FusionViewTest.php
Labels: 9.0

#4465 TASK: Cleanup & fix workspace cli commands
  Neos.ContentRepositoryRegistry/Classes/Command/WorkspaceCommandController.php
  Neos.Neos/Classes/Command/WorkspaceCommandController.php
Labels: 9.0, Task

#4521 90/edit preview mode support v3 review
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Classes/Domain/Model/RenderingMode.php
  Neos.Neos/Classes/Domain/Service/RenderingModeService.php
  Neos.Neos/Classes/View/FusionExceptionView.php
  Neos.Neos/Classes/View/FusionView.php
  Neos.Neos/Configuration/Settings.yaml
Labels: 90/editPreviewModeSupport_v3

#4505 !!! FEATURE: Reimplement EditPreviewModes for Neos 9
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Classes/Domain/Model/RenderingMode.php
  Neos.Neos/Classes/Domain/Model/UserInterfaceMode.php
  Neos.Neos/Classes/Domain/Service/RenderingModeService.php
  Neos.Neos/Classes/Domain/Service/UserInterfaceModeService.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Classes/View/FusionExceptionView.php
  Neos.Neos/Classes/View/FusionView.php
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/Resources/Private/Fusion/Override/GlobalCacheIdentifiers.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/ContentElementWrapping.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/Editable.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/FallbackNode.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion
  Neos.Neos/Resources/Private/Fusion/RootCase.fusion
Labels: Feature, 9.0, 9.0beta1

#4481 TASK `requireTetheredDescendantNodeTypesToExist` readability
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
Labels: 9.0

#4528 TASK: Rename Afx Parsing `Node` to `AfxNode`
  Neos.Fusion.Afx/Classes/Parser/Expression/AfxNode.php
  Neos.Fusion.Afx/Classes/Parser/Expression/AfxNodeList.php
  Neos.Fusion.Afx/Classes/Parser/Parser.php
Labels: 9.0, Task

#4482 BUGFIX: Fix `NodeType` `getTypeOfAutoCreatedChildNode` and `getPropertyType`
  Neos.ContentRepository/Classes/Domain/Model/NodeType.php
Labels: Bug, 7.3

#4513 TASK: Remove `PropertyCollectionInterface`
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Dto/NodeSubtreeSnapshot.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/PropertyCollection.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/PropertyCollectionInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Reference.php
  Neos.ContentRepository.NodeMigration/src/Filter/PropertyValueFilterFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/ChangePropertyValueTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RenamePropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/StripTagsOnPropertyTransformationFactory.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/PropertyAdjustment.php
  Neos.Neos/Tests/Functional/Fusion/NodeHelperTest.php
Labels: 9.0, Task

#4496 !!! TASK: Cleanup deprecated code in FusionService
  Neos.Neos/Classes/Domain/Service/FusionService.php
Labels: 9.0, 9.0beta1

#4540 TASK: cleanup (Asset usage) node address
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsageNodeAddress.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjection.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepository.php
Labels: 9.0, Task

#4542 TASK: Remove `Neos.Node.inBackend()` and `Neos.Node.isLive()` eel helper
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
Labels: 9.0, Task, 9.0beta1

#4519 FEATURE: Add `ContentSubgraphInterface::findClosestNode()`
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/ClosestNode.feature
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindClosestNodeFilter.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/NodeTraversalTrait.php
Labels: Feature, 9.0

#4546 BUGFIX: Adjust `rawContent` mode condition to use `renderingMode.isEdit`
  Neos.Neos/Resources/Private/Fusion/RootCase.fusion
Labels: Bug, 9.0, 9.0beta1

#4547 BUGFIX: Guard that Fusion path cannot be empty
  Neos.Fusion/Classes/Core/RuntimeConfiguration.php
Labels: Bug, 7.3

#4559 TASK: Review of "Node type fallback handling"
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/NodePrivilegeContext.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DisallowedChildNodeAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/LoadNodeTypeTrait.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/PropertyAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/UnknownNodeTypeAdjustment.php
  Neos.ContentRepositoryRegistry/Classes/Utility/ContentRepositoryRegistryProvider.php
  Neos.Neos/Classes/Controller/Backend/ContentController.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Domain/Service/NodeSiteResolvingService.php
  Neos.Neos/Classes/Domain/Service/SiteNodeUtility.php
  Neos.Neos/Classes/EventLog/Integrations/ContentRepositoryIntegrationService.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Classes/Fusion/Helper/NodeLabelToken.php
  Neos.Neos/Classes/Routing/Cache/RouteCacheFlusher.php
  Neos.Neos/Classes/Utility/NodeTypeWithFallbackProvider.php
  Neos.Neos/Classes/View/FusionView.php
  Neos.Neos/Classes/ViewHelpers/Backend/DocumentBreadcrumbPathViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Link/NodeViewHelper.php
  Neos.Neos/Tests/Functional/Fusion/NodeHelperTest.php
Labels: Task, nodeTypeFallbackHandling

#4548 BUGFIX: Fix Neos.ContentRepository.LegacyNodeMigration behat tests
  .composer.json
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Assets.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Errors.feature
  composer.json
Labels: Bug, 9.0

#4221 Remove old CSS files (Includes-built.css, Neos.css) which are not maintained anymore
  Neos.Media.Browser/Configuration/Settings.yaml
  Neos.Neos/.gitignore
  Neos.Neos/Resources/Public/Styles/Includes-built.css
  Neos.Neos/Resources/Public/Styles/Neos.css
Labels: 7.3

#4543 TASK: remove outdated useless e2e tests
  .composer.json
  .github/workflows/build.yml
  .github/workflows/postgresql-versions.yml
  Neos.ContentRepository.BehavioralTests/DistributionBehatTemplate/composer.json
  Neos.ContentRepository.TestSuite/composer.json
  Neos.Neos/Tests/Behavior/Features/Administration/SiteManagement/ListSites.__feature
  Neos.Neos/Tests/Behavior/Features/BackendLogin.__feature
  Neos.Neos/Tests/Behavior/Features/Bootstrap/BrowserTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FlowQueryTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FlowSubcommandTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/HistoryDefinitionsTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
  Neos.Neos/Tests/Behavior/Features/Content/InlineEditing.__feature
  Neos.Neos/Tests/Behavior/Features/Content/PreviewMode.__feature
  Neos.Neos/Tests/Behavior/Features/Content/PublishUserWorkspace.__feature
  Neos.Neos/Tests/Behavior/Features/EventLog/CotentRepository/AddingNodes.__feature
  Neos.Neos/Tests/Behavior/Features/EventLog/CotentRepository/EditingNodes.__feature
  Neos.Neos/Tests/Behavior/Features/ExportImport.__feature
  Neos.Neos/Tests/Behavior/Features/NeosHistory/Entities/AccountsUsers.feature
  Neos.Neos/Tests/Behavior/Features/Security/NodeTreePrivilege.__feature
  Neos.Neos/Tests/Behavior/behat.yml
  Neos.Neos/Tests/Behavior/behat.yml.dist
  Neos.Neos/Tests/Behavior/saucelabsBrowsers.yml
  Neos.Neos/Tests/Functional/Command/BehatTestHelper.php
  composer.json
Labels: 9.0, Task

#4562 !!! TASK: Remove `NodeType::getName()` and replace usages
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.Neos/Resources/Private/Fusion/Prototypes/Content.fusion
  Neos.Neos/Resources/Private/Fusion/RawContent/Node.fusion
  Neos.Neos/Resources/Private/Fusion/RootCase.fusion
  Neos.NodeTypes.Navigation/Resources/Private/Fusion/Root.fusion
Labels: nodeTypeFallbackHandling

#4534 BUGFIX: Remove Neos `WorkspaceName`
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceFinder.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Domain/Model/WorkspaceName.php
  Neos.Neos/Classes/Domain/Service/WorkspaceNameBuilder.php
  Neos.Neos/Classes/Service/EditorContentStreamZookeeper.php
  Neos.Neos/Classes/Utility/User.php
Labels: Bug, 9.0

#4530 TASK: Deprecate legacy User Utility
  Neos.Neos/Classes/Utility/User.php
Labels: 9.0, Task

#4565 TASK: Add configuration files for RTD
  .readthedocs.yaml
  Neos.Media/Documentation/.readthedocs.yaml
Labels: Task, 7.3

#4568 TASK: Fix paths for Neos.Media RTD rendering setup
  Neos.Media/Documentation/.readthedocs.yaml
Labels: Task, 7.3

#4556 TASK: NodeType::isOfType allow NodeTypeName as $nodeTypeName
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
Labels: 9.0, 9.0beta1

#4544 TASK: Remove `Neos.ContentRepository.Security`
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/BehatTestHelper.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/AbstractNodePrivilege.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/AbstractNodePropertyPrivilege.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/CreateNodePrivilege.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/CreateNodePrivilegeContext.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/CreateNodePrivilegeSubject.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/EditNodePrivilege.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/EditNodePropertyPrivilege.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/NodePrivilegeContext.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/NodePrivilegeSubject.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/PropertyAwareNodePrivilegeContext.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/PropertyAwareNodePrivilegeSubject.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/ReadNodePrivilege.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/ReadNodePropertyPrivilege.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/RemoveNodePrivilege.php
  Neos.ContentRepository.Security/Classes/Service/AuthorizationService.php
  Neos.ContentRepository.Security/Tests/Behavior/Features/Bootstrap/NodeAuthorizationTrait.php
  Neos.ContentRepository.Security/composer.json
  Neos.Neos/Classes/Controller/Backend/MenuHelper.php
  Neos.Neos/Classes/Security/Authorization/Privilege/NodeTreePrivilege.php
  Neos.Neos/Classes/Service/ContentElementEditableService.php
  Neos.Neos/Classes/Service/ContentElementWrappingService.php
  Neos.Neos/Tests/Unit/Service/ContentElementEditableServiceTest.php
  Neos.Neos/Tests/Unit/ViewHelpers/ContentElement/EditableViewHelperTest.php
  composer.json
  phpstan.neon
Labels: 9.0, Task, 9.0beta1

#4569 BUGFIX: FusionExceptionView must use mocked controller context
  Neos.Neos/Classes/View/FusionExceptionView.php
Labels: Bug, 9.0, 9.0beta1

#4466 !!! FEATURE: `NodeTypeManager` remove NodeType fallback handling
  .composer.json
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.BehavioralTests/Classes/TestSuite/Behavior/CRBehavioralTestsSubjectProvider.php
  Neos.ContentRepository.BehavioralTests/Classes/TestSuite/Behavior/GherkinPyStringNodeBasedNodeTypeManagerFactory.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/NodeTypeAdjustment_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/NodeTypeAdjustment_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/UnknownNodeType.feature
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeManager.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeManagerTest.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DisallowedChildNodeAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/LoadNodeTypeTrait.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/PropertyAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/UnknownNodeTypeAdjustment.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/NodeTypesCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Factory/NodeTypeManager/DefaultNodeTypeManagerFactory.php
  Neos.ContentRepositoryRegistry/Configuration/Settings.yaml
  Neos.Neos/Classes/Controller/Backend/ContentController.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/Domain/Service/NodeSiteResolvingService.php
  Neos.Neos/Classes/Domain/Service/NodeTypeNameFactory.php
  Neos.Neos/Classes/Domain/Service/SiteNodeUtility.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.Neos/Classes/EventLog/Integrations/ContentRepositoryIntegrationService.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Classes/Fusion/Helper/NodeLabelToken.php
  Neos.Neos/Classes/Fusion/MenuItemsImplementation.php
  Neos.Neos/Classes/Fusion/PluginImplementation.php
  Neos.Neos/Classes/NodeTypePostprocessor/DefaultPropertyEditorPostprocessor.php
  Neos.Neos/Classes/Routing/Cache/RouteCacheFlusher.php
  Neos.Neos/Classes/Service/Mapping/NodeTypeStringConverter.php
  Neos.Neos/Classes/Service/NodeTypeSchemaBuilder.php
  Neos.Neos/Classes/Utility/NodeTypeWithFallbackProvider.php
  Neos.Neos/Classes/View/FusionView.php
  Neos.Neos/Classes/ViewHelpers/Backend/DocumentBreadcrumbPathViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Link/NodeViewHelper.php
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/NodeTypes/FallbackNode.yaml
  Neos.Neos/NodeTypes/Root/Sites.yaml
  Neos.Neos/Resources/Private/Fusion/Prototypes/Content.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCase.fusion
  Neos.Neos/Resources/Private/Fusion/RawContent/Node.fusion
  Neos.Neos/Resources/Private/Fusion/RootCase.fusion
  Neos.Neos/Resources/Private/Templates/Service/Nodes/Index.html
  Neos.Neos/Resources/Private/Templates/Service/Nodes/Show.html
  Neos.Neos/Tests/Functional/Fusion/NodeHelperTest.php
  Neos.Neos/Tests/Functional/Service/NodeTypeSchemaBuilderTest.php
  Neos.Neos/Tests/Unit/NodeTypePostprocessor/DefaultPropertyEditorPostprocessorTest.php
  Neos.NodeTypes.Navigation/Resources/Private/Fusion/Root.fusion
  composer.json
Labels: 9.0, 9.0beta1
