Repository neos/neos-development-collection, pull requests merged in 2023-07, with the labels that each got.

#4277 BUGFIX: Disable publish checkmark for new pages in workspace
  Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html
  Neos.Neos/Resources/Private/Translations/en/Main.xlf
Labels: Bug, 7.3

#4309 FEATURE: Introduce catchup hook for DocumentUriPath projection
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentNodeInfos.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathFinder.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjectionFactory.php
  Neos.Neos/Classes/Package.php
Labels: Feature, 9.0

#4339 !!! 9.0: Serious root nodes
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/Query/HypergraphQuery.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/01-RootNodeCreation/01-CreateRootNodeAggregateWithNode_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/01-RootNodeCreation/02-CreateRootNodeAggregateWithNode_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/01-RootNodeCreation/03-CreateRootNodeAggregateWithNode_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodeByPath.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindRootNodeByType.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/RetrieveNodePath.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Dto/NodeAggregateIdsByNodePaths.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/RootNodeHandling.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/AbsoluteNodePath.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache/NodePathCache.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodePath.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/AbsoluteNodePathIsInvalid.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/RootNodeAggregateDoesNotExist.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/RootNodeAggregateTypeIsAlreadyOccupied.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/EventSourcedTrait.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/ProjectedNodeTrait.php
  Neos.ContentRepository.Core/Tests/Unit/Projection/ContentGraph/AbsoluteNodePathTest.php
  Neos.ContentRepository.Core/Tests/Unit/Projection/ContentGraph/NodePathTest.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Helpers/VisitedNodeAggregates.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/FindOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PropertyOperation.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/NodePrivilegeContext.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Classes/Presentation/VisualNodePath.php
  Neos.Neos/Classes/Service/View/NodeView.php
  Neos.Neos/Documentation/References/PropertyEditorReference.rst
Labels: 9.0

#4384 Bugfix: `migratelegacydata` warn if no valid content dimension configuration
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
Labels: Bug, 9.0

#4391 BUGFIX: Provide replacement/insertion as array
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/NodeAggregateIds.php
Labels: Bug, 9.0

#4390 BUGFIX: Use $nodeAggregateId->value redirect params in NodesController
  Neos.Neos/Classes/Controller/Service/NodesController.php
Labels: Bug, 9.0

#4400 BUGFIX: Consistently use correct cr identifier across delegated cr:* commands
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Command/CrCommandController.php
Labels: Bug, 9.0

#4399 BUGFIX: Disable content element wrapping and inline editable for references in content reference list
  Neos.NodeTypes.ContentReferences/Resources/Private/Fusion/Root.fusion
Labels: Bug, 7.3

#4403 BUGFIX: Ignore ORM exceptions in AssetUsageProjection
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjection.php
Labels: Bug, 9.0

#4326 FEATURE: PropertyType handle typed arrays `type: array<string>`
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/PropertyType.php
  Neos.ContentRepository.Core/Tests/Unit/Infrastructure/Property/PropertyTypeTest.php
Labels: Feature, 9.0, Task, task/revertWipNullablePropertyTypes

#4406 TASK: remove asset usage migrations, as they fail under MySQL
  Neos.Neos/Migrations/Mysql/Version20220225092238.php
  Neos.Neos/Migrations/Mysql/Version20230303145522.php
Labels: 9.0, Task

#4409 TASK: Avoid potential deprecation warnings
  Neos.Fusion/Classes/Service/HtmlAugmenter.php
  Neos.Neos/Classes/Service/LinkingService.php
Labels: Task, 7.3

#4407 9.0: try to debug pipeline errors
  .github/workflows/build.yml
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
Labels: Bug, 9.0

#4411 BUGFIX: Make ChangeProjection independent from WorkspaceFinder
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjectionFactory.php
Labels: Bug, 9.0

#4419 BUGFIX: Fix editing of Electronic Address type in Backend module
  Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
  Neos.Neos/Resources/Private/Partials/Module/Shared/EditUser.html
  Neos.Neos/Resources/Private/Partials/Module/Shared/NewElectronicAddress.html
Labels: Bug, 7.3

#4417 FEATURE: Tweak and fix `content:*` CLI commands
  Neos.ContentRepositoryRegistry/Classes/Command/ContentCommandController.php
Labels: Feature, 9.0

#4395 BUGFIX: (Neos.Neos) Restore `show` action of `ContentDimensionsController`
  Neos.Neos/Classes/Controller/Service/ContentDimensionsController.php
  Neos.Neos/Configuration/Routes.Service.yaml
Labels: Bug, 9.0

#4310 FEATURE: Expose id from ContentRepository
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.ContentRepository.BehavioralTests/Classes/Command/PerformanceMeasurementCommandController.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositoryFactory.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/MigrationsTrait.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/StructureAdjustmentsTrait.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Command/CrCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentStreamCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/MigrateEventsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/NodeMigrationCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/StructureAdjustmentsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/WorkspaceCommandController.php
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
  Neos.ContentRepositoryRegistry/Classes/Exception/ContentRepositoryIdNotFoundException.php
  Neos.Neos/Classes/AssetUsage/Command/AssetUsageCommandController.php
  Neos.Neos/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Controller/Module/Administration/DimensionController.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Controller/Service/ContentDimensionsController.php
  Neos.Neos/Classes/Domain/Service/SiteService.php
  Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php
  Neos.Neos/Classes/View/FusionExceptionView.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
Labels: Bug, Feature, 9.0, Task
