Repository neos/neos-development-collection, pull requests merged in 2023-03, with the labels that each got.

#4074 FEATURE: Add api eel helpers as replacement for `node.context.inBackend` and `node.context.isLive`
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/Editable.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/FallbackNode.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion
  Neos.Neos/Resources/Private/Fusion/RootCase.fusion
Labels: Feature, 9.0

#4068 FEATURE: Add inspector group `default` to `Neos.Neos:Node`
  Neos.Neos/Configuration/NodeTypes.Node.yaml
  Neos.Neos/Resources/Private/Translations/en/NodeTypes/Node.xlf
Labels: Feature, Neos.Ui, 8.3

#3943 FEATURE: `Neos.Fusion:Component` `@private` props
  Neos.Fusion/Classes/Core/ObjectTreeParser/MergedArrayTreeVisitor.php
  Neos.Fusion/Classes/FusionObjects/ComponentImplementation.php
  Neos.Fusion/Classes/FusionObjects/Helpers/CircularReferenceException.php
  Neos.Fusion/Classes/FusionObjects/Helpers/LazyReference.php
  Neos.Fusion/Classes/FusionObjects/Helpers/LazySelfReferentialProps.php
  Neos.Fusion/Resources/Private/Fusion/Prototypes/Component.fusion
  Neos.Fusion/Tests/Functional/FusionObjects/ComponentTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Component.fusion
  Neos.Fusion/Tests/Unit/Core/Parser/ParserExceptionTest.php
  Neos.Neos/Documentation/References/NeosFusionReference.rst
Labels: Feature, 8.3

#4071 TASK: Remove obsolete tables from new content repository
  Neos.ContentRepositoryRegistry/Migrations/Mysql/Version20230307093648.php
  Neos.Neos/Migrations/Mysql/Version20230307111325.php
Labels: 9.0

#4079 BUGFIX: Fix linting errors and ignore max line length
  .composer.json
  Neos.ContentRepository.Core/Classes/DimensionSpace/ContentDimensionZookeeper.php
  Neos.ContentRepository.Security/Classes/Authorization/Privilege/Node/CreateNodePrivilegeContext.php
  Neos.Neos/Classes/Controller/BackendUserTranslationTrait.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  composer.json
Labels: Bug, 9.0

#4076 FEATURE: Stabilize Content Subgraph API
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/InMemoryCache/AllChildNodesByNodeIdCache.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/SqlQueryBuilder.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/Query/CommonGraphQueryOperations.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/Query/HypergraphParentQuery.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/Query/QueryUtility.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/CountNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindChildNodeConnectedThroughEdgeName.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindChildNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindDescendants.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodeById.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodeByPath.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodePath.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindParentNode.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindPrecedingSiblings.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindReferencedNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindReferencingNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindSubtrees.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindSucceedingSiblings.feature
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache/AllChildNodesByNodeIdCache.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache/NamedChildNodeByNodeIdCache.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache/NodeByNodeAggregateIdCache.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache/NodePathCache.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache/ParentNodeIdByChildNodeIdCache.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindDescendantsFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindPrecedingSiblingsFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindReferencedNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindReferencingNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindSubtreesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindSucceedingSiblingsFilter.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/EventSourcedTrait.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
Labels: Feature, 9.0

#4085 FEATURE: Add `Neos.Dimension` helper
  Neos.Neos/Classes/Fusion/Helper/DimensionHelper.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion
Labels: Feature, 9.0

#4066 9.0: BUGFIX: Fix default dimension resolving
  Neos.ContentRepository.LegacyNodeMigration/Classes/Command/ContentRepositoryMigrateCommandController.php
  Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
  Neos.Neos/Classes/Domain/Model/Site.php
  Neos.Neos/Classes/Domain/Model/SiteConfiguration.php
  Neos.Neos/Classes/Domain/Service/SiteService.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/DelegatingResolver.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/DimensionResolverFactoryInterface.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/DimensionResolverInterface.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/AutoUriPathResolverFactory.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/AutoUriPathResolverFactoryInternals.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/AutoUriPathResolverFactoryInternalsFactory.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/CompositeResolver.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/NoopResolver.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/NoopResolverFactory.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/UriPathResolver.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/UriPathResolverFactory.php
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
  Neos.Neos/Classes/FrontendRouting/SiteDetection/SiteDetectionMiddleware.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/DimensionResolution/NoopResolver.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/DimensionResolution/UriPathResolver.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Dimensions.feature
Labels: 9.0

#4095 TASK: consistently use public readonly properties in value objects, instead of getters
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/PropertyValuesToWrite.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/SerializedPropertyValue.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/SerializedPropertyValues.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/PropertyConverter.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/PropertyType.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeManager.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeName.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeNames.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache/AllChildNodesByNodeIdCache.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache/NodePathCache.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeTypeConstraintsWithSubNodeTypes.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceRuntimeCache.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeAggregateId.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/ContentStreamId.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/EventSourcedTrait.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Helper/TestingNodeAggregateId.php
  Neos.ContentRepository.Export/src/Processors/EventStoreImportProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Helpers/VisitedNodeAggregates.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToAssetsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.NodeMigration/src/Filter/NodeTypeFilterFactory.php
  Neos.ContentRepository.NodeMigration/src/Filter/PropertyValueFilterFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/ChangePropertyValueTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/StripTagsOnPropertyTransformationFactory.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/Domain/Model/NodeCacheEntryIdentifier.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
Labels: 9.0, Task

#4109 Apply fixes from StyleCI
  Neos.Fusion.Afx/Classes/Dsl/AfxDslImplementation.php
  Neos.Fusion.Afx/Tests/Functional/AfxServiceTest.php
  Neos.Fusion.Afx/Tests/Functional/ParserTest.php
  Neos.Fusion/Classes/Core/Cache/ParserCacheIdentifierTrait.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Exception/ParserException.php
  Neos.Fusion/Classes/Core/RuntimeConfiguration.php
  Neos.Fusion/Classes/FusionObjects/AugmenterImplementation.php
  Neos.Fusion/Classes/FusionObjects/Helpers/LazyProps.php
  Neos.Fusion/Classes/FusionObjects/JoinImplementation.php
  Neos.Fusion/Classes/FusionObjects/LoopImplementation.php
  Neos.Fusion/Classes/FusionObjects/RendererImplementation.php
  Neos.Fusion/Classes/ViewHelpers/FusionContextTrait.php
  Neos.Fusion/Tests/Benchmark/RuntimeBench.php
  Neos.Fusion/Tests/Functional/FusionObjects/DebugConsoleTest.php
  Neos.Fusion/Tests/Functional/Parser/FusionParserTest.php
  Neos.Fusion/Tests/Unit/Core/Cache/ContentCacheTest.php
  Neos.Fusion/Tests/Unit/Core/RuntimeConfigurationTest.php
  Neos.Media/Classes/Domain/Model/Adjustment/ResizeImageAdjustment.php
  Neos.Media/Classes/Domain/Model/Dto/UsageReference.php
  Neos.Media/Classes/Domain/Strategy/AbstractAssetUsageStrategy.php
  Neos.Media/Classes/Imagine/Box.php
  Neos.Media/Tests/Functional/Domain/Repository/ImportedAssetRepositoryTest.php
  Neos.Media/Tests/Unit/Domain/Model/Dto/AssetConstraintsTest.php
  Neos.Media/Tests/Unit/Domain/Service/AssetServiceTest.php
  Neos.Media/Tests/Unit/Domain/ValueObject/Configuration/AspectRatioTest.php
  Neos.SiteKickstarter/Tests/Unit/Service/SimpleTemplateRendererTest.php
Labels: 9.0

#4120 9.0: BUGFIX: fix selecting node(s) in `ReferenceEditor` / `ReferencesEditor`
  Neos.Neos/Resources/Private/Templates/Service/Nodes/Index.html
  Neos.Neos/Resources/Private/Templates/Service/Nodes/Show.html
Labels: Bug, 9.0

#4093 9.0 FEATURE: Migrate content dimensions in a running installation
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/RootNodeAggregateDimensionUpdates/UpdateRootNodeAggregateDimensions_WithDimensions.feature
  Neos.ContentRepository.Core/Classes/EventStore/EventNormalizer.php
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeAggregateEventPublisher.php
  Neos.ContentRepository.Core/Classes/Feature/NodeAggregateCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/NodeVariation.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Command/UpdateRootNodeAggregateDimensions.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Event/RootNodeAggregateDimensionsWereUpdated.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/RootNodeHandling.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindRootNodeAggregatesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeAggregates.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/NodeAggregateIsNotRoot.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/Features/NodeCreation.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentCommandController.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Dimensions.feature
Labels: 9.0

#4107 9.0 BUGFIX: Update site properties independent of node name
  Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
Labels: Bug, 9.0

#4129 TASK: refactor API for findNodeAggregates
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeAggregates.php
Labels: 9.0, Task

#4128 TASK: Remove unused `ReadModelInstantiationTrait`
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/ReadModelInstantiationTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
Labels: 9.0, Task

#4083 FEATURE: Allow non eel labels in nodetypes
  Neos.ContentRepository/Classes/Domain/Model/ExpressionBasedNodeLabelGenerator.php
  Neos.ContentRepository/Configuration/Testing/NodeTypes.yaml
  Neos.ContentRepository/Tests/Functional/Domain/NodesTest.php
  Neos.ContentRepository/Tests/Unit/Domain/Model/NodeDataTest.php
Labels: Feature, 8.3

#4142 FEATURE: ContentSubgraph node property value filter
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/CountChildNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/CountDescendantNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindChildNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindDescendantNodes.feature
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountDescendantNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindDescendantNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/AndCriteria.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/NegateCriteria.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/OrCriteria.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/PropertyValueContains.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/PropertyValueCriteriaInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/PropertyValueEndsWith.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/PropertyValueEquals.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/PropertyValueGreaterThan.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/PropertyValueGreaterThanOrEqual.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/PropertyValueLessThan.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/PropertyValueLessThanOrEqual.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/Criteria/PropertyValueStartsWith.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/CriteriaParser/ParserException.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/CriteriaParser/Token.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/CriteriaParser/TokenType.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/PropertyValue/PropertyValueCriteriaParser.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/Features/NodeCreation.php
  Neos.ContentRepository.Core/Tests/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.ContentRepository.Core/Tests/Unit/Projection/ContentGraph/Filter/NodePropertyValue/PropertyValueCriteriaParserTest.php
  Neos.Neos/Classes/Package.php
Labels: Feature, 9.0

#4110 TASK: Speed up CI build
  .github/workflows/build.yml
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Basic.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Dimensions.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/DisableNodes.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/MultiSiteLinking.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Shortcuts.feature
Labels: 9.0, Task

#4146 BUGFIX: Add `ChangeNodeAggregateName` constraint checks
  Neos.ContentRepository.Core/Classes/Feature/NodeAggregateCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRenaming/NodeRenaming.php
Labels: Bug, 9.0

#3279 FEATURE: add dimensions hash to node event model
  Neos.Neos/Classes/EventLog/Domain/Model/Event.php
  Neos.Neos/Classes/EventLog/Domain/Model/NodeEvent.php
  Neos.Neos/Migrations/Mysql/Version20210125134503.php
Labels: P: Neos, Feature, 8.3
