Repository neos/neos-development-collection, pull requests merged in 2024-12, with the labels that each got.

#5370 BUGFIX: Throw `PartialWorkspaceRebaseFailed` if workspace was up to date and publish didnt work
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W10-IndividualNodeDiscarding/01-ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/01-ConstraintChecks.feature
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Exception/PartialWorkspaceRebaseFailed.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Exception/WorkspaceRebaseFailed.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
Labels: Bug, 9.0

#4574 BUGFIX: Throw error if Succeeding Sibiling could not be loaded
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php
Labels: Bug, 9.0

#5384 FEATURE: Cleanup change projection after publish and discard
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/01-DiscardWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/03-DiscardIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/04-DiscardIndividualNodesFromWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/Bootstrap/ChangeProjectionTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/PendingChanges/01-NodeCreation/01-CreateNodeAggregateWithNode_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/01-NodeCreation/02-CreateNodeAggregateWithNode_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/02-NodeVariation/01-CreateNodeGeneralizationVariant.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/02-NodeVariation/02-CreateNodeSpecializationVariant.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/02-NodeVariation/03-CreateNodeSpecializationVariant_InternalWorkspace.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/02-NodeVariation/04-CreateNodePeerVariant.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/03-NodeModification/01-SetNodeProperties_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/03-NodeModification/02-SetNodeProperties_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/04-NodeReferencing/01-SetNodeReferences_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/04-NodeReferencing/02-SetNodeReferences_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/05-NodeDisabling/01-DisableNode_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/05-NodeDisabling/02-DisableNodes_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/06-NodeRemoval/01-RemoveNodeAggregate_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/06-NodeRemoval/02-RemoveNodeAggregate_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/07-NodeMove/01-MoveNodeAggregate_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/07-NodeMove/02-MoveNodeAggregate_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/08-NodeRenaming/01-ChangeNodeAggregateName_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/08-NodeRenaming/02-ChangeNodeAggregateName_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/09-NodeTypeChange/01-ChangeNodeAggregateType_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/09-NodeTypeChange/02-ChangeNodeAggregateType_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/10-DimensionSpaceAdjustment/01-MoveDimensionSpacePoints.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W01-WorkspacePublication/01-PublishWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W01-WorkspacePublication/02-PublishWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W01-WorkspacePublication/03-PublishIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W01-WorkspacePublication/04-PublishIndividualNodesFromWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W02-WorkspaceDiscarding/01-DiscardWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W02-WorkspaceDiscarding/02-DiscardWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W02-WorkspaceDiscarding/03-DiscardIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W02-WorkspaceDiscarding/04-DiscardIndividualNodesFromWorkspace_WithDimensions.feature
Labels: Feature, 9.0

#5397 BUGFIX: Fix Workspace Metadata upsert
  Neos.Neos/Classes/Domain/Repository/WorkspaceMetadataAndRoleRepository.php
  Neos.Neos/Tests/Behavior/Features/ContentRepository/WorkspaceService.feature
Labels: Bug, 9.0

#5392 TASK: Overhaul CatchUpHook error behaviour; At least once delivery for ERROR projections
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/HypergraphProjection.php
  Neos.ContentRepository.BehavioralTests/Classes/ProjectionRaceConditionTester/RaceTrackerCatchUpHook.php
  Neos.ContentRepository.BehavioralTests/Classes/TestSuite/DebugEventProjection.php
  Neos.ContentRepository.BehavioralTests/Classes/TestSuite/DebugEventProjectionState.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/AbstractSubscriptionEngineTestCase.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/CatchUpHookErrorTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/CatchUpHookTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/CatchUpHookWithPersistenceTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/ExternalProjectionErrorTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/ProjectionErrorTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/SubscriptionBatchingTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/SubscriptionSetupTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/ParallelWritingInWorkspaces/ParallelWritingInWorkspacesTest.php
  Neos.ContentRepository.Core/Classes/CommandHandler/Commands.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamHandling.php
  Neos.ContentRepository.Core/Classes/Infrastructure/ProjectionTransactionTrait.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUpHook/CatchUpHookFailed.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUpHook/CatchUpHookInterface.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUpHook/DelegatingCatchUpHook.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionInterface.php
  Neos.ContentRepository.Core/Classes/Service/ContentRepositoryMaintainer.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/Error.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/ProcessedResult.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/SubscriptionEngine.php
  Neos.ContentRepository.Core/Classes/Subscription/Exception/CatchUpFailed.php
  Neos.ContentRepository.Core/Classes/Subscription/Exception/CatchUpHadErrors.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscriber/ProjectionSubscriber.php
  Neos.ContentRepositoryRegistry/Classes/Factory/SubscriptionStore/DoctrineSubscriptionStore.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/FlushSubgraphCachePoolCatchUpHook.php
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHook.php
  Neos.Neos/Classes/FrontendRouting/CatchUpHook/RouterCacheHook.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: Task, feature/4746-rework-catchup-mechanism-3

#5385 BUGFIX: Simplify PartialPublish & Discard (for now) to NOT select dimensions and have custom events
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W10-IndividualNodeDiscarding/01-ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W10-IndividualNodeDiscarding/02-BasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W7-WorkspacePublication/02-PublishWorkspace.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/01-ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/02-BasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/03-MoreBasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/04-AllFeaturePublication.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/05-PublishMovedNodesWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W9-WorkspaceDiscarding/02-DiscardWorkspace.feature
  Neos.ContentRepository.Core/Classes/EventStore/EventInterface.php
  Neos.ContentRepository.Core/Classes/EventStore/EventNormalizer.php
  Neos.ContentRepository.Core/Classes/Feature/Common/MatchableWithNodeIdToPublishOrDiscardInterface.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNodeAndSerializedProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/DisableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/EnableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Event/NodeAggregateWasDisabled.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Event/NodeAggregateWasEnabled.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Command/CopyNodesRecursively.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Command/SetSerializedNodeProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Command/MoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetSerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/Command/RemoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRenaming/Command/ChangeNodeAggregateName.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/Command/ChangeNodeAggregateType.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/Command/CreateNodeVariant.php
  Neos.ContentRepository.Core/Classes/Feature/RebaseableCommands.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Command/TagSubtree.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Command/UntagSubtree.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Command/DiscardIndividualNodesFromWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Command/PublishIndividualNodesFromWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Dto/NodeIdToPublishOrDiscard.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Dto/NodeIdsToPublishOrDiscard.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Event/WorkspaceWasDiscarded.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Event/WorkspaceWasPartiallyDiscarded.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Event/WorkspaceWasPartiallyPublished.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Event/WorkspaceWasPublished.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeAggregateIds.php
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHook.php
  Neos.Neos/Classes/Domain/Service/WorkspacePublishingService.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W01-WorkspacePublication/03-PublishIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W01-WorkspacePublication/04-PublishIndividualNodesFromWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/03-DiscardIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/04-DiscardIndividualNodesFromWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/Bootstrap/AssetUsageTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/ChangeProjectionTrait.php
  Neos.Neos/Tests/Behavior/Features/ContentCache/NodesInUserWorkspace.feature
  Neos.Neos/Tests/Behavior/Features/ContentRepository/Security/WorkspacePermissions.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/PartialPublish.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W01-WorkspacePublication/03-PublishIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W01-WorkspacePublication/04-PublishIndividualNodesFromWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W02-WorkspaceDiscarding/03-DiscardIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/W02-WorkspaceDiscarding/04-DiscardIndividualNodesFromWorkspace_WithDimensions.feature
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
Labels: Bug, 9.0

#5393 BUGFIX: Mark all affected dimension space points as changed on node move
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  Neos.Neos/Tests/Behavior/Features/PendingChanges/07-NodeMove/02-MoveNodeAggregate_WithDimensions.feature
Labels: Bug, 9.0

#5334 BUGFIX: `WorkspaceService` adjust to real world use cases
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/WorkspaceDoesNotExist.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
  Neos.Neos/Classes/Command/WorkspaceCommandController.php
  Neos.Neos/Classes/Domain/Import/LiveWorkspaceCreationProcessor.php
  Neos.Neos/Classes/Domain/Model/WorkspaceRoleAssignment.php
  Neos.Neos/Classes/Domain/Model/WorkspaceRoleAssignments.php
  Neos.Neos/Classes/Domain/Repository/WorkspaceMetadataAndRoleRepository.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.Neos/Classes/Domain/Service/WorkspaceService.php
  Neos.Neos/Classes/Security/Authorization/ContentRepositoryAuthorizationService.php
  Neos.Neos/Classes/Security/ContentRepositoryAuthProvider/ContentRepositoryAuthProvider.php
  Neos.Neos/Configuration/Policy.yaml
  Neos.Neos/Migrations/Mysql/Version20240425223900.php
  Neos.Neos/Migrations/Mysql/Version20241212000000.php
  Neos.Neos/Migrations/Postgresql/Version20240425223901.php
  Neos.Neos/Migrations/Postgresql/Version20241212000001.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FlowSecurityTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/UserServiceTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/WorkspaceServiceTrait.php
  Neos.Neos/Tests/Behavior/Features/ContentRepository/Security/EditNodePrivilege.feature
  Neos.Neos/Tests/Behavior/Features/ContentRepository/Security/ReadNodePrivilege.feature
  Neos.Neos/Tests/Behavior/Features/ContentRepository/Security/WorkspacePermissions.feature
  Neos.Neos/Tests/Behavior/Features/ContentRepository/WorkspaceService.feature
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
Labels: Bug, 9.0

#5401 BUGFIX: Add missing dependency for neos/contentrepository-nodemigration
  Neos.ContentRepositoryRegistry/composer.json
Labels: Bug, 9.0

#5394 BUGFIX: Avoid that `doctrine:migrationgenerate` drops pure dbal tables
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/Tests/Behavior/Features/Bootstrap/AssetUsageTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/WorkspaceServiceTrait.php
Labels: Bug, 9.0

#5398 TASK: Core and neos schemas for pgsql and mysql
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
  Neos.ContentRepository.BehavioralTests/Classes/TestSuite/DebugEventProjection.php
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalSchemaFactory.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathSchemaBuilder.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: 9.0, Task

#5404 BUGFIX: Allow width and height to be empty on export
  Neos.ContentRepository.Export/src/Asset/ValueObject/SerializedImageVariant.php
Labels: Bug, 9.0

#5409 !!! FEATURE: Drop twitter bootstrap dependency
  Neos.Media.Browser/Configuration/Settings.yaml
  Neos.Media.Browser/Resources/Public/Libraries/bootstrap/bootstrap.min.js
  Neos.Media.Browser/composer.json
  composer.json
Labels: P: Media Browser, 9.0

#5416 BUGFIX: Fix typo in member variable
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Labels: Bug, 9.0
