Repository neos/neos-development-collection, pull requests merged in 2024-09, with the labels that each got.

#5233 TASK: Streamline workspacename fields
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalSchemaFactory.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathSchemaBuilder.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: 9.0, Task

#5237 TASK: Update GitHub actions
  .github/workflows/add-pr-labels.yml
  .github/workflows/build.yml
  .github/workflows/doctum.yml
  .github/workflows/postgresql-versions.yml
Labels: 8.3, Task

#5235 TASK: Rename parent nodes to ancestor nodes and improve ancestor determination
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.Neos/Classes/Fusion/Cache/AssetChangeHandlerForCacheFlushing.php
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
  Neos.Neos/Classes/Fusion/Cache/FlushNodeAggregateRequest.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
Labels: 9.0, Task

#5207 BUGFIX: Remove rootnode when user workspace is deleted
  Neos.Neos/Classes/Domain/Service/UserService.php
Labels: Bug, 8.3, P: User Management

#5238 TASK: Update GitHub actions
  .github/workflows/build.yml
Labels: 9.0, Task

#5232 BUGFIX: Fix autoselection of ancestor nodes in Workspace module
  Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html
Labels: Bug, 8.3

#5241 TASK: Make single-field Value Objects stringable
  Neos.ContentRepository.BehavioralTests/Classes/PhpstanRules/NoStringCastingRule.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Dto/SubtreeTag.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeName.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/AbsoluteNodePath.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/Ordering/OrderingFieldName.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodePath.php
  Neos.ContentRepository.Core/Classes/SharedModel/ContentRepository/ContentRepositoryId.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeAggregateId.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeName.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/PropertyName.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/ReferenceName.php
  Neos.ContentRepository.Core/Classes/SharedModel/User/UserId.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/ContentStreamId.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/WorkspaceDescription.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/WorkspaceName.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/WorkspaceTitle.php
  Neos.Neos/Classes/FrontendRouting/DimensionResolution/Resolver/UriPathResolver/Separator.php
  phpstan.neon.dist
Labels: 9.0, Task

#5242 BUGFIX: Mark projection as stale after applying an event.
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteRuntimeVariables.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeTrait.php
Labels: Bug, 9.0

#5244 extract content subgraph inmemory caching
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/InMemoryCache.php
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/FlushSubgraphCachePoolCatchUpHook.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/FlushSubgraphCachePoolCatchUpHookFactory.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/InMemoryCache/AllChildNodesByNodeIdCache.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/InMemoryCache/NamedChildNodeByNodeIdCache.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/InMemoryCache/NodeByNodeAggregateIdCache.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/InMemoryCache/NodePathCache.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/InMemoryCache/ParentNodeIdByChildNodeIdCache.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/SubgraphCachePool.php
  Neos.ContentRepositoryRegistry/Configuration/Settings.yaml
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  phpstan-baseline.neon
Labels: 9.0

#5225 TASK: remove ui script tag neos 9 followup
  Neos.Neos/Classes/Service/ContentElementWrappingService.php
Labels: 9.0, Task

#5226 TASK: Split up EmbedsContentStreamAndNodeAggregateId interface
  Neos.ContentRepository.Core/Classes/Feature/Common/EmbedsContentStreamId.php
  Neos.ContentRepository.Core/Classes/Feature/Common/EmbedsNodeAggregateId.php
  Neos.ContentRepository.Core/Classes/Feature/Common/EmbedsWorkspaceName.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamClosing/Event/ContentStreamWasClosed.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamClosing/Event/ContentStreamWasReopened.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamCreation/Event/ContentStreamWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamRemoval/Event/ContentStreamWasRemoved.php
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/Event/DimensionShineThroughWasAdded.php
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/Event/DimensionSpacePointWasMoved.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Event/NodeAggregateWithNodeWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Event/NodeAggregateWasDisabled.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Event/NodeAggregateWasEnabled.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Event/NodePropertiesWereSet.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Event/NodeAggregateWasMoved.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Event/NodeReferencesWereSet.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/Event/NodeAggregateWasRemoved.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRenaming/Event/NodeAggregateNameWasChanged.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/Event/NodeAggregateTypeWasChanged.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/Event/NodeGeneralizationVariantWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/Event/NodePeerVariantWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/Event/NodeSpecializationVariantWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Event/RootNodeAggregateDimensionsWereUpdated.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Event/RootNodeAggregateWithNodeWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Event/SubtreeWasTagged.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Event/SubtreeWasUntagged.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCreation/Event/RootWorkspaceWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCreation/Event/WorkspaceWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Event/WorkspaceBaseWorkspaceWasChanged.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Event/WorkspaceOwnerWasChanged.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Event/WorkspaceWasRemoved.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Event/WorkspaceWasRenamed.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Event/WorkspaceWasDiscarded.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Event/WorkspaceWasPartiallyDiscarded.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Event/WorkspaceRebaseFailed.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Event/WorkspaceWasRebased.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamProjection.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
Labels: 9.0, Task

#5246 TASK: 5243 remove ContentGraphFinder runtime cache
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentRepository.Core/Classes/ContentGraphFinder.php
Labels: 9.0, Task

#5196 TASK: Improve JSON error handling
  Neos.ContentRepository.Core/Classes/DimensionSpace/AbstractDimensionSpacePoint.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/ContentSubgraphVariationWeight.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/DimensionSpacePointSet.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Dto/NodeAggregateIdsByNodePaths.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/PropertyValuesToWrite.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/SerializedPropertyValue.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/NodeReferencesToWrite.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
Labels: 9.0, Task

#5251 TASK: Improve error messages in case old transformations have been used
  Neos.ContentRepository.NodeMigration/src/Transformation/TransformationsFactory.php
Labels: 9.0, Task

#5229 TASK: Improve performance on content cache flush
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.monopic
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
Labels: 9.0, Task

#5254 BUGFIX: Flush content cache on rebase workspace
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
  Neos.Neos/Tests/Behavior/Features/ContentCache/NodesInUserWorkspace.feature
Labels: Bug, 9.0

#5256 FEATURE: Add UpdateRootNodeAggregateDimensions as transformation
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/UpdateRootNodeAggregateDimensions.feature
  Neos.ContentRepository.NodeMigration/src/NodeMigrationServiceFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/UpdateRootNodeAggregateDimensionsTransformationFactory.php
  Neos.Neos/Documentation/References/NodeMigrations.rst
Labels: Feature, 9.0

#5257 TASK: Add indices to improve parent/child query performance
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
Labels: 9.0, Task

#5253 BUGFIX: Remove default value for subtreetags to fix MySQL support
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
Labels: Bug, 9.0

#5263 TASK: Remove obsolete content cache flusher unit test
  Neos.Neos/Tests/Unit/Fusion/Cache/ContentCacheFlusherTest.php
Labels: 9.0, Task

#5149 TASK: Check against LiveWorkspaceName Instead Of Comparing CS Ids
  Neos.Neos/Classes/FrontendRouting/CatchUpHook/RouterCacheHook.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathFinder.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathSchemaBuilder.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: 9.0, Task

#5260 TASK: Streamline value object mapping usages
  Neos.ContentRepository.Core/Classes/EventStore/Events.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Dto/SubtreeTags.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeNames.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeTags.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Nodes.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeAggregateIds.php
  Neos.Neos/Classes/Fusion/Cache/CacheTagSet.php
  Neos.Neos/Classes/Fusion/MenuItemsImplementation.php
Labels: 9.0, Task

#5266 BUGFIX: 5265 - Ignore null values in SearchTermMatcher
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/SearchTerm/SearchTermMatcher.php
  Neos.ContentRepository.Core/Tests/Unit/Projection/ContentGraph/Filter/SearchTerm/SearchTermMatcherTest.php
Labels: Bug, 9.0
