Repository neos/neos-development-collection, pull requests merged in 2024-06, with the labels that each got.

#5112 Fix PHPStan baseline
  phpstan-baseline.neon
Labels: 9.0

#5110 BUGFIX: fix behat configuration template folder path in README.rst
  Readme.rst
Labels: Bug, 9.0

#5120 FEATURE: Update PHP Version in Behat Test docker file
  Neos.ContentRepository.BehavioralTests/Dockerfile.full
Labels: Feature, 9.0

#5121 BUGFIX: Fix title attribute for impersonate button in user management
  Neos.Neos/Resources/Public/JavaScript/Templates/ImpersonateButton.js
  Neos.Neos/Resources/Public/JavaScript/Templates/RestoreButton.js
Labels: Bug, 8.3

#5126 FEATURE: Link Neos logo in modules to primary module
  Neos.Neos/Classes/Controller/Backend/ModuleController.php
  Neos.Neos/Resources/Private/Partials/Backend/Branding.html
  Neos.Neos/Resources/Private/Templates/Backend/Module/Index.html
  Neos.Neos/Resources/Private/Translations/en/Modules.xlf
Labels: Feature, 8.4

#5115 TASK: Unify naming of contentRepositoryIdentifier to contentRepository in ESCR CLI commands
  Neos.ContentRepositoryRegistry/Classes/Command/ContentStreamCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/NodeMigrationCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/StructureAdjustmentsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/SubprocessProjectionCatchUpCommandController.php
  Neos.Neos/Classes/Command/WorkspaceCommandController.php
  Neos.Neos/Documentation/References/CommandReference.rst
Labels: 9.0, Task

#5124 BUGFIX: Flush cache also for deleted nodes
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Labels: Bug, 8.3

#5117 BUGFIX: Prevent multiple imports of the same remote asset in the frontend
  Neos.Media.Browser/Resources/Private/Layouts/Default.html
  Neos.Media.Browser/Resources/Private/Translations/en/Main.xlf
  Neos.Media.Browser/Resources/Public/JavaScript/select.js
  Neos.Neos/Resources/Public/JavaScript/Services/Configuration.js
Labels: Bug, 8.3

#4990 TASK: Remove i18n labels that are obsolete after neos/neos-ui#3759
  Neos.Neos/Resources/Private/Translations/ar/Main.xlf
  Neos.Neos/Resources/Private/Translations/cs/Main.xlf
  Neos.Neos/Resources/Private/Translations/da/Main.xlf
  Neos.Neos/Resources/Private/Translations/de/Main.xlf
  Neos.Neos/Resources/Private/Translations/el/Main.xlf
  Neos.Neos/Resources/Private/Translations/en/Main.xlf
  Neos.Neos/Resources/Private/Translations/es/Main.xlf
  Neos.Neos/Resources/Private/Translations/fi/Main.xlf
  Neos.Neos/Resources/Private/Translations/fr/Main.xlf
  Neos.Neos/Resources/Private/Translations/hu/Main.xlf
  Neos.Neos/Resources/Private/Translations/id_ID/Main.xlf
  Neos.Neos/Resources/Private/Translations/it/Main.xlf
  Neos.Neos/Resources/Private/Translations/ja/Main.xlf
  Neos.Neos/Resources/Private/Translations/km/Main.xlf
  Neos.Neos/Resources/Private/Translations/lv/Main.xlf
  Neos.Neos/Resources/Private/Translations/nl/Main.xlf
  Neos.Neos/Resources/Private/Translations/no/Main.xlf
  Neos.Neos/Resources/Private/Translations/pl/Main.xlf
  Neos.Neos/Resources/Private/Translations/pt/Main.xlf
  Neos.Neos/Resources/Private/Translations/pt_BR/Main.xlf
  Neos.Neos/Resources/Private/Translations/ru/Main.xlf
  Neos.Neos/Resources/Private/Translations/sr/Main.xlf
  Neos.Neos/Resources/Private/Translations/sv/Main.xlf
  Neos.Neos/Resources/Private/Translations/tl_PH/Main.xlf
  Neos.Neos/Resources/Private/Translations/tr/Main.xlf
  Neos.Neos/Resources/Private/Translations/uk/Main.xlf
  Neos.Neos/Resources/Private/Translations/vi/Main.xlf
  Neos.Neos/Resources/Private/Translations/zh/Main.xlf
  Neos.Neos/Resources/Private/Translations/zh_TW/Main.xlf
Labels: 9.0, Task

#5135 FEATURE: Improve site:list command
  Neos.Neos/Classes/Command/SiteCommandController.php
Labels: Feature, 8.4

#5099 TASK: Use correct @template-covariant tag for ProjectionFactoryInterface
  Neos.ContentRepository.Core/Classes/Projection/ProjectionFactoryInterface.php
Labels: 9.0, Task

#5140 BUGFIX: Access isNil function from Helper function to apply selected image to property
  Neos.Media.Browser/Resources/Public/JavaScript/select.js
Labels: Bug, P: Media Browser, 8.3

#5137 TASK: Tweak README
  CONTRIBUTING.md
  README.md
  Readme.rst
Labels: 9.0, Task

#5089 TASK: Remove `--reset-projections` flag from `cr:setup` command
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
Labels: Bug, 9.0, Task

#5141 TASK: Consolidate contributing file
  .github/CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 9.0, Task

#5139 TASK: Remove `createSitePackage` action
  Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
  Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/NewSite.html
  Neos.Neos/Resources/Private/Translations/en/Modules.xlf
Labels: 9.0, Task

#5122 BUGFIX: Flush node content caches without workspace name
  Neos.Neos/Classes/Fusion/Cache/CacheTag.php
  Neos.Neos/Classes/Fusion/Cache/CacheTagSet.php
  Neos.Neos/Classes/Fusion/Cache/CacheTagWorkspaceName.php
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
  Neos.Neos/Classes/Fusion/Helper/CachingHelper.php
  Neos.Neos/Tests/Unit/Fusion/Helper/CachingHelperTest.php
Labels: Bug, 9.0

#5083 BUGFIX Workspace aware NodeCacheEntryIdentifier
  Neos.Neos/Classes/Fusion/Cache/NodeCacheEntryIdentifier.php
  Neos.Neos/Classes/Fusion/Helper/CachingHelper.php
Labels: Bug, 9.0

#5136 !!! TASK: Make kickstart:site command work with Neos 9.0
  Neos.SiteKickstarter/Classes/Command/KickstartCommandController.php
  Neos.SiteKickstarter/Classes/Generator/AfxTemplateGenerator.php
  Neos.SiteKickstarter/Classes/Generator/SitePackageGeneratorInterface.php
  Neos.SiteKickstarter/Classes/Service/FusionRecursiveDirectoryRenderer.php
  Neos.SiteKickstarter/Classes/Service/SimpleTemplateRenderer.php
  Neos.SiteKickstarter/Classes/Service/SiteGeneratorCollectingService.php
  Neos.SiteKickstarter/Classes/Service/SitePackageGeneratorNameService.php
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/Content/Sites.xml
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/Fusion/Document/Homepage.fusion
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/NodeTypes/Document.Homepage.yaml
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/NodeTypes/Document.Page.yaml
  Neos.SiteKickstarter/Tests/Unit/Service/Fixtures/BlankSitePackageGenerator.php
  Neos.SiteKickstarter/Tests/Unit/Service/Fixtures/NamedSitePackageGenerator.php
  phpstan.neon.dist
Labels: Bug, 9.0

#5163 BUGFIX: Fix content cache for discard, revert #5083 for now
  Neos.Neos/Classes/Fusion/Cache/NodeCacheEntryIdentifier.php
  Neos.Neos/Classes/Fusion/Helper/CachingHelper.php
  Neos.Neos/Tests/Behavior/Features/ContentCache/NodesInUserWorkspace.feature
Labels: Bug, 9.0

#4892 !!! FEATURE: Overhaul node uri building
  Neos.ContentRepository.Core/Classes/DimensionSpace/DimensionSpacePoint.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeAddress.php
  Neos.ContentRepository.Core/Tests/Unit/SharedModel/Node/NodeAddressTest.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
  Neos.Neos/Classes/FrontendRouting/FrontendNodeRoutePartHandlerInterface.php
  Neos.Neos/Classes/FrontendRouting/NodeAddress.php
  Neos.Neos/Classes/FrontendRouting/NodeAddressFactory.php
  Neos.Neos/Classes/FrontendRouting/NodeShortcutResolver.php
  Neos.Neos/Classes/FrontendRouting/NodeUriBuilder.php
  Neos.Neos/Classes/FrontendRouting/NodeUriBuilderFactory.php
  Neos.Neos/Classes/FrontendRouting/Options.php
  Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
  Neos.Neos/Classes/Fusion/Helper/LinkHelper.php
  Neos.Neos/Classes/Fusion/NodeUriImplementation.php
  Neos.Neos/Classes/Routing/NodeIdentityConverterAspect.php
  Neos.Neos/Classes/Service/LinkingService.php
  Neos.Neos/Classes/ViewHelpers/Link/NodeViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Uri/NodeViewHelper.php
  Neos.Neos/Configuration/Routes.Frontend.yaml
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
Labels: 9.0

#5165 TASK: Use `8.4.x-dev` of `neos/flow-development-collection`
  .composer.json
  Neos.Neos/composer.json
  Neos.SiteKickstarter/composer.json
  composer.json
Labels: Task, 8.4

#5162 BUGFIX: Dont initialize $currentContentStreamId by default in behat tests
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteRuntimeVariables.php
  Neos.Neos/Tests/Behavior/Features/ContentCache/NodesInUserWorkspace.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Basic.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Lowlevel_ProjectionTests.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/RouteCache.feature
Labels: Bug, 9.0

#5166 BUGFIX: Case insensitive user search on PostgreSQL
  Neos.Neos/Classes/Domain/Repository/UserRepository.php
Labels: Bug, 8.3
