Repository neos/neos-development-collection, pull requests merged in 2024-08, with the labels that each got.

#5183 Bugfix/5116: bundle js in Neos.Neos
  Neos.Neos/Resources/Public/JavaScript/Main.min.js
  Neos.Neos/Resources/Public/JavaScript/Main.min.js.map
Labels: 8.3

#5193 FEATURE: Stabilize WorkspaceName value object
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/WorkspaceName.php
  Neos.ContentRepository.Core/Tests/Unit/SharedModel/Workspace/WorkspaceNameTest.php
Labels: Feature, 9.0

#5194 FEATURE: Expose content repository ids from registry
  Neos.ContentRepository.Core/Classes/SharedModel/ContentRepository/ContentRepositoryIds.php
  Neos.ContentRepository.Core/Tests/Unit/SharedModel/ContentRepository/ContentRepositoryIdsTest.php
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
Labels: Feature, 9.0

#5198 BUGFIX: Changed from hardcoded date format to user-localized format.
  Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Index.html
Labels: Bug, 8.3

#530 FEATURE: Custom label for auto created child nodes
  Neos.ContentRepository/Classes/Domain/Model/ExpressionBasedNodeLabelGenerator.php
  Neos.ContentRepository/Configuration/Testing/NodeTypes.yaml
  Neos.ContentRepository/Resources/Private/Schema/NodeTypes.schema.yaml
  Neos.ContentRepository/Tests/Functional/Domain/NodesTest.php
  Neos.NodeTypes.ColumnLayouts/NodeTypes/Content/FourColumn.yaml
  Neos.NodeTypes.ColumnLayouts/NodeTypes/Content/ThreeColumn.yaml
  Neos.NodeTypes.ColumnLayouts/NodeTypes/Content/TwoColumn.yaml
Labels: P: Node Types, P: Neos, T: PHP, Feature, 8.4

#4503 BUGFIX: Don’t include subnodetypes of subnodetypes in node search
  Neos.Neos/Classes/Controller/Service/NodesController.php
Labels: Bug, 8.3

#5186 BUGFIX: Don’t copy removed nodes
  Neos.ContentRepository/Classes/Domain/Model/Node.php
  Neos.ContentRepository/Classes/Domain/Model/NodeData.php
  Neos.ContentRepository/Tests/Functional/Domain/NodesTest.php
Labels: Bug, 8.3

#5202 TASK: Add migration for workspaceName constraints
  Neos.ContentRepositoryRegistry/Classes/Command/MigrateEventsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
Labels: 9.0, Task

#5203 BUGFIX: Sort roles for users by label instead of internal name in the UI
  Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
Labels: Bug, 8.3

#5133 BUGFIX: Translate FlashMessage if asset is still in use in media browser inspector
  Neos.Media.Browser/Classes/Controller/AssetController.php
Labels: Bug, 8.3

#5195 !!! BUGFIX: Consider entry node when filtering in reference editor
  Neos.ContentGraph.DoctrineDbalAdapter/src/NodeQueryBuilder.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/ChildNodes.feature
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/SerializedPropertyValue.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountBackReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountDescendantNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindBackReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindDescendantNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindPrecedingSiblingNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindSucceedingSiblingNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/SearchTerm/SearchTerm.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/SearchTerm/SearchTermMatcher.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Nodes.php
  Neos.ContentRepository.Core/Tests/Unit/Projection/ContentGraph/Filter/SearchTerm/SearchTermMatcherTest.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  phpstan-baseline.neon
Labels: Bug, 9.0

#5211 BUGFIX: Optimize queries for subtree tags
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/SubtreeTagging.php
Labels: Bug, 9.0

#5205 TASK: Case sensitive migration and migration of baseWorkspaceName
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/WorkspaceName.php
  Neos.ContentRepository.Core/Tests/Unit/SharedModel/Workspace/WorkspaceNameTest.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
  Neos.Neos/Classes/Domain/Service/WorkspaceNameBuilder.php
Labels: 9.0, Task

#5212 BUGFIX: Ensure a valid target workspace name
  Neos.ContentRepositoryRegistry/Classes/Command/NodeMigrationCommandController.php
Labels: Bug, 9.0

#5216 BUGFIX: Adjust service templates for references
  Neos.Neos/Classes/ViewHelpers/Node/LabelViewHelper.php
  Neos.Neos/Resources/Private/Templates/Service/Nodes/Index.html
  Neos.Neos/Resources/Private/Templates/Service/Nodes/Show.html
Labels: Bug, 9.0

#5219 BUGFIX 5218 - declare dependency of Registry on StructureAdjustments
  Neos.ContentRepositoryRegistry/composer.json
Labels: 9.0

#5223 BUGFIX 5222 - use valid workspace name substitutes
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
Labels: 9.0

#5214 BUGFIX: cr:projectionReplay cli progress advancing
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
Labels: Bug, 9.0

#5224 BUGFIX: Make URI suffix configurable for the ESFrontendNode RoutePart
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
Labels: Bug, 9.0, 9.0beta12

#5221 FEATURE: Overhaul ContentCacheFlusher
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/ForkContentStreamWithoutDimensions.feature
  Neos.Neos/Classes/Fusion/Cache/AssetChangeHandlerForCacheFlushing.php
  Neos.Neos/Classes/Fusion/Cache/CacheFlushingStrategy.php
  Neos.Neos/Classes/Fusion/Cache/CacheTag.php
  Neos.Neos/Classes/Fusion/Cache/CacheTagSet.php
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
  Neos.Neos/Classes/Fusion/Cache/FlushNodeAggregateRequest.php
  Neos.Neos/Classes/Fusion/Cache/FlushWorkspaceRequest.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
  Neos.Neos/Classes/Fusion/Cache/NodeCacheEntryIdentifier.php
  Neos.Neos/Classes/Fusion/Helper/CachingHelper.php
  Neos.Neos/Classes/Package.php
  Neos.Neos/Tests/Behavior/Features/ContentCache/Assets.feature
  Neos.Neos/Tests/Behavior/Features/ContentCache/Nodes.feature
  Neos.Neos/Tests/Behavior/Features/ContentCache/NodesInUserWorkspace.feature
  Neos.Neos/Tests/Unit/Fusion/Helper/CachingHelperTest.php
Labels: Feature, 9.0
