Repository neos/neos-development-collection, pull requests merged in 2024-01, with the labels that each got.

#4819 BUGFIX: Fix StyleCI issues
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
Labels: Bug, 8.3

#4820 BUGFIX: Resolve StyleCI issues
  Neos.Fusion/Classes/Core/Parser.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
Labels: Bug, 7.3

#4812 BUGFIX: Check SVG files for malicious code before providing original asset url links
  Neos.Media.Browser/Classes/Controller/AssetController.php
  Neos.Media.Browser/Resources/Private/Partials/ContentDefaultPreview.html
  Neos.Media.Browser/Resources/Private/Templates/Asset/Edit.html
  Neos.Media.Browser/Resources/Private/Templates/Asset/Show.html
  Neos.Media.Browser/Resources/Private/Translations/en/Main.xlf
  Neos.Media.Browser/composer.json
  composer.json
Labels: Bug, 7.3

#4823 BUGFIX: More precise selection of the DomNode with CSFR token
  Neos.Neos/Resources/Public/JavaScript/Components/TopBar/UserMenu.js
  Neos.Neos/Resources/Public/JavaScript/Main.min.js
  Neos.Neos/Resources/Public/JavaScript/Main.min.js.map
  Neos.Neos/Resources/Public/JavaScript/Module/Administration/UserManagement.js
Labels: Bug, 8.0

#4798 BUGFIX: Fixup #4679 constraints in node references
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/01-SetNodeReferences_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/02-SetNodeReferences_WithoutDimensions.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/NodeType/ConstraintCheck.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/References.php
Labels: Bug, 9.0

#3986 BUGFIX: Add dimensions to Workspace module
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html
Labels: Bug, 7.3

#4845 TASK: Update neos/eventstore packages to 1.0
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/HypergraphProjection.php
  Neos.ContentRepository.BehavioralTests/Classes/ProjectionRaceConditionTester/RaceTrackerCatchUpHook.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/EventStore/DecoratedEvent.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeAggregateEventPublisher.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalCheckpointStorage.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUp.php
  Neos.ContentRepository.Core/Classes/Projection/CheckpointStorageInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphProjection.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamProjection.php
  Neos.ContentRepository.Core/Classes/Projection/NodeHiddenState/NodeHiddenStateProjection.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionInterface.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.ContentRepository.Core/Tests/Unit/EventStore/DecoratedEventTest.php
  Neos.ContentRepository.Export/src/Event/ValueObject/ExportedEvent.php
  Neos.ContentRepository.Export/src/Processors/EventStoreImportProcessor.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjection.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepository.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  composer.json
  phpstan-baseline.neon
Labels: 9.0, Task

#4846 FEATURE: Content Repository status
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/HypergraphProjection.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalCheckpointStorage.php
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalSchemaDiff.php
  Neos.ContentRepository.Core/Classes/Projection/CheckpointStorageInterface.php
  Neos.ContentRepository.Core/Classes/Projection/CheckpointStorageStatus.php
  Neos.ContentRepository.Core/Classes/Projection/CheckpointStorageStatusType.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphProjection.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamProjection.php
  Neos.ContentRepository.Core/Classes/Projection/NodeHiddenState/NodeHiddenStateProjection.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionStatus.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionStatusType.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionStatuses.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.ContentRepository.Core/Classes/SharedModel/ContentRepository/ContentRepositoryStatus.php
  Neos.ContentRepository.Core/Tests/Unit/Infrastructure/DbalSchemaDiffTest.php
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjection.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepository.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: Feature, 9.0

#4847 BUGFIX: Fix projection database schema
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalSchemaFactory.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepository.php
Labels: Bug, 9.0

#4854 TASK: Correct `DoctrineProxy` import in AssetController
  Neos.Media.Browser/Classes/Controller/AssetController.php
Labels: 8.3, Task

#4860 TASK: Dont use NodeInfoHelper::renderNode
  Neos.Neos/Classes/Service/ContentElementWrappingService.php
Labels: 9.0, Task

#4827 BUGFIX: 4824 FusionExceptionView doesnt set editPreviewMode correctly
  Neos.Neos/Classes/View/FusionExceptionView.php
Labels: Bug, 9.0

#4731 BUGFIX: #3624 Node::getProperty does not always return list for references
  Neos.ContentRepository/Classes/Domain/Model/Node.php
  Neos.ContentRepository/Tests/Functional/Domain/NodesTest.php
Labels: Bug, 8.3

#4791 !!! TASK: Use integers as lightweight nodeanchorpoints
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/ProjectionIntegrityViolationDetectionTrait.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/NodeRecord.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/NodeRelationAnchorPoint.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalSchemaFactory.php
Labels: 9.0

#4863 TASK: Exclude possible EEL helpers residing in `Neos.Ui` as they are internal
  Neos.Neos/Configuration/Settings.yaml
Labels: 9.0, Task
