Repository neos/neos-development-collection, pull requests merged in 2024-05, with the labels that each got.

#5016 TASK: Cleanup `EventNormalizer`
  Neos.ContentRepository.Core/Classes/EventStore/EventNormalizer.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepository.Export/src/Processors/EventStoreImportProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
Labels: Feature, 9.0, Task

#5026 BUGFIX: Fix Subtree tagging CTE implementation
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/SubtreeTagging.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/SubtreeTagging/TagSubtree_WithoutDimensions.feature
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/NodeTraversalTrait.php
Labels: Bug, 4993-fixMoveSubtreeTags

#4788 BUGFIX: Flush node caches when asset has changed
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/AssetTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/ContentCacheTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/ContentCache/Assets.feature
  Neos.Neos/Tests/Behavior/Features/ContentCache/ConvertUris.feature
  Neos.Neos/Tests/Behavior/Features/ContentCache/Nodes.feature
  Neos.Neos/Tests/Behavior/Features/ContentCache/NodesInOtherWorkspace.feature
Labels: Bug, 9.0

#5025 4993 - Actually execute moveSubtreeTags tests and fix moveSubtreeTags
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/NodeMove.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/SubtreeTagging.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/05-MoveNodeAggregate_SubtreeTags.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/SubtreeTagging/TagSubtree_WithoutDimensions.feature
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeTags.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeTrait.php
Labels: 9.0

#5029 TASK: Change loading of objects notation in behat tests
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/ContentCache/Assets.feature
Labels: 9.0, Task

#5035 TASK: Reset `$this->currentWorkspaceName` in behat tests before scenario
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
Labels: 9.0, Task

#5036 TASK: Remove legacy cr functional test artifacts
  Neos.ContentRepository.Core/Tests/Functional/Domain/Fixtures/TestNodePostprocessor.php
  Neos.ContentRepository.Core/Tests/Functional/Domain/Fixtures/TestObjectForSerialization.php
  Neos.ContentRepository.Core/Tests/Functional/Fixtures/NodeStructure.xml
  Neos.ContentRepository.Core/Tests/Functional/Fixtures/NodesWithAndWithoutDimensions.xml
  Neos.ContentRepository.NodeAccess/Configuration/Testing/Behat/Settings.yaml
  Neos.ContentRepository.NodeAccess/Configuration/Testing/NodeTypes.yaml
  Neos.ContentRepository.NodeAccess/Configuration/Testing/Policy.yaml
  Neos.Neos/Tests/Functional/AbstractNodeTest.php
  Neos.Neos/Tests/Functional/Domain/Service/Fixtures/Sites.xml
  Neos.Neos/Tests/Functional/FlowQueryOperations/Fixtures/SortableNodes.xml
  Neos.Neos/Tests/Functional/FlowQueryOperations/SortOperationTest.php
  Neos.Neos/Tests/Functional/Fusion/Cache/ContentCacheFlusherTest.php
  Neos.Neos/Tests/Functional/Fusion/Cache/Fixtures/CacheableNodes.xml
Labels: 9.0, Task

#5049 TASK: WIP Prepare for synchronous content repository
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandResult.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepositoryRegistry/Classes/Factory/ProjectionCatchUpTrigger/CatchUpTriggerWithSynchronousOption.php
Labels: 9.0, Task

#5046 FEATURE: 9.0 Node access flow query operations
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/IdOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/LabelOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/NodeTypeNameOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PropertyOperation.php
  Neos.ContentRepositoryRegistry/Classes/NodeLabel/ExpressionBasedNodeLabelGenerator.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCase.fusion
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
Labels: Feature, 9.0

#4948 BUGFIX: Fix `contentgraphintegrity:runviolationdetection`
  Neos.ContentRepositoryRegistry/Classes/Command/ContentGraphIntegrityCommandController.php
Labels: Bug, 9.0

#5042 FEATURE: workspace aware Node (introduce new `NodeAdress`)
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/DimensionSpacePoint.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphWithRuntimeCaches/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphIdentity.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeAggregate.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/VisibilityConstraints.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeAddress.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/CreateNodeHashTrait.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/FindOperation.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.StructureAdjustment/src/StructureAdjustmentService.php
  Neos.ContentRepository.TestSuite/Classes/Unit/NodeSubjectProvider.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentCommandController.php
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/Domain/Service/SiteNodeUtility.php
  Neos.Neos/Classes/FrontendRouting/NodeAddress.php
  Neos.Neos/Classes/FrontendRouting/NodeAddressFactory.php
  Neos.Neos/Classes/Fusion/Cache/NeosFusionContextSerializer.php
  Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php
  Neos.Neos/Classes/Fusion/Helper/CachingHelper.php
  Neos.Neos/Classes/Fusion/Helper/DimensionHelper.php
  Neos.Neos/Classes/Service/LinkingService.php
  Neos.Neos/Classes/View/FusionExceptionView.php
  Neos.Neos/Tests/Unit/Fusion/Helper/CachingHelperTest.php
  Neos.TimeableNodeVisibility/Classes/Service/TimeableNodeVisibilityService.php
Labels: Feature, 9.0

#4291 BUGFIX: Invalidate caches correctly after node move changes have been discarded
  Neos.ContentRepository/Classes/Domain/Service/PublishingService.php
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Labels: Bug, 8.3

#5020 !!! TASK: Make node label pure neos concept
  Neos.ContentRepository.BehavioralTests/Classes/TestSuite/Behavior/GherkinPyStringNodeBasedNodeTypeManagerFactory.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Feature/WorkspacePublication/WorkspaceWritingDuringPublication.php
  Neos.ContentRepository.Core/Classes/NodeType/DefaultNodeLabelGeneratorFactory.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeLabelGeneratorFactoryInterface.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeLabelGeneratorInterface.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeManager.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php
  Neos.ContentRepository.Core/Tests/Unit/Feature/NodeCreation/Dto/NodeAggregateIdsByNodePathsTest.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeManagerTest.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeTest.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/LabelOperation.php
  Neos.ContentRepository.NodeAccess/Configuration/Settings.yaml
  Neos.ContentRepositoryRegistry/Classes/Factory/NodeTypeManager/DefaultNodeTypeManagerFactory.php
  Neos.ContentRepositoryRegistry/Classes/Factory/NodeTypeManager/ObjectManagerBasedNodeLabelGeneratorFactory.php
  Neos.ContentRepositoryRegistry/Configuration/Objects.yaml
  Neos.Neos/Classes/Domain/NodeLabel/DelegatingNodeLabelRenderer.php
  Neos.Neos/Classes/Domain/NodeLabel/ExpressionBasedNodeLabelGenerator.php
  Neos.Neos/Classes/Domain/NodeLabel/NodeLabelGeneratorInterface.php
  Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Classes/Fusion/MenuItemsImplementation.php
  Neos.Neos/Classes/Utility/NodeUriPathSegmentGenerator.php
  Neos.Neos/Classes/ViewHelpers/Link/NodeViewHelper.php
  Neos.Neos/Configuration/Objects.yaml
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/Documentation/References/NodeTypeDefinition.rst
  Neos.Neos/Resources/Private/Fusion/Prototypes/NodeLink.fusion
  Neos.Neos/Resources/Private/Fusion/RawContent/NodeHeader.fusion
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
  Neos.Neos/Tests/Functional/Fusion/NodeHelperTest.php
  Neos.Neos/Tests/Functional/Service/NodeTypeSchemaBuilderTest.php
  Neos.Neos/Tests/Unit/NodeTypePostprocessor/DefaultPropertyEditorPostprocessorTest.php
  Neos.TimeableNodeVisibility/Classes/Command/TimeableNodeVisibilityCommandController.php
  Neos.TimeableNodeVisibility/Classes/Service/TimeableNodeVisibilityService.php
Labels: 9.0, Task

#4921 !!! TASK: Rename `_hiddenInIndex` to `hiddenInMenu`
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/FilterOperation.php
  Neos.Neos/Classes/Fusion/AbstractMenuItemsImplementation.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Documentation/References/NeosFusionReference.rst
  Neos.Neos/NodeTypes/Mixin/Document.yaml
  Neos.Neos/Resources/Private/Fusion/Prototypes/BreadcrumbMenu.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/BreadcrumbMenuItems.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/DimensionsMenu.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/DimensionsMenuItems.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/Menu.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/MenuItems.fusion
  Neos.Neos/Resources/Private/Styles/_Tree.scss
  Neos.Neos/Resources/Private/Translations/ar/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/cs/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/da/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/de/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/el/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/en/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/es/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/fi/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/fr/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/hu/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/id_ID/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/it/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/ja/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/km/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/lv/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/nl/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/no/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/pl/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/pt/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/pt_BR/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/ru/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/sr/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/sv/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/tl_PH/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/tr/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/uk/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/vi/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/zh/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/zh_TW/NodeTypes/Document.xlf
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/Menu.feature
Labels: 9.0, Task

#5053 BUGFIX: Fix broken XLIFF files
  Neos.Neos/Resources/Private/Translations/ar/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/cs/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/da/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/el/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/es/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/fi/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/fr/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/hu/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/id_ID/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/it/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/ja/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/km/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/lv/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/nl/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/no/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/pl/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/pt_BR/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/ru/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/sr/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/sv/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/tl_PH/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/tr/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/uk/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/vi/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/zh/NodeTypes/Document.xlf
  Neos.Neos/Resources/Private/Translations/zh_TW/NodeTypes/Document.xlf
Labels: Bug, 9.0

#4832 TASK: Document NodeAggregate
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/InterDimensionalVariationGraph.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeAggregate.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.Neos/Classes/View/FusionExceptionViewInternals.php
Labels: 9.0, Task

#5048 TASK: Combine two `NodeTypeNotFoundExceptions` into one
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/NodeTypeChange.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/RootNodeHandling.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeManager.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/NodeTypeNotFoundException.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeManagerTest.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DimensionAdjustment.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/StructureAdjustmentsTrait.php
  Neos.Media.Browser/Classes/Controller/UsageController.php
  Neos.Neos/Classes/Command/SiteCommandController.php
  Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Labels: 9.0, Task

#5055 FEATURE: Workspace aware content cache
  Neos.Neos/Classes/Fusion/Cache/CacheTag.php
  Neos.Neos/Classes/Fusion/Cache/CacheTagSet.php
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
  Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
  Neos.Neos/Classes/Fusion/Helper/CachingHelper.php
  Neos.Neos/Tests/Behavior/Features/ContentCache/Nodes.feature
  Neos.Neos/Tests/Unit/Fusion/Helper/CachingHelperTest.php
Labels: Feature, 9.0

#4906 !!! TASK: Followup #4520 Introduce `NodeType::tetheredNodeTypeDefinitions`
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/Common/TetheredNodeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Dto/NodeAggregateIdsByNodePaths.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/NodeTypeChange.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/RootNodeHandling.php
  Neos.ContentRepository.Core/Classes/NodeType/Exception/TetheredNodeNotConfigured.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeManager.php
  Neos.ContentRepository.Core/Classes/NodeType/TetheredNodeTypeDefinition.php
  Neos.ContentRepository.Core/Classes/NodeType/TetheredNodeTypeDefinitions.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeManagerTest.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DisallowedChildNodeAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.Neos/Classes/Service/NodeTypeSchemaBuilder.php
Labels: 9.0, Task

#5052 TASK: Allow PropertyName in `Node::getProperty`
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php
Labels: 9.0, Task

#5063 TASK: Add workspaceName to nodeAggregate
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeAggregate.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/StructureAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeAggregateTrait.php
Labels: 9.0, Task

#5070 BUGFIX: Properly convert legacy MoveNodeMappings
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Event/NodeAggregateWasMoved.php
  Neos.ContentRepository.Core/Tests/Unit/Feature/NodeMove/Event/NodeAggregateWasMovedTest.php
Labels: Bug, 9.0

#5071 TASK: Remove DbalClient abstraction
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/ProjectionIntegrityViolationDetectionTrait.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphFactory.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjectionFactory.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalProjectionIntegrityViolationDetectionRunnerFactory.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/ProjectionIntegrityViolationDetector.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/ContentHyperGraphFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/HypergraphProjection.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/ProjectionHypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/HypergraphProjectionFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Infrastructure/PostgresDbalClientInterface.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalClientInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamFinder.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamProjection.php
  Neos.ContentRepository.Core/Classes/Projection/ContentStream/ContentStreamProjectionFactory.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceFinder.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjectionFactory.php
  Neos.ContentRepositoryRegistry.DoctrineDbalClient/Classes/DoctrineDbalClient.php
  Neos.ContentRepositoryRegistry.DoctrineDbalClient/Configuration/Caches.yaml
  Neos.ContentRepositoryRegistry.DoctrineDbalClient/Configuration/Objects.yaml
  Neos.ContentRepositoryRegistry.DoctrineDbalClient/Configuration/Settings.yaml
  Neos.ContentRepositoryRegistry.DoctrineDbalClient/composer.json
  Neos.ContentRepositoryRegistry.PostgresDbalClient/Classes/PostgresDbalClient.php
  Neos.ContentRepositoryRegistry.PostgresDbalClient/Configuration/Caches.yaml
  Neos.ContentRepositoryRegistry.PostgresDbalClient/Configuration/Objects.yaml
  Neos.ContentRepositoryRegistry.PostgresDbalClient/composer.json
  Neos.ContentRepositoryRegistry/Classes/Command/ContentGraphIntegrityCommandController.php
  Neos.ContentRepositoryRegistry/Configuration/Objects.yaml
  Neos.ContentRepositoryRegistry/Configuration/Settings.yaml
  Neos.Neos/Classes/PendingChangesProjection/ChangeFinder.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjectionFactory.php
  composer.json
Labels: 9.0, Task

#5073 BUGFIX: Fix behat steps
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRetyping/ChangeNodeAggregateType_BasicErrorCases.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRetyping/ChangeNodeAggregateType_DeleteStrategy.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRetyping/ChangeNodeAggregateType_HappyPathStrategy.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/Timestamps.feature
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeTypeChange.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Lowlevel_ProjectionTests.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Shortcuts.feature
Labels: Bug, 9.0

#5044 TASK: Remove shallow `ContentGraphProjection` decorator
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjectionFactory.php
  Neos.ContentRepository.Core/Classes/EventStore/EventNormalizer.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphProjection.php
Labels: 9.0, Task

#4637 TASK: Make the `ImageInterfaceArrayPresenter` required by the ui the …
  Neos.Neos/Configuration/Settings.yaml
Labels: 9.0, Task, 9.1

#5081 TASK: Remove usages of `$node->subgraphIdentity->contentStreamId` in structure adjustments
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DimensionAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DisallowedChildNodeAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/ProjectedNodeIterator.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/PropertyAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/UnknownNodeTypeAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/StructureAdjustmentService.php
Labels: 9.0, Task

#5013 BUGFIX: Workspace module: Tweak UX for collapsed rows in rewiew
  Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html
Labels: Bug, 8.3

#5079 !!! TASK: Remove concepts `addQueryString` and `argumentsToBeExcludedFromQueryString` in Neos
  Neos.Fusion/Classes/FusionObjects/ActionUriImplementation.php
  Neos.Fusion/Classes/FusionObjects/UriBuilderImplementation.php
  Neos.Fusion/Resources/Private/Fusion/Deprecated/UriBuilder.fusion
  Neos.Fusion/Resources/Private/Fusion/Prototypes/ActionUri.fusion
  Neos.Neos/Classes/Fusion/NodeUriImplementation.php
  Neos.Neos/Classes/Service/LinkingService.php
  Neos.Neos/Classes/ViewHelpers/Link/ModuleViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Link/NodeViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Uri/ModuleViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Uri/NodeViewHelper.php
  Neos.Neos/Documentation/References/NeosFusionReference.rst
  Neos.Neos/Resources/Private/Fusion/Prototypes/NodeLink.fusion
  Neos.Neos/Resources/Private/Fusion/Prototypes/NodeUri.fusion
Labels: 9.0

#5087 BUGFIX: Violation detection: Fix selection of node ids by content stream
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/ProjectionIntegrityViolationDetector.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ProjectionIntegrityViolationDetection/NodeAggregatesAreConsistentlyClassifiedPerContentStream.feature
Labels: Bug, 9.0

#5094 BUGFIX: Fix linting error in `ConvertUrisImplementation`
  Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
Labels: Bug, 9.0

#5088 TASK: Cleanup and stabilize `Neos.ContentGraph.DoctrineDbalAdapter`
  Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphFactory.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/EventCouldNotBeAppliedToContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/NodeMove.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/NodeRemoval.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/NodeVariation.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/SubtreeTagging.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/HierarchyRelation.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/NodeRecord.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/ProjectionIntegrityViolationDetector.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/DimensionSpacePointsRepository.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/NodeQueryBuilder.php
Labels: 9.0, Task

#5098 FEATURE: Add `NodeAggregateId::tryFromString()` constructor
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeAggregateId.php
Labels: Feature, 9.0

#5092 TASK: Cosmetic cleanup of `DoctrineDbalContentGraphProjection`
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
Labels: 9.0, Task

#5106 BUGFIX AssetUsage in MediaBrowser
  Neos.Media.Browser/Classes/Controller/UsageController.php
  Neos.Media.Browser/Resources/Private/Templates/Usage/RelatedNodes.html
Labels: 9.0
