Repository neos/neos-development-collection, pull requests merged in 2024-10, with the labels that each got.

#5270 BUGFIX: Handle non-existing workspaces gracefully
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
Labels: Bug, 9.0

#5258 FEATURE: AssetUsage as CatchUpHook
  .github/workflows/build.yml
  Neos.ContentRepository.Export/src/ExportService.php
  Neos.ContentRepository.Export/src/ExportServiceFactory.php
  Neos.ContentRepository.Export/src/Processors/AssetExportProcessor.php
  Neos.Media.Browser/Classes/Controller/UsageController.php
  Neos.Media.Browser/Resources/Private/Templates/Usage/RelatedNodes.html
  Neos.Neos/Classes/AssetUsage/AssetUsageIndexingProcessor.php
  Neos.Neos/Classes/AssetUsage/AssetUsageService.php
  Neos.Neos/Classes/AssetUsage/AssetUsageStrategy.php
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHook.php
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHookFactory.php
  Neos.Neos/Classes/AssetUsage/Command/AssetUsageCommandController.php
  Neos.Neos/Classes/AssetUsage/Domain/AssetUsage.php
  Neos.Neos/Classes/AssetUsage/Domain/AssetUsageRepository.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsageFilter.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsageNodeAddress.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsageReference.php
  Neos.Neos/Classes/AssetUsage/Dto/AssetUsages.php
  Neos.Neos/Classes/AssetUsage/GlobalAssetUsageService.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageFinder.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjection.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjectionFactory.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepository.php
  Neos.Neos/Classes/AssetUsage/Projection/AssetUsageRepositoryFactory.php
  Neos.Neos/Classes/AssetUsage/Service/AssetUsageIndexingService.php
  Neos.Neos/Classes/AssetUsage/Service/AssetUsageSyncService.php
  Neos.Neos/Classes/AssetUsage/Service/AssetUsageSyncServiceFactory.php
  Neos.Neos/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Fusion/Cache/AssetChangeHandlerForCacheFlushing.php
  Neos.Neos/Classes/Service/ImageVariantGarbageCollector.php
  Neos.Neos/Configuration/Settings.ContentRepositoryRegistry.yaml
  Neos.Neos/Migrations/Mysql/Version20240906102606.php
  Neos.Neos/Resources/Private/Partials/Module/Shared/DocumentBreadcrumb.html
  Neos.Neos/Tests/Behavior/Features/AssetUsage/01-NodeCreation/01-CreateNodeAggregateWithNode_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/01-NodeCreation/02-CreateNodeAggregateWithNode_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/02-NodeVariation/01-CreateNodeGeneralizationVariant.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/02-NodeVariation/02-CreateNodeSpecializationVariant.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/02-NodeVariation/03-CreateNodeSpecializationVariant_InternalWorkspace.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/02-NodeVariation/04-CreateNodePeerVariant.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/03-NodeModification/01-SetNodeProperties_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/03-NodeModification/02-SetNodeProperties_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/04-NodeRemoval/01-RemoveNodeAggregate_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/DimensionSpacePoints/01-MoveDimensionSpacePoints.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/Indexing/01-Indexing_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/Indexing/02-Indexing_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W01-WorkspacePublication/01-PublishWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W01-WorkspacePublication/02-PublishWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W01-WorkspacePublication/03-PublishIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W01-WorkspacePublication/04-PublishIndividualNodesFromWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/01-DiscardWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/02-DiscardWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/03-DiscardIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/04-DiscardIndividualNodesFromWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/Bootstrap/AssetUsageTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
Labels: Feature, 9.0

#5268 BUGFIX: Improve performance on find*Aggregates
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/NodeQueryBuilder.php
Labels: Bug, 9.0

#5278 BUGFIX: Prevent augmenter from applying data of multiple nodes into the same element
  Neos.Neos/Classes/Service/ContentElementWrappingService.php
Labels: Bug, 9.0

#5279 FEATURE: Deprecate `WorkspaceFinder` and introduce new API
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/Workspace.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceFinder.php
  Neos.ContentRepository.Core/Classes/Projection/Workspace/Workspaces.php
Labels: Feature, 9.0

#5015 !!! TASK: Remove leftovers from magic underscore access for internal node properties
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/FilterOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PropertyOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/SortByTimestampOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/SortOperation.php
  Neos.ContentRepository.NodeAccess/Tests/Unit/FlowQueryOperations/SortByTimestampOperationTest.php
  Neos.ContentRepository.NodeAccess/Tests/Unit/FlowQueryOperations/SortOperationTest.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
  Neos.Neos/Tests/Unit/FlowQueryOperations/ParentsOperationTest.php
Labels: 9.0

#5283 BUGFIX: Fix workspace role assignment after migration, import and site creation
  Neos.ContentRepository.Core/Classes/Service/ContentRepositoryBootstrapper.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
  Neos.Neos/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Domain/Service/SiteService.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternalsFactory.php
  Neos.Neos/Classes/Domain/Service/WorkspaceService.php
Labels: Bug, 9.0

#4886 BUGFIX: Restore `Neos.Neos:NodeUri`, `neos:link.node` and `LinkingService`
  .composer.json
  .github/workflows/postgresql-versions.yml
  Neos.Neos/Classes/FrontendRouting/NodeUriBuilder.php
  Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
  Neos.Neos/Classes/Fusion/Helper/LinkHelper.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Classes/Fusion/NodeUriImplementation.php
  Neos.Neos/Classes/Service/LinkingService.php
  Neos.Neos/Classes/Utility/LegacyNodePathNormalizer.php
  Neos.Neos/Classes/Utility/NodePathResolver.php
  Neos.Neos/Classes/ViewHelpers/Link/NodeViewHelper.php
  Neos.Neos/Classes/ViewHelpers/Uri/NodeViewHelper.php
  Neos.Neos/Tests/Behavior/Features/Fusion/NodeUri.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/NodeUri.feature.wip
  Neos.Neos/Tests/Behavior/behat.yml.dist
  composer.json
Labels: Bug, 9.0

#5267 TASK: Remove legacy `NodeAddress` and `NodeAddressFactory`
  Neos.Neos/Classes/Controller/Backend/ContentController.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/FrontendRouting/NodeAddress.php
  Neos.Neos/Classes/FrontendRouting/NodeAddressFactory.php
  Neos.Neos/Classes/Routing/NodeIdentityConverterAspect.php
  Neos.Neos/Classes/Service/ContentElementEditableService.php
  Neos.Neos/Classes/Service/ContentElementWrappingService.php
  Neos.Neos/Classes/Service/Controller/DataSourceController.php
  Neos.Neos/Classes/TypeConverter/NodeAddressToStringConverter.php
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
Labels: 9.0, Task

#5290 BUGFIX: Fix admin workspace permissions for workspaces without metadata
  Neos.Neos/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Domain/Service/WorkspaceService.php
  Neos.Neos/Tests/Behavior/Features/ContentRepository/WorkspaceService.feature
Labels: Bug, 9.0

#5289 BUGFIX: Improve error of nearest content collection
  Neos.Neos/Classes/Domain/NodeLabel/DelegatingNodeLabelRenderer.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Classes/Presentation/VisualNodePath.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCollection.feature
Labels: Bug, 9.0

#5286 TASK: Make content repository service internal concept and avoid use in Neos.Neos
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositoryServiceFactoryDependencies.php
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositoryServiceFactoryInterface.php
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositoryServiceInterface.php
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
  Neos.Neos/Classes/Controller/Module/Administration/DimensionController.php
  Neos.Neos/Classes/Controller/Module/Administration/DimensionControllerInternals.php
  Neos.Neos/Classes/Controller/Module/Administration/DimensionControllerInternalsFactory.php
  Neos.Neos/Classes/Controller/Service/ContentDimensionsController.php
  Neos.Neos/Classes/Controller/Service/ContentDimensionsControllerInternals.php
  Neos.Neos/Classes/Controller/Service/ContentDimensionsControllerInternalsFactory.php
  Neos.Neos/Classes/Domain/Service/SiteService.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternalsFactory.php
  Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php
  Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementationInternals.php
  Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementationInternalsFactory.php
  Neos.Neos/Classes/View/FusionExceptionView.php
  Neos.Neos/Classes/View/FusionExceptionViewInternals.php
  Neos.Neos/Classes/View/FusionExceptionViewInternalsFactory.php
Labels: 9.0, Task

#5061 TASK: Remove references to `CommandResult` in return types
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W6-WorkspaceRebasing/03-RebasingWithConflictingChanges.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W7-WorkspacePublication/02-PublishWorkspace.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/04-AllFeaturePublication.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W9-WorkspaceDiscarding/02-DiscardWorkspace.feature
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandResult.php
  Neos.ContentRepository.Core/Classes/CommandHandlingDependencies.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.NodeMigration/src/NodeMigrationService.php
  Neos.ContentRepository.NodeMigration/src/Transformation/AddDimensionShineThroughTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/AddNewPropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/ChangeNodeTypeTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/ChangePropertyValueTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/GlobalTransformationInterface.php
  Neos.ContentRepository.NodeMigration/src/Transformation/MoveDimensionSpacePointTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/NodeAggregateBasedTransformationInterface.php
  Neos.ContentRepository.NodeMigration/src/Transformation/NodeBasedTransformationInterface.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RemoveNodeTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RemovePropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RenameNodeAggregateTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RenamePropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/StripTagsOnPropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/Transformations.php
  Neos.ContentRepository.NodeMigration/src/Transformation/UpdateRootNodeAggregateDimensionsTransformationFactory.php
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
Labels: 9.0, Task

#5306 BUGFIX: Ensure workspace roles and metadata are pruned with the CR.
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Domain/Service/WorkspaceService.php
Labels: Bug, 9.0

#5299 BUGFIX: Remove workspace creation from `EditorContentStreamZookeeper`
  Neos.Neos/Classes/Package.php
  Neos.Neos/Classes/Service/EditorContentStreamZookeeper.php
Labels: Bug, 9.0

#5288 TASK: Cleanup projection catch-up trigger extensibility
  Neos.ContentRepository.BehavioralTests/Classes/Command/PerformanceMeasurementService.php
  Neos.ContentRepository.BehavioralTests/Classes/ProjectionRaceConditionTester/RaceTrackerCatchUpHook.php
  Neos.ContentRepository.Core/Classes/CommandHandler/PendingProjections.php
  Neos.ContentRepository.Core/Classes/CommandHandlingDependencies.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositoryFactory.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionCatchUpTriggerInterface.php
  Neos.ContentRepository.Core/Classes/Projection/WithMarkStaleInterface.php
  Neos.ContentRepository.StructureAdjustment/src/StructureAdjustmentService.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
  Neos.ContentRepositoryRegistry/Classes/Command/SubprocessProjectionCatchUpCommandController.php
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
  Neos.ContentRepositoryRegistry/Classes/Factory/ProjectionCatchUpTrigger/CatchUpTriggerWithSynchronousOption.php
  Neos.ContentRepositoryRegistry/Classes/Factory/ProjectionCatchUpTrigger/ProjectionCatchUpTriggerFactoryInterface.php
  Neos.ContentRepositoryRegistry/Classes/Factory/ProjectionCatchUpTrigger/SubprocessProjectionCatchUpTrigger.php
  Neos.ContentRepositoryRegistry/Classes/Factory/ProjectionCatchUpTrigger/SubprocessProjectionCatchUpTriggerFactory.php
  Neos.ContentRepositoryRegistry/Configuration/Settings.yaml
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
Labels: 9.0, Task

#5309 TASK: Throw `InvalidArgumentException` as `\Throwable` is not caught …
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/01-CreateNodeAggregateWithNode_ConstraintChecks.feature
  Neos.ContentRepository.Core/Tests/Behavior/Fixtures/PostalAddress.php
Labels: 9.0, Task

#5312 BUGFIX: Avoid escaping errors within Gherkin
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/Properties.feature
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Assets.feature
Labels: Bug, 9.0

#5313 TASK: Cosmetic tweak to WorkspaceService
  Neos.Neos/Classes/Command/CrCommandController.php
  Neos.Neos/Classes/Domain/Service/WorkspaceService.php
Labels: 9.0

#5311 FEATURE: convert detail view to fusion
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
  Neos.Workspace.Ui/Configuration/Settings.Neos.yaml
  Neos.Workspace.Ui/Configuration/Views.yaml
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewActions.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewChangeDiff.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewChangeTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewDocumentTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewTable.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/WorkspaceTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Views/Review.fusion
  Neos.Workspace.Ui/Resources/Private/Partials/Workspaces/ContentChangeAttributes.html
  Neos.Workspace.Ui/Resources/Private/Partials/Workspaces/ContentChangeDiff.html
  Neos.Workspace.Ui/Resources/Private/Templates/Workspace/Show.html
  Neos.Workspace.Ui/Resources/Public/Styles/Module.css
Labels: Feature, feature/4255-new-workspace-management-ui

#5182 BUGFIX: show workspace owner/title in media usage tab
  Neos.Media.Browser/Classes/Controller/UsageController.php
  Neos.Media.Browser/Configuration/Policy.yaml
  Neos.Media.Browser/Resources/Private/Templates/Usage/RelatedNodes.html
  Neos.Neos/Configuration/Policy.yaml
Labels: Bug, 8.3

#5295 TASK: Remove deprecations of beta 14
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Event/WorkspaceRebaseFailed.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodePath.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/IdOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/LabelOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/NodeTypeNameOperation.php
  Neos.Neos/Classes/Domain/Model/User.php
  Neos.Neos/Classes/Domain/Model/UserInterface.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCollection.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/Menu.feature
Labels: 9.0, Task

#5319 FEATURE: Add Buttons and Javascript functions for review
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewActions.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewChangeTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewDocumentTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewTable.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Views/Review.fusion
  Neos.Workspace.Ui/Resources/Public/Scripts/Review.js
  Neos.Workspace.Ui/Resources/Public/Styles/Module.css
Labels: Feature, feature/4255-new-workspace-management-ui

#5318 BUGFIX: Prevent projection failure due to missing resource
  Neos.Neos/Classes/AssetUsage/Service/AssetUsageIndexingService.php
Labels: Bug, 9.0

#5323 Feature/redesign review page
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/Presentationals/Button.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewActions.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewChangeDiff.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewChangeTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewDocumentTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewTable.fusion
  Neos.Workspace.Ui/Resources/Private/Translations/en/Main.xlf
  Neos.Workspace.Ui/Resources/Public/Scripts/Review.js
  Neos.Workspace.Ui/Resources/Public/Styles/Module.css
Labels: feature/4255-new-workspace-management-ui

#5322 TASK: Remove migrations in CR setup
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: 9.0, Task

#5274 BUGFIX 4508 mark dependands of live outdated after direct change
  Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphReadModelAdapter.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/ContentStream.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/Workspace.php
  Neos.ContentGraph.PostgreSQLAdapter/src/ContentHyperGraphReadModelAdapter.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W6-WorkspaceRebasing/03-RebasingWithConflictingChanges.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W9-WorkspaceDiscarding/02-DiscardWorkspace.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/WorkspaceState.feature
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphReadModelInterface.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/WorkspaceStatus.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
Labels: 9.0

#5315 TASK: Yield events to publish in workspace command handler
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/01-ForkContentStream_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/02-BasicFeatures.feature
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandBus.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandHandlerInterface.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamClosing/Command/CloseContentStream.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamCreation/Command/CreateContentStream.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamHandling.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamRemoval/Command/RemoveContentStream.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/ContentStreamForking.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/WorkspaceCreation.php
Labels: 9.0, Task

#5324 TASK: Remove PerformanceMeasurementCommand
  Neos.ContentRepository.BehavioralTests/Classes/Command/PerformanceMeasurementCommandController.php
  Neos.ContentRepository.BehavioralTests/Classes/Command/PerformanceMeasurementService.php
  Neos.ContentRepository.BehavioralTests/Classes/Command/PerformanceMeasurementServiceFactory.php
Labels: 9.0, Task

#5326 Feature: Add dto for review
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
  Neos.Workspace.Ui/Classes/ViewModel/ChangeItem.php
  Neos.Workspace.Ui/Classes/ViewModel/ChangeItems.php
  Neos.Workspace.Ui/Classes/ViewModel/ContentChangeItem.php
  Neos.Workspace.Ui/Classes/ViewModel/ContentChangeItems.php
  Neos.Workspace.Ui/Classes/ViewModel/ContentChangeProperties.php
  Neos.Workspace.Ui/Classes/ViewModel/ContentChanges/AssetContentChange.php
  Neos.Workspace.Ui/Classes/ViewModel/ContentChanges/ContentChange.php
  Neos.Workspace.Ui/Classes/ViewModel/ContentChanges/DateTimeContentChange.php
  Neos.Workspace.Ui/Classes/ViewModel/ContentChanges/ImageContentChange.php
  Neos.Workspace.Ui/Classes/ViewModel/ContentChanges/TagContentChange.php
  Neos.Workspace.Ui/Classes/ViewModel/ContentChanges/TextContentChange.php
  Neos.Workspace.Ui/Classes/ViewModel/DocumentChangeItem.php
  Neos.Workspace.Ui/Classes/ViewModel/DocumentItem.php
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewChangeDiff.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewChangeTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/ReviewDocumentTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Components/WorkspaceTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Views/Review.fusion
  Neos.Workspace.Ui/Resources/Private/Translations/en/Main.xlf
  Neos.Workspace.Ui/Resources/Public/Styles/Module.css
Labels: Feature, feature/4255-new-workspace-management-ui

#5296 BUGFIX: Add primary keys and unique indexes on graph projection tables
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
Labels: Bug, 9.0, Task

#5262 FEATURE: Fusion eel neos deprecation tracer
  Neos.Fusion/Classes/Core/EelNeosDeprecationTracer.php
  Neos.Fusion/Classes/Core/Runtime.php
  Neos.Fusion/Configuration/Development/Settings.yaml
  Neos.Fusion/Configuration/Settings.yaml
  Neos.Fusion/Resources/Private/Schema/Settings.Neos.Fusion.schema.yaml
Labels: Feature, 9.0

#5297 BUGFIX: Harden content stream pruner and remove `removed` flag from content streams
  Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphReadModelAdapter.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/ContentStream.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/01-RootNodeCreation/01-CreateRootNodeAggregateWithNode_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/01-CreateNodeAggregateWithNode_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/03-NodeVariation/01-CreateNodeVariant_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/04-NodeModification/01-SetNodeProperties_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/01-SetNodeReferences_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/01-DisableNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/01-RemoveNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/01-MoveNodes_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/09-NodeRenaming/01-ChangeNodeAggregateName_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/11-NodeTypeChange/01-ChangeNodeAggregateType_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamClosing/01-CloseContentStream_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/01-ForkContentStream_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/PruneContentStreams.feature
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandHandlingDependencies.php
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositoryFactory.php
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamClosing/Command/CloseContentStream.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamClosing/Command/ReopenContentStream.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamClosing/Event/ContentStreamWasReopened.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamEventStreamName.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamHandling.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamRemoval/Command/RemoveContentStream.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceEventStreamName.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner/ContentStreamForPruning.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner/ContentStreamStatus.monopic
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner/ContentStreamStatus.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPrunerFactory.php
  Neos.ContentRepository.Core/Classes/Service/WorkspaceMaintenanceService.php
  Neos.ContentRepository.Core/Classes/Service/WorkspaceMaintenanceServiceFactory.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/ContentStream.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/Workspace.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/Workspaces.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/ContentStreamClosing.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentStreamCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/MigrateEventsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
  Neos.Neos/Classes/Command/CrCommandController.php
Labels: Bug, 9.0

#5331 BUGFIX: Change base workspace
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W11-ChangeBaseWorkspace/01-ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W11-ChangeBaseWorkspace/02-BasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W6-WorkspaceRebasing/03-RebasingWithConflictingChanges.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/01-ConstraintChecks.feature
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Command/ChangeBaseWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Command/PublishIndividualNodesFromWorkspace.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/WorkspacePublishing.php
Labels: Bug, 9.0
