Repository neos/neos-development-collection, pull requests merged in 2024-11, with the labels that each got.

#5148 !!! FEATURE: References on creation and Copy
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Projection/ProjectionIntegrityViolationDetection/ReferenceIntegrityIsProvided.feature
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/Feature/NodeReferencing.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/01-SetNodeReferences_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/02-SetNodeReferences_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/03-SetNodeReferences_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/04-SetNodeReferences_PropertyScopes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/05-NodeVariation_After_NodeReferencing.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/02-DisableNodeAggregate_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/03-DisableNodeAggregate_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/05-EnableNodeAggregate_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/06-EnableNodeAggregate_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/02-RemoveNodeAggregate_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/03-RemoveNodeAggregate_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/NodeReferencesOnForkContentStream.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeCopying/CopyNode_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRemoval/RemoveNodeAggregateAfterDisabling.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/References.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/Timestamps.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ProjectionIntegrityViolationDetection/IntactContentGraph.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ProjectionIntegrityViolationDetection/ReferenceIntegrityIsProvided.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/04-AllFeaturePublication.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeReferencingInternals.php
  Neos.ContentRepository.Core/Classes/Feature/Common/TetheredNodeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNode.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNodeAndSerializedProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Event/NodeAggregateWithNodeWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Dto/NodeReferenceSnapshot.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Dto/NodeReferencesSnapshot.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Dto/NodeSubtreeSnapshot.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/NodeDuplicationCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/PropertyScope.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetSerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/NodeReferenceToWrite.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/NodeReferencesForName.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/NodeReferencesToWrite.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/SerializedNodeReference.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/SerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/SerializedNodeReferencesForName.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Event/NodeReferencesWereSet.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/NodeReferencing.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/RootNodeHandling.php
  Neos.ContentRepository.Core/Tests/Unit/Feature/NodeCreation/Event/NodeAggregateWithNodeWasCreatedTest.php
  Neos.ContentRepository.Core/Tests/Unit/Feature/NodeReferencing/Event/NodeReferencesWereSetTest.php
  Neos.ContentRepository.Core/Tests/Unit/Feature/NodeReferencing/NodeReferencesToWriteTest.php
  Neos.ContentRepository.Export/Tests/Behavior/Features/Export/Export.feature
  Neos.ContentRepository.LegacyNodeMigration/Classes/Helpers/SerializedPropertyValuesAndReferences.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/References.feature
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeCreation.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeReferencing.php
  Neos.ContentRepositoryRegistry/Classes/Command/MigrateEventsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
Labels: Feature, 9.0

#5332 FEATURE: Introduce `Workspace::hasPublishableChanges`
  Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphReadModelAdapter.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/ContentStream.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W7-WorkspacePublication/02-PublishWorkspace.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/PublishableToWorkspaceInterface.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamForking/Event/ContentStreamWasForked.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/Workspace.php
  Neos.ContentRepository.NodeMigration/src/NodeMigrationService.php
  Neos.Neos/Classes/Command/WorkspaceCommandController.php
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
  Neos.Workspace.Ui/Resources/Private/Translations/en/Main.xlf
Labels: Feature, 9.0

#5328 !!! TASK: Catchups will only be able to access the state of the projection they are registered for
  Neos.ContentRepository.BehavioralTests/Classes/ProjectionRaceConditionTester/RaceTrackerCatchUpHookFactory.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/Factory/ProjectionsAndCatchUpHooksFactory.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUpHookFactories.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUpHookFactoryDependencies.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUpHookFactoryInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphReadModelInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionsAndCatchUpHooks.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/FlushSubgraphCachePoolCatchUpHookFactory.php
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHook.php
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHookFactory.php
  Neos.Neos/Classes/FrontendRouting/CatchUpHook/RouterCacheHook.php
  Neos.Neos/Classes/FrontendRouting/CatchUpHook/RouterCacheHookFactory.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushingFactory.php
Labels: 9.0

#5261 FEATURE: Speedup content cache flush by using cte in `findAncestorNodeAggregateIds`
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/ProjectionIntegrityViolationDetectionTrait.php
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Projection/ProjectionIntegrityViolationDetection/AllNodesAreConnectedToARootNodePerSubgraph.feature
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/AncestorNodes.feature
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphInterface.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.Neos/Classes/Fusion/Cache/AssetChangeHandlerForCacheFlushing.php
  Neos.Neos/Classes/Fusion/Cache/CacheFlushingStrategy.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
Labels: Feature, 9.0, Task

#5330 FEATURE: Allow mapping of legacy root paths to RootNodeAggregate NodeTypeNames
  Neos.ContentRepository.LegacyNodeMigration/Classes/Command/CrCommandController.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/LegacyMigrationService.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/LegacyMigrationServiceFactory.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/RootNodeTypeMapping.php
  Neos.ContentRepository.LegacyNodeMigration/Configuration/Settings.yaml
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/RootNodeTypeMapping.feature
Labels: Feature, 9.0

#5344 TASK: Fix test parallel
  .composer.json
  .github/workflows/build.yml
  Neos.ContentRepository.BehavioralTests/Configuration/Settings.yaml
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/.gitignore
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/AbstractParallelTestCase.php
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/WorkspaceWritingDuringRebase/WorkspaceWritingDuringRebase.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUp.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Helpers/GherkinTableNodeBasedContentDimensionSource.php
  composer.json
Labels: 9.0, Task

#5354 TASK: Add identifier to custom PHPStan rules
  Neos.ContentRepository.BehavioralTests/Classes/PhpstanRules/ApiOrInternalAnnotationRule.php
  Neos.ContentRepository.BehavioralTests/Classes/PhpstanRules/InternalMethodsNotAllowedOutsideContentRepositoryRule.php
Labels: 9.0, Task

#5355 TASK: Remove `SerializedCommandInterface` again and use `RebasableToO…
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandBus.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandHandlerInterface.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandInterface.php
  Neos.ContentRepository.Core/Classes/CommandHandler/SerializedCommandInterface.php
  Neos.ContentRepository.Core/Classes/Feature/Common/RebasableToOtherWorkspaceInterface.php
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/DimensionSpaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeAggregateCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNodeAndSerializedProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/NodeDuplicationCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Command/SetSerializedNodeProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetSerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/RebaseableCommand.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
Labels: Task, task/serializable-commands

#5357 BUGFIX: Re-introduce stricter checks for subtree en/disabling and tagging
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/01-DisableNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/04-EnableNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/SubtreeTagging/TagSubtree_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/03-MoreBasicFeatures.feature
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandSimulator.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepository.Core/Classes/EventStore/Events.php
  Neos.ContentRepository.Core/Classes/EventStore/EventsToPublish.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Exception/NodeAggregateIsAlreadyDisabled.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Exception/NodeAggregateIsAlreadyEnabled.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/NodeDisabling.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Command/TagSubtree.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Command/UntagSubtree.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Exception/SubtreeIsAlreadyTagged.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Exception/SubtreeIsNotTagged.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/SubtreeTagging.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
Labels: Bug, 9.0

#5361 TASK: Unify command and event dispatching in Behat tests
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/03-CreateNodeAggregateWithNode_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRemoval/RemoveNodeAggregateAfterDisabling.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRemoval/RemoveNodeAggregateWithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/DimensionMismatch.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/Properties.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/TetheredNodesReordering.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W6-WorkspaceRebasing/02-RebasingWithAutoCreatedNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/04-AllFeaturePublication.feature
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandInterface.php
  Neos.ContentRepository.Core/Classes/Feature/Common/RebasableToOtherWorkspaceInterface.php
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/Command/MoveDimensionSpacePoint.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNode.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNodeAndSerializedProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/DisableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/EnableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Command/CopyNodesRecursively.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Command/SetNodeProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Command/SetSerializedNodeProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Command/MoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Dto/RelationDistributionStrategy.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetSerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/Command/RemoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/Command/ChangeNodeAggregateType.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/Command/CreateNodeVariant.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Command/CreateRootNodeAggregateWithNode.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Command/UpdateRootNodeAggregateDimensions.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Command/TagSubtree.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Command/UntagSubtree.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCreation/Command/CreateRootWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCreation/Command/CreateWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Command/ChangeBaseWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Command/DeleteWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Command/DiscardIndividualNodesFromWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Command/DiscardWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Command/PublishIndividualNodesFromWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Command/PublishWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Command/RebaseWorkspace.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteRuntimeVariables.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeCreation.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeDisabling.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeModification.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeMove.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeReferencing.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeRemoval.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeRenaming.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeTypeChange.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeVariation.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/SubtreeTagging.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/WorkspaceCreation.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/WorkspaceDiscarding.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/WorkspacePublishing.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCollection.feature
Labels: 9.0, Task

#5305 TASK: Introduce full behat test for FrontendNodeController
  Neos.Fusion/Classes/Core/FusionSourceCodeCollection.php
  Neos.Neos/Classes/Domain/Service/FusionAutoIncludeHandler.php
  Neos.Neos/Classes/Domain/Service/FusionService.php
  Neos.Neos/Classes/Domain/Service/FusionSourceCodeFactory.php
  Neos.Neos/Classes/Domain/Service/ResourceFusionAutoIncludeHandler.php
  Neos.Neos/Classes/Testing/TestingFusionAutoIncludeHandler.php
  Neos.Neos/Configuration/Objects.yaml
  Neos.Neos/Configuration/Testing/Objects.yaml
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FrontendNodeControllerTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
  Neos.Neos/Tests/Behavior/Features/FrontendNodeController/DefaultFusionRendering.feature
Labels: 9.0, Task

#5348 !!! TASK: Serializable Commands
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/AddNewProperty_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W10-IndividualNodeDiscarding/01-ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W6-WorkspaceRebasing/02-RebasingWithAutoCreatedNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W6-WorkspaceRebasing/03-RebasingWithConflictingChanges.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/01-ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/03-MoreBasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W9-WorkspaceDiscarding/02-DiscardWorkspace.feature
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandBus.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandHandlerInterface.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandInterface.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandSimulator.php
  Neos.ContentRepository.Core/Classes/Feature/Common/RebasableToOtherWorkspaceInterface.php
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/Command/AddDimensionShineThrough.php
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/DimensionSpaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeAggregateCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNodeAndSerializedProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/NodeDuplicationCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Command/SetSerializedNodeProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetSerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRenaming/Command/ChangeNodeAggregateName.php
  Neos.ContentRepository.Core/Classes/Feature/RebaseableCommand.php
  Neos.ContentRepository.Core/Classes/Feature/RebaseableCommands.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/CommandThatFailedDuringRebase.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/ConflictingEvent.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/ConflictingEvents.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Exception/WorkspaceRebaseFailed.php
  Neos.ContentRepository.NodeMigration/src/NodeMigrationServiceFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/AddDimensionShineThroughTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/AddNewPropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/ChangeNodeTypeTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/ChangePropertyValueTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/MoveDimensionSpacePointTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RemoveNodeTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RemovePropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RenameNodeAggregateTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RenamePropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/StripTagsOnPropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/TransformationFactoryInterface.php
  Neos.ContentRepository.NodeMigration/src/Transformation/TransformationsFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/UpdateRootNodeAggregateDimensionsTransformationFactory.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
Labels: 9.0

#5342 BUGFIX: Ensure users content stream is never left closed after publication
  .composer.json
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/AbstractParallelTestCase.php
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/WorkspacePublicationDuringWriting/WorkspacePublicationDuringWritingTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/WorkspaceWritingDuringRebase/WorkspaceWritingDuringRebaseTest.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandBus.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandHandlingDependencies.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/EventStore/EventPersister.php
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamHandling.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
  Neos.Neos/Classes/Domain/Model/UserId.php
  composer.json
Labels: Bug, 9.0

#5362 BUGFIX: Behat: Reset `lastCommandException` once asserted
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/01-DisableNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
Labels: Bug, 9.0

#5367 BUGFIX: Restore asset collection assignment capabilities
  Neos.Media.Browser/Resources/Private/Templates/Asset/Edit.html
Labels: Bug, 8.3

#5363 BUGFIX: Migration to correct order of removed node events
  Neos.ContentRepositoryRegistry/Classes/Command/MigrateEventsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
Labels: Bug, 9.0

#5347 TASK: Improve removal of asset usages on node removal
  Neos.ContentRepository.Export/src/Event/ValueObject/ExportedEvent.php
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHook.php
  Neos.Neos/Classes/AssetUsage/Service/AssetUsageIndexingService.php
Labels: 9.0, Task

#5375 TASK: Radical cleanup for subscription pr to simplify and get into 9.0
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositoryFactory.php
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositorySubscriberFactories.php
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositorySubscriberFactoryInterface.php
  Neos.ContentRepository.Core/Classes/Factory/ProjectionSubscriberFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionEventHandler.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/SubscriptionEngine.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/SubscriptionEngineCriteria.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/SubscriptionManager.php
  Neos.ContentRepository.Core/Classes/Subscription/RetryStrategy/ClockBasedRetryStrategy.php
  Neos.ContentRepository.Core/Classes/Subscription/RetryStrategy/NoRetryStrategy.php
  Neos.ContentRepository.Core/Classes/Subscription/RetryStrategy/RetryStrategy.php
  Neos.ContentRepository.Core/Classes/Subscription/RunMode.php
  Neos.ContentRepository.Core/Classes/Subscription/Store/InMemorySubscriptionStore.php
  Neos.ContentRepository.Core/Classes/Subscription/Store/SubscriptionCriteria.php
  Neos.ContentRepository.Core/Classes/Subscription/Store/SubscriptionStoreInterface.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscriber/EventHandlerInterface.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscriber/ProjectionSubscriber.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscriber/Subscriber.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscriber/Subscribers.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscription.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionGroup.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionGroups.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionStatus.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionStatusFilter.php
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Factory/SubscriptionStore/DoctrineSubscriptionStore.php
Labels: Task, feature/4746-rework-catchup-mechanism-3

#5382 Bugfix: Only reorder `NodeAggregateWasRemoved` events if the node is not recreated afterwards
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
Labels: Bug, 9.0

#5314 FEATURE: Add nodeMove strategy configuration to nodetypes
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Command/MoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeManagerTest.php
  Neos.ContentRepositoryRegistry/Resources/Private/Schema/NodeTypes.schema.yaml
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Documentation/References/NodeTypeDefinition.rst
  Neos.Neos/NodeTypes/Mixin/Document.yaml
Labels: Feature, 9.0

#5378 FEATURE: Introduce `ContentRepositoryMaintainer` and restore projection cli commands
  Neos.ContentRepository.BehavioralTests/Classes/TestSuite/Behavior/CRBehavioralTestsSubjectProvider.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/AbstractSubscriptionEngineTestCase.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/CatchUpHookErrorTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/CatchUpHookTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/ProjectionErrorTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/SubscriptionActiveStatusTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/SubscriptionBootingStatusTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/SubscriptionDetachedStatusTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/SubscriptionGetStatusTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/SubscriptionNewStatusTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/SubscriptionResetTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/SubscriptionSetupTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/AbstractParallelTestCase.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionStatus.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionStatusType.php
  Neos.ContentRepository.Core/Classes/Service/ContentRepositoryMaintainer.php
  Neos.ContentRepository.Core/Classes/Service/ContentRepositoryMaintainerFactory.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner.php
  Neos.ContentRepository.Core/Classes/Service/SubscriptionService.php
  Neos.ContentRepository.Core/Classes/SharedModel/ContentRepository/ContentRepositoryStatus.php
  Neos.ContentRepository.Core/Classes/Subscription/DetachedSubscriptionStatus.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/Error.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/Errors.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/ProcessedResult.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/Result.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/SubscriptionEngine.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/SubscriptionEngineCriteria.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/SubscriptionManager.php
  Neos.ContentRepository.Core/Classes/Subscription/Exception/CatchUpFailed.php
  Neos.ContentRepository.Core/Classes/Subscription/Exception/SubscriptionEngineAlreadyProcessingException.php
  Neos.ContentRepository.Core/Classes/Subscription/ProjectionSubscriptionStatus.php
  Neos.ContentRepository.Core/Classes/Subscription/Store/SubscriptionCriteria.php
  Neos.ContentRepository.Core/Classes/Subscription/Store/SubscriptionStoreInterface.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscriber/ProjectionSubscriber.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscriber/Subscribers.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscription.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionAndProjectionStatuses.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionError.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionId.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionIds.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionStatus.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionStatusCollection.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionStatusFilter.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscriptions.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
  Neos.ContentRepositoryRegistry.TestSuite/Classes/Behavior/CRRegistrySubjectProvider.php
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/SubscriptionCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Processors/ProjectionCatchupProcessor.php
  Neos.ContentRepositoryRegistry/Classes/Processors/SubscriptionReplayProcessor.php
  Neos.ContentRepositoryRegistry/Tests/Functional/ContentRepositoryMaintenanceCommandControllerTest.php
  Neos.Neos/Classes/Domain/Pruning/ContentRepositoryPruningProcessor.php
  Neos.Neos/Classes/Domain/Service/SiteImportService.php
  Neos.Neos/Classes/Domain/Service/SitePruningService.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Basic.feature
  phpstan-baseline.neon
Labels: Feature, feature/4746-rework-catchup-mechanism-3

#5374 BUGFIX: Harden events exporter
  Neos.ContentRepository.Export/Tests/Behavior/Features/Bootstrap/CrImportExportTrait.php
  Neos.ContentRepository.Export/Tests/Behavior/Features/EventExportProcessor.feature
  Neos.ContentRepository.Export/src/Event/ValueObject/ExportedEvent.php
  Neos.ContentRepository.Export/src/Factory/EventStoreImportProcessorFactory.php
  Neos.ContentRepository.Export/src/Processors/EventStoreImportProcessor.php
Labels: Bug, 9.0
