Repository neos/neos-development-collection, pull requests merged in 2024-03, with the labels that each got.

#4902 BUGFIX: `DateTime` node property with `defaultValue`
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/05-CreateNodeAggregateWithNode_ComplexDefaultAndInitialProperties.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/TetheredNodeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/SerializedPropertyValues.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/RootNodeHandling.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/PropertyConverter.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.ContentRepository.Core/Tests/Behavior/Fixtures/PriceSpecification.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/PropertyAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.StructureAdjustment/src/StructureAdjustmentService.php
  Neos.ContentRepository.StructureAdjustment/src/StructureAdjustmentServiceFactory.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeTrait.php
  Neos.ContentRepository.TestSuite/Classes/Unit/NodeSubjectProvider.php
Labels: Bug, 9.0

#4923 BUGFIX: Fix static method call in SiteDetectionResult
  Neos.Neos/Classes/FrontendRouting/SiteDetection/SiteDetectionResult.php
Labels: Bug, 9.0

#4924 TASK: Adjust Code to increased PHPStan level
  Neos.Neos/Classes/Controller/Backend/ModuleController.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Service/ImpersonateService.php
  Neos.Neos/Classes/Service/UserService.php
Labels: 9.0, Task

#4920 DOCS: Fix indentation of ImageEditor options
  Neos.Neos/Documentation/References/PropertyEditorReference.rst
Labels: 8.3

#4361 BUGFIX: Fix too strict grand-parent NodeType constraints
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/06-CreateNodeAggregateWithNode_NodeTypeConstraintChecks.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/NodeAggregateCommandHandler.php
Labels: Bug, 9.0

#4926 BUGFIX: Fix propertyValueCriteriaMatcherTest
  Neos.ContentRepository.Core/Tests/Unit/Projection/ContentGraph/PropertyValue/PropertyValueCriteriaMatcherTest.php
Labels: Bug, 9.0

#4929 FEATURE: Allow `neos/eventstore-doctrineadapter` v2
  Neos.ContentRepository.Core/composer.json
Labels: Feature, 9.0

#4927 TASK: Reimplement ContentCacheFlush DebugMode and performance improvement
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Labels: 9.0, Task

#4919 TASK: Declare fusion core classes as internal
  Neos.Fusion.Afx/Classes/Dsl/AfxDslImplementation.php
  Neos.Fusion/Classes/Core/DslFactory.php
  Neos.Fusion/Classes/Core/DslInterface.php
  Neos.Fusion/Classes/Core/FusionConfiguration.php
  Neos.Fusion/Classes/Core/FusionSourceCode.php
  Neos.Fusion/Classes/Core/FusionSourceCodeCollection.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/AbstractNode.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/AbstractOperation.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/AbstractPathSegment.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/AbstractPathValue.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/AbstractStatement.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/AssignedObjectPath.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/Block.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/BoolValue.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/DslExpressionValue.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/EelExpressionValue.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/FloatValue.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/FusionFile.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/FusionObjectValue.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/IncludeStatement.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/IntValue.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/MetaPathSegment.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/NullValue.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/ObjectPath.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/ObjectStatement.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/PathSegment.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/PrototypePathSegment.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/StatementList.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/StringValue.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/ValueAssignment.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/ValueCopy.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Ast/ValueUnset.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/AstNodeVisitorInterface.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Exception/ParserException.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Exception/ParserUnexpectedCharException.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/ExceptionMessage/MessageCreator.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/ExceptionMessage/MessageLinePart.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/FilePatternResolver.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Lexer.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/MergedArrayTree.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/MergedArrayTreeVisitor.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/ObjectTreeParser.php
  Neos.Fusion/Classes/Core/ObjectTreeParser/Token.php
  Neos.Fusion/Classes/Core/Parser.php
  Neos.Fusion/Classes/Core/Runtime.php
  Neos.Fusion/Classes/Core/RuntimeConfiguration.php
  Neos.Fusion/Classes/Core/RuntimeFactory.php
  Neos.Fusion/Tests/Functional/Parser/Fixtures/Dsl/FusionObjectExpressionTestDslImplementation.php
  Neos.Fusion/Tests/Functional/Parser/Fixtures/Dsl/PassthroughTestDslImplementation.php
  Neos.Neos/Classes/Domain/Service/FusionService.php
  Neos.Neos/Classes/Domain/Service/FusionSourceCodeFactory.php
Labels: 9.0, Task

#4932 BUGFIX: Reset workspace state to `OUTDATED` after discard
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/WorkspacePublishing/WorkspaceBasedContentPublishing.feature
  Neos.ContentRepository.Core/Classes/Projection/Workspace/WorkspaceProjection.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
  Neos.Neos/Classes/Command/WorkspaceCommandController.php
Labels: Bug, 9.0

#4936 TASK: Prevent TimeableNodeVisibility tests to fail in 5 years
  Neos.TimeableNodeVisibility/Tests/Behavior/Features/HandleExceeded.feature
Labels: 9.0, Task

#4931 BUGFIX: Evaluate language dimension when rendering nodes.
  Neos.Neos/Classes/View/FusionView.php
Labels: Bug, 9.0

#4934 FEATURE: move user menu to left drawer
  Neos.Neos/Readme.rst
  Neos.Neos/Resources/Private/Partials/Backend/Menu.html
  Neos.Neos/Resources/Private/Partials/Backend/UserImage.html
  Neos.Neos/Resources/Private/Partials/Backend/UserMenu.html
  Neos.Neos/Resources/Private/Styles/Lite.scss
  Neos.Neos/Resources/Private/Styles/Main.scss
  Neos.Neos/Resources/Private/Styles/Menu/_MenuPanel.scss
  Neos.Neos/Resources/Private/Styles/Menu/_UserMenu.scss
  Neos.Neos/Resources/Private/Styles/Minimal.scss
  Neos.Neos/Resources/Private/Styles/TopBar/_TopBar.scss
  Neos.Neos/Resources/Private/Styles/TopBar/_UserMenu.scss
  Neos.Neos/Resources/Private/Templates/Backend/Module/Index.html
  Neos.Neos/Resources/Public/JavaScript/Components/TopBar/index.ts
  Neos.Neos/Resources/Public/JavaScript/Components/UserMenu.js
  Neos.Neos/Resources/Public/JavaScript/Main.min.js
  Neos.Neos/Resources/Public/JavaScript/Main.min.js.map
  Neos.Neos/Resources/Public/JavaScript/index.js
  Neos.Neos/Resources/Public/Styles/Lite.css
  Neos.Neos/Resources/Public/Styles/Lite.css.map
  Neos.Neos/Resources/Public/Styles/Main.css
  Neos.Neos/Resources/Public/Styles/Main.css.map
  Neos.Neos/Resources/Public/Styles/Minimal.css
  Neos.Neos/Resources/Public/Styles/Minimal.css.map
Labels: Feature, 9.0

#4890 TASK: Workspace aware commands events migration
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/01-SetNodeReferences_ConstraintChecks.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/Common/ContentStreamIdOverride.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNodeAndSerializedProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/DisableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/EnableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Command/CopyNodesRecursively.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Command/SetSerializedNodeProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Command/MoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetSerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/Command/RemoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRenaming/Command/ChangeNodeAggregateName.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/Command/ChangeNodeAggregateType.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/Command/CreateNodeVariant.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Dto/NodeIdToPublishOrDiscard.php
  Neos.ContentRepositoryRegistry/Classes/Command/MigrateEventsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
Labels: 9.0, Task

#4940 FEATURE: Use CacheTag to generate cache tags and add ContentRepositoryId to cache tag
  Neos.Fusion/Classes/Core/Cache/RuntimeContentCache.php
  Neos.Fusion/Classes/Core/Runtime.php
  Neos.Neos/Classes/Fusion/Cache/CacheTag.php
  Neos.Neos/Classes/Fusion/Cache/CacheTagSet.php
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
  Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
  Neos.Neos/Classes/Fusion/Helper/CachingHelper.php
  Neos.Neos/Tests/Unit/Fusion/ConvertUrisImplementationTest.php
  Neos.Neos/Tests/Unit/Fusion/Helper/CachingHelperTest.php
Labels: Feature, 9.0

#4941 TASK: Pass ContentStreamId to NodeFactory
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
Labels: 9.0, Task

#4946 TASK: Tweak composer scripts
  .composer.json
  .github/workflows/build.yml
  Readme.rst
  composer.json
  phpcs.xml.dist
Labels: 9.0, Task

#4947 TASK: Document `ContentRepositoryRegistry::get`
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
Labels: 9.0, Task

#4790 Split dimensionspacepoints into separate table to reduce data duplication
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/ProjectionIntegrityViolationDetectionTrait.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjectionFactory.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/HierarchyRelation.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/NodeRecord.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/ProjectionIntegrityViolationDetector.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/DimensionSpacePointsRepository.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php
Labels: 9.0

#4962 BUGFIX: Fix argument order of implode()
  Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
Labels: Bug, 8.3

#4954 !!! TASK: Forgiving node type manager
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/Common/TetheredNodeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Dto/NodeAggregateIdsByNodePaths.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeManager.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeManagerTest.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToAssetsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DimensionAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DisallowedChildNodeAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/PropertyAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/NodeTypesCommandController.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
  Neos.Neos/Classes/Utility/NodeTypeWithFallbackProvider.php
Labels: 9.0
