Repository neos/neos-development-collection, pull requests merged in 2024-04, with the labels that each got.

#4967 TASK: remove obsolete contentStreamId argument for commands in behat
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/01-CreateNodeAggregateWithNode_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/03-NodeVariation/02-CreateNodeSpecializationVariant.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/03-NodeVariation/03-CreateNodeGeneralizationVariant.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/03-NodeVariation/04-CreateNodePeerVariant.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/04-NodeModification/02-SetNodeProperties.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/04-NodeModification/03-SetNodeProperties_PropertyScopes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/04-SetNodeReferences_PropertyScopes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/NodeReferencesOnForkContentStream.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/AddNewProperty_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeCopying/CopyNode_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRetyping/ChangeNodeAggregateType_HappyPathStrategy.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/ChildNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/DescendantNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/Timestamps.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/TetheredNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/SubtreeTagging/TagSubtree_WithoutDimensions.feature
Labels: 9.0, Task

#4971 BUGFIX: Throw explicit transaction has been marked for rollback only exception
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalCheckpointStorage.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUp.php
Labels: Bug, 9.0

#4952 TASK: Export event cleanup and error handling for catchupd events
  Neos.ContentRepository.Core/Classes/EventStore/EventNormalizer.php
  Neos.ContentRepository.Core/Classes/Projection/CatchUp.php
  Neos.ContentRepository.Export/src/Event/ValueObject/ExportedEvent.php
Labels: 9.0, Task

#4974 Task/publishing bonanza review
  Neos.Neos/Classes/Domain/Workspace/Workspace.php
  Neos.Neos/Classes/Domain/Workspace/WorkspaceFactory.php
Labels: publishingBonanza

#4961 BUGFIX: #4742 - Interdimensional relatives
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/NodeVariation.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/Feature/NodeCreation.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/Feature/NodeVariation.php
  Neos.ContentRepository.BehavioralTests/Classes/Command/PerformanceMeasurementService.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/01-RootNodeCreation/03-CreateRootNodeAggregateWithNodeAndTetheredChildren_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/01-RootNodeCreation/04-CreateRootNodeAggregateWithNodeAndTetheredChildren_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/03-CreateNodeAggregateWithNode_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/04-CreateNodeAggregateWithNode_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/03-NodeVariation/02-CreateNodeSpecializationVariant.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/03-NodeVariation/03-CreateNodeGeneralizationVariant.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/03-NodeVariation/04-CreateNodePeerVariant.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/03-RemoveNodeAggregate_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/05-CreateNodeAfterDeletion.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/06-CreateNodeSpecializationVariantAfterDeletion.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/InterdimensionalSibling.php
  Neos.ContentRepository.Core/Classes/Feature/Common/InterdimensionalSiblings.php
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeCreationInternals.php
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeVariationInternals.php
  Neos.ContentRepository.Core/Classes/Feature/Common/TetheredNodeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Event/NodeAggregateWithNodeWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/NodeDuplicationCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/Event/NodeGeneralizationVariantWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/Event/NodePeerVariantWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/Event/NodeSpecializationVariantWasCreated.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/RootNodeHandling.php
  Neos.ContentRepository.Export/Tests/Behavior/Features/Export/Export.feature
  Neos.ContentRepository.Export/Tests/Behavior/Features/Import/Import.feature
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Variants.feature
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeCreation.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeVariation.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeAggregateTrait.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
Labels: Bug, 9.0

#4943 Highlevel Workspace API
  Neos.Neos/Classes/Command/WorkspaceCommandController.php
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
  Neos.Neos/Classes/Domain/Workspace/DiscardAllChanges.php
  Neos.Neos/Classes/Domain/Workspace/DiscardingResult.php
  Neos.Neos/Classes/Domain/Workspace/PublishAllChanges.php
  Neos.Neos/Classes/Domain/Workspace/PublishingResult.php
  Neos.Neos/Classes/Domain/Workspace/Workspace.php
  Neos.Neos/Classes/Domain/Workspace/WorkspaceProvider.php
Labels: 9.0

#4976 TASK: 4942 - refactor global transformation commands…
  Neos.ContentRepository.Core/Classes/Feature/Common/RebasableToOtherWorkspaceInterface.php
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/Command/AddDimensionShineThrough.php
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/Command/MoveDimensionSpacePoint.php
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/DimensionSpaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNodeAndSerializedProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/DisableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/EnableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Command/CopyNodesRecursively.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Command/SetSerializedNodeProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Command/MoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetSerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/Command/RemoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRenaming/Command/ChangeNodeAggregateName.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/Command/ChangeNodeAggregateType.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/Command/CreateNodeVariant.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Command/CreateRootNodeAggregateWithNode.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/Command/UpdateRootNodeAggregateDimensions.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Command/TagSubtree.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Command/UntagSubtree.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.NodeMigration/src/NodeMigrationService.php
  Neos.ContentRepository.NodeMigration/src/Transformation/AddDimensionShineThroughTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/GlobalTransformationInterface.php
  Neos.ContentRepository.NodeMigration/src/Transformation/MoveDimensionSpacePointTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/Transformations.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentCommandController.php
Labels: 9.0, Task

#4677 !!! FEATURE: Separate properties from references in NodeType declaration
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/01-SetNodeReferences_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/05-NodeReferencing/02-SetNodeReferences_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodeById.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodeByPath.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodeByPathAsNodeName.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindParentNode.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/References.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/SiblingNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/Timestamps.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/NodeReferencesToWrite.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Dto/SerializedNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/NodeReferencing.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/PropertyConverter.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/PropertyType.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeType.php
  Neos.ContentRepository.Core/Classes/NodeType/NodeTypeManager.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/References.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/PropertyTypeIsInvalid.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/ReferenceCannotBeSet.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeManagerTest.php
  Neos.ContentRepository.Core/Tests/Unit/NodeType/NodeTypeTest.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PropertyOperation.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/NodeTypePostprocessor/DefaultPropertyEditorPostprocessor.php
  Neos.Neos/Classes/Service/Mapping/NodeReferenceConverter.php
  Neos.Neos/Classes/Service/Mapping/NodeTypeStringConverter.php
  Neos.Neos/Classes/Service/NodeTypeSchemaBuilder.php
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/Tests/Unit/NodeTypePostprocessor/DefaultPropertyEditorPostprocessorTest.php
Labels: 9.0

#4945 BUGFIX: Strip image to prevent wrong orientation information in exif data
  Neos.Media/Classes/Domain/Service/ImageService.php
Labels: Bug, 8.3

#4965 Rebase failed exception
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W9-WorkspaceDiscarding/02-DiscardWorkspace.feature
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/CommandThatFailedDuringRebase.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/CommandsThatFailedDuringRebase.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Event/WorkspaceRebaseFailed.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Exception/WorkspaceRebaseFailed.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/WorkspaceRebaseStatistics.php
  Neos.ContentRepository.Core/Classes/Service/WorkspaceMaintenanceService.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/WorkspaceCreation.php
  Neos.Neos/Classes/Command/WorkspaceCommandController.php
  Neos.Neos/Classes/Domain/Workspace/Workspace.php
  Neos.Neos/Classes/Domain/Workspace/WorkspaceProvider.php
  Neos.Neos/Classes/Service/EditorContentStreamZookeeper.php
Labels: 9.0

#4985 BUGFIX: Make text formatting visible in raw content mode
  Neos.Neos/Resources/Private/Fusion/RawContent/Document.fusion
  Neos.Neos/Resources/Private/Styles/RawContentMode.scss
  Neos.Neos/Resources/Public/Styles/RawContentMode.css
  Neos.Neos/Resources/Public/Styles/RawContentMode.css.map
  Neos.Neos/package.json
Labels: Bug, 8.3

#4986 BUGFIX: Remove br from role tooltip and improve readability
  Neos.Neos/Resources/Private/Partials/Module/Shared/Roles.html
Labels: Bug, 8.3

#5001 BUGFIX: Fix the check for RedirectStorageInterface
  Neos.Media/Classes/Domain/Service/AssetService.php
Labels: Bug, 8.3

#5003 TASK: Update plupload library to latest 2.3.9
  Neos.Media.Browser/Resources/Public/Libraries/plupload/jquery.plupload.queue/jquery.plupload.queue.js
  Neos.Media.Browser/Resources/Public/Libraries/plupload/jquery.plupload.queue/jquery.plupload.queue.min.js
  Neos.Media.Browser/Resources/Public/Libraries/plupload/jquery.ui.plupload/jquery.ui.plupload.js
  Neos.Media.Browser/Resources/Public/Libraries/plupload/jquery.ui.plupload/jquery.ui.plupload.min.js
  Neos.Media.Browser/Resources/Public/Libraries/plupload/plupload.full.min.js
Labels: 8.3, Task

#5004 TASK: Update plupload library to latest 2.3.9
  Neos.Media.Browser/Resources/Public/Libraries/plupload/jquery.plupload.queue/jquery.plupload.queue.js
  Neos.Media.Browser/Resources/Public/Libraries/plupload/jquery.plupload.queue/jquery.plupload.queue.min.js
  Neos.Media.Browser/Resources/Public/Libraries/plupload/jquery.ui.plupload/jquery.ui.plupload.js
  Neos.Media.Browser/Resources/Public/Libraries/plupload/jquery.ui.plupload/jquery.ui.plupload.min.js
  Neos.Media.Browser/Resources/Public/Libraries/plupload/plupload.full.min.js
Labels: Task, 7.3

#5009 !!! BUGFIX: Fix schema of hierarchy relation table
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphSchemaBuilder.php
Labels: Bug, 9.0

#4856 !!! FEATURE: Render `ResponseInterface` directly in Fusion Views
  Neos.Fusion/Classes/Core/Cache/FusionContextSerializer.php
  Neos.Fusion/Classes/Core/FusionGlobals.php
  Neos.Fusion/Classes/Core/IllegalEntryFusionPathValueException.php
  Neos.Fusion/Classes/Core/LegacyFusionControllerContext.php
  Neos.Fusion/Classes/Core/Runtime.php
  Neos.Fusion/Classes/Core/RuntimeFactory.php
  Neos.Fusion/Classes/Exception/RuntimeException.php
  Neos.Fusion/Classes/FusionObjects/ResourceUriImplementation.php
  Neos.Fusion/Classes/FusionObjects/TemplateImplementation.php
  Neos.Fusion/Classes/FusionObjects/UriBuilderImplementation.php
  Neos.Fusion/Classes/View/FusionView.php
  Neos.Fusion/Tests/Functional/FusionObjects/AbstractFusionObjectTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/ContentCacheTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/ReservedKeysTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/TestingViewForFusionRuntime.php
  Neos.Fusion/Tests/Functional/View/Fixtures/Fusion/HttpResponse.fusion
  Neos.Fusion/Tests/Functional/View/Fixtures/Fusion/IllegalEntryPointValue.fusion
  Neos.Fusion/Tests/Functional/View/Fixtures/Fusion/Root.fusion
  Neos.Fusion/Tests/Functional/View/FusionViewTest.php
  Neos.Fusion/Tests/Unit/Core/RuntimeTest.php
  Neos.Fusion/Tests/Unit/FusionObjects/ResourceUriImplementationTest.php
  Neos.Neos/Classes/Fusion/Cache/NeosFusionContextSerializer.php
  Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
  Neos.Neos/Classes/Fusion/ExceptionHandlers/PageHandler.php
  Neos.Neos/Classes/Fusion/ImageUriImplementation.php
  Neos.Neos/Classes/Fusion/NodeUriImplementation.php
  Neos.Neos/Classes/Fusion/PluginImplementation.php
  Neos.Neos/Classes/View/FusionExceptionView.php
  Neos.Neos/Classes/View/FusionView.php
  Neos.Neos/Classes/View/Service/AssetJsonView.php
  Neos.Neos/Classes/View/Service/NodeJsonView.php
  Neos.Neos/Classes/View/Service/WorkspaceJsonView.php
  Neos.Neos/Classes/ViewHelpers/StandaloneViewViewHelper.php
  Neos.Neos/Tests/Functional/Fusion/NodeHelperTest.php
  Neos.Neos/Tests/Unit/Fusion/PluginImplementationTest.php
Labels: Feature, 9.0

#5010 FEATURE: Improved CLI output for projection replay
  Neos.ContentRepository.Core/Classes/Projection/Projections.php
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Service/ProjectionReplayService.php
  Neos.ContentRepositoryRegistry/Classes/Service/ProjectionReplayServiceFactory.php
Labels: Feature, 9.0

#4975 BUGFIX: 4742 - document uri path projection adjustments
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentNodeInfo.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathFinder.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/NodeCreationEdgeCases.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/NodeVariationEdgeCases.feature
Labels: Bug, 9.0

#4982 BUGFIX: Enforce unique names also for root children
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/01-CreateNodeAggregateWithNode_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/02-NodeCreation/02-CreateNodeAggregateWithNode_ConstraintChecks_WithDimensions.feature
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/NodeDuplicationCommandHandler.php
Labels: Bug, 9.0

#4966 BUGFIX: Catch not completely covered node aggregates
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DimensionAdjustment.php
Labels: Bug, 9.0

#5007 BUGFIX: Add missing type converts for asset subtypes
  Neos.Neos/Configuration/Settings.yaml
Labels: Bug, 8.3

#5017 TASK: set new-password in EditAccount page
  Neos.Neos/Resources/Private/Partials/Module/Shared/EditAccount.html
  Neos.Neos/Resources/Private/Templates/Module/Administration/Users/New.html
Labels: 8.3, Task

#5014 TASK: Allow to enable Fusion caching for Behat tests
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FusionTrait.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCache.feature
Labels: Feature, 9.0, Task

#4735 FEATURE: Site configuration presets
  Neos.Neos/Classes/Domain/Model/Site.php
  Neos.Neos/Configuration/Settings.Sites.yaml
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/Migrations/Code/Version20230801154834.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Basic.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Dimensions.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/DisableNodes.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/MultiSiteLinking.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/RouteCache.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Shortcuts.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/TetheredSiteChildDocuments.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCase.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCollection.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/ConvertUris.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/Menu.feature
  Neos.Neos/Tests/Unit/Domain/Model/SiteTest.php
Labels: Feature, 9.0

#4993 TASK: Interdimensional relatives for node move
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Projection/SiblingPositions.feature
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/NodeMove.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/NodeRecord.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/01-MoveNodes_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/02-MoveNodeAggregate_NoNewParent_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/03-MoveNodeAggregate_NewParent_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/04-MoveNodeAggregate_ScatteredChildren.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/05-MoveNodeAggregate_SubtreeTags.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/06-AdditionalConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/07-MoveNodeAggregateWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/MoveNodeAggregate.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/MoveNodeAggregateConsideringDisableStateWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/MoveNodeAggregate_NewParent_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/08-NodeMove/MoveNodeAggregate_NoNewParent_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ProjectionIntegrityViolationDetection/AllNodesAreConnectedToARootNodePerSubgraph.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Dto/CoverageNodeMoveMapping.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Dto/CoverageNodeMoveMappings.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Dto/OriginNodeMoveMapping.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Dto/OriginNodeMoveMappings.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Dto/ParentNodeMoveDestination.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Dto/SucceedingSiblingNodeMoveDestination.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Event/NodeAggregateWasMoved.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/NodeMove.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Nodes.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/NodeAggregateIsNoChild.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/NodeAggregateIsNoSibling.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/Variants.feature
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeTrait.php
  Neos.Neos/Classes/FrontendRouting/CatchUpHook/RouterCacheHook.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: 9.0, Task
