Repository neos/neos-development-collection, pull requests merged in 2024-07, with the labels that each got.

#5068 !!! TASK: Refactor `Node` property mapper to use new NodeAddress
  Neos.Neos/Classes/Controller/Backend/ContentController.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/FrontendRouting/NodeAddress.php
  Neos.Neos/Classes/FrontendRouting/NodeAddressFactory.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Classes/Service/Controller/DataSourceController.php
  Neos.Neos/Classes/Service/LinkingService.php
  Neos.Neos/Classes/TypeConverter/NodeAddressToNodeConverter.php
  Neos.Neos/Classes/TypeConverter/NodeToNodeAddressStringConverter.php
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
  phpstan.neon.dist
Labels: 9.0

#5156 FEATURE: Separate properties and references in Neos UI
  Neos.ContentRepositoryRegistry/Classes/Configuration/NodeTypeEnrichmentService.php
  Neos.ContentRepositoryRegistry/Tests/Unit/Configuration/NodeTypeEnrichmentServiceTest.php
  Neos.Neos/Classes/Service/NodeTypeSchemaBuilder.php
Labels: Feature, 9.0

#5021 !!! TASK: Remove `Node::nodeType`
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjectionFactory.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/HypergraphProjectionFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/PropertyAdjustment.php
  Neos.ContentRepository.TestSuite/Classes/Unit/NodeSubjectProvider.php
  Neos.Neos/Classes/Domain/NodeLabel/ExpressionBasedNodeLabelGenerator.php
  Neos.Neos/Classes/Utility/NodeTypeWithFallbackProvider.php
  Neos.Neos/Resources/Private/Fusion/RawContent/NodeHeader.fusion
  Neos.Neos/Resources/Private/Fusion/RawContent/NodeProperties.fusion
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCollection.feature
  Neos.Neos/Tests/Unit/Fusion/Helper/CachingHelperTest.php
Labels: 9.0

#5172 BUGFIX Disable uriPathSegment Validation on Hompage
  Neos.Neos/NodeTypes/Mixin/Site.yaml
Labels: 9.0

#5170 TASK: Update textarea docs to latest version
  Neos.Neos/Documentation/References/PropertyEditorReference.rst
Labels: Task, 8.4

#5174 FEATURE: Support doctrine/dbal 2.x and 3.x
  Neos.ContentRepository/Classes/Domain/Service/ImportExport/NodeImportService.php
  Neos.Media/composer.json
  composer.json
Labels: Feature, 8.4

#5082 !!! TASK: Deprecate setting NodeNames via cr commands
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNode.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNodeAndSerializedProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Command/CopyNodesRecursively.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRenaming/Command/ChangeNodeAggregateName.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeCopying.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Features/NodeCreation.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
Labels: 9.0

#5157 TASK: Use collection value objects in content graph instead of `iterable`
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphInterface.php
Labels: 9.0, Task

#5173 BUGFIX: Improve output of `PropertyCannotBeSet` exception
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
Labels: Bug, 9.0

#5153 !!! TASK: streamline `NodeReferencesWereSet::$nodeAggregateId`
  Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Projection/Feature/NodeReferencing.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Event/NodeReferencesWereSet.php
  Neos.ContentRepository.Core/Tests/Unit/Feature/NodeCreation/Event/NodeAggregateWithNodeWasCreatedTest.php
  Neos.ContentRepository.Core/Tests/Unit/Feature/NodeMove/Event/NodeAggregateWasMovedTest.php
  Neos.ContentRepository.Core/Tests/Unit/Feature/NodeReferencing/Event/NodeReferencesWereSetTest.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/References.feature
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
Labels: 9.0

#5179 BUGFIX: Forward status codes and headers set in module actions
  Neos.Neos/Classes/Controller/Backend/ModuleController.php
Labels: Bug, 8.3

#5169 TASK: 5034 fully completely workspace aware behat tests
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/ForkContentStreamWithDisabledNodesWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/ForkContentStreamWithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/ContentStreamForking/NodeReferencesOnForkContentStream.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/MoveDimensionSpacePoint.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/04-AllFeaturePublication.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/PruneContentStreams.feature
  Neos.ContentRepository.Core/Classes/ContentGraphFinder.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamClosing/Command/CloseContentStream.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamClosing/Command/ReopenContentStream.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamCreation/Command/CreateContentStream.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamForking/Command/ForkContentStream.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamRemoval/Command/RemoveContentStream.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteRuntimeVariables.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Helpers/NodeDiscriminator.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Helpers/NodeDiscriminators.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeTrait.php
  Neos.Neos/Tests/Behavior/Features/Fusion/ConvertUris.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
Labels: 9.0, Task

#5184 BUGFIX: Change workspace runs into endless while-loop
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
Labels: Bug, 9.0

#5168 TASK: Remove deprecated beta10 apis
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandResult.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphIdentity.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Node.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeAggregate.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ClosestOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/NextAllOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/NextOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/NextUntilOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ParentOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ParentsUntilOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PrevAllOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PrevOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PrevUntilOperation.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/SiblingsOperation.php
  Neos.ContentRepository.TestSuite/Classes/Unit/NodeSubjectProvider.php
  Neos.Neos/Classes/Domain/Repository/SiteRepository.php
  Neos.Neos/Classes/Service/ImageVariantGarbageCollector.php
  Neos.Neos/Resources/Private/Fusion/Backend/Views/Login.fusion
  Neos.Neos/Resources/Private/Templates/Service/Nodes/Index.html
  Neos.Neos/Resources/Private/Templates/Service/Nodes/Show.html
  Neos.Neos/Tests/Behavior/Features/Fusion/ContentCollection.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/Menu.feature
  Neos.Neos/Tests/Functional/Fusion/NodeHelperTest.php
  Neos.Neos/Tests/Unit/Fusion/Helper/CachingHelperTest.php
  Neos.Workspace.Ui/Resources/Private/Templates/Workspace/Show.html
Labels: 9.0, Task

#5158 !!! TASK: Streamline `ContentGraph::findRootNodeAggregateByType`
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphInterface.php
  Neos.ContentRepository.Core/Classes/Service/ContentRepositoryBootstrapper.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/RootNodeAggregateDoesNotExist.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
  Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
  Neos.Neos/Classes/Domain/Service/SiteNodeUtility.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.TimeableNodeVisibility/Classes/Service/TimeableNodeVisibilityService.php
Labels: 9.0

#5078 Implement document uri path placeholders
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentTypeClassification.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathFinder.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathSchemaBuilder.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/NodeAggregateTypeChangeEdgeCases.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/UnknownNodeTypes.feature
Labels: 9.0
