Repository neos/neos-development-collection, pull requests merged in 2025-02, with the labels that each got.

#5464 TASK: Update pipeline OS to latest ubuntu
  .github/workflows/build.yml
Labels: 9.0, Task

#5465 TASK: Update github actions to checkout@v4 and cache@v4
  .github/workflows/add-pr-labels.yml
  .github/workflows/build.yml
  .github/workflows/doctum.yml
Labels: Task, 7.3

#5467 TASK: Adjust to removed package freezing API's
  Neos.ContentRepositoryRegistry/Classes/Package.php
  Neos.Fusion/Classes/Package.php
  Neos.Neos/Classes/Controller/Module/Administration/PackagesController.php
  Neos.Neos/Resources/Private/Templates/Module/Administration/Packages/Index.html
  Neos.Neos/Resources/Private/Translations/en/Modules.xlf
Labels: 9.0, Task

#5453 TASK: Followup #5371 remove legacy `CopyNodesRecursively` command
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositoryFactory.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Command/CopyNodesRecursively.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/Dto/NodeSubtreeSnapshot.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDuplication/NodeDuplicationCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/RebaseableCommands.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
  Neos.Neos/Classes/Domain/Service/NodeDuplication/NodeAggregateIdMapping.php
Labels: 9.0, Task

#5304 BUGFIX: 4909 fusion plugins and tests
  Neos.Fusion/Classes/Core/Runtime.php
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/BehatRuntimeActionController.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FrontendNodeControllerTrait.php
  Neos.Neos/Tests/Behavior/Features/FrontendNodeController/DefaultFusionRendering.feature
  Neos.Neos/Tests/Behavior/Features/FrontendNodeController/FusionPlugin.feature
Labels: Bug, 9.0

#4969 BUGFIX: Fix and test tethered node structure adjustment
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/TetheredNodes.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/TetheredNodeInternals.php
Labels: Bug, 9.0, Task

#5472 BUGFIX: Replace node identity converter aspect with `NeosRouteValueNormalizer`
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
  Neos.Neos/Classes/Routing/NeosRouteValueNormalizer.php
  Neos.Neos/Classes/Routing/NodeIdentityConverterAspect.php
  Neos.Neos/Configuration/Objects.yaml
  Neos.Neos/Tests/Behavior/Features/Fusion/ActionUriWithNode.feature
Labels: Bug, 9.0

#5091 BUGFIX: Build URI path based on parent from "target" dimensionSpacePoint
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentNodeInfo.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/NodeVariationEdgeCases.feature
Labels: Bug, 9.0

#5458 TASK: Add debug information to identify original event after rebase
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandSimulator.php
Labels: 9.0, Task

#5473 BUGFIX - Decouple CR Registry from BehavioralTests
  Neos.ContentRepository.BehavioralTests/Tests/Functional/ContentRepositoryMaintenanceCommandControllerTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/AbstractSubscriptionEngineTestCase.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/ProjectionErrorTest.php
Labels: 9.0

#5474 TASK: Rename --level to --depth
  Neos.ContentRepositoryRegistry/Classes/Command/NodeTypesCommandController.php
Labels: 9.0, Task

#5476 FEATURE: Make adjustments for missing tethered nodes recursive
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/MissingTetheredNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/StructureAdjustment/TetheredNodes.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/TetheredNodeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/NodeTypeChange.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/StructureAdjustmentsTrait.php
Labels: Feature, 9.0

#5481 TASK: Followup 4969 remove duplicate peer creations
  Neos.ContentRepositoryRegistry/Classes/Command/MigrateEventsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
Labels: 9.0, Task

#5454 FEATURE: Workspace UI - Add second confirmation window for rebasing
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
  Neos.Workspace.Ui/Resources/Private/Fusion/Features/Workspace/Actions/Rebase.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Features/Workspace/Actions/RebaseConfirm.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Features/Workspace/Modals/Rebase.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Features/Workspace/Modals/RebaseConfirm.fusion
  Neos.Workspace.Ui/Resources/Private/Translations/en/Main.xlf
  Neos.Workspace.Ui/Resources/Public/Styles/Module.css
Labels: Feature, 9.0

#5482 FEATURE: Fetch multiple nodes or node aggregates
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentSubhypergraph.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/FindNodeById.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/NodeDisabling.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/NodeMove.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/NodeRemoval.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/NodeTypeChange.php
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/NodeVariation.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/RootNodeHandling.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphInterface.php
  Neos.ContentRepository.Core/Classes/SharedModel/Exception/NodeAggregatesTypeIsAmbiguous.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeAggregateTrait.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/ContentSubgraphWithRuntimeCaches.php
Labels: Feature, 9.0

#5484 FEATURE: expose all NodeTags via `getCoveredDimensionsTaggedBy` on NodeAggregate
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/NodeDisabling.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/SubtreeTagging.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/DimensionSpacePointsBySubtreeTags.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeAggregate.php
  Neos.ContentRepository.Core/Tests/Unit/Projection/ContentGraph/DimensionSpacePointsBySubtreeTagsTest.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeAggregateTrait.php
Labels: Feature, 9.0, Task
