Repository neos/neos-development-collection, pull requests merged in 2025-06, with the labels that each got.

#5566 BUGFIX: Convert Nodes object into array to return references in the same way as in Neos 8.x
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/PropertyOperation.php
Labels: Bug, 9.0

#5549 BUGFIX: Adjust fusion-form dependency
  Neos.Neos/composer.json
Labels: Bug, 9.0

#5553 BUGFIX: MediaBrowser's upload action shows empty flash message if file is too big
  Neos.Media.Browser/Resources/Private/Layouts/EditImage.html
  Neos.Media.Browser/Resources/Private/Layouts/UploadImage.html
Labels: Bug, 8.3

#5563 BUGFIX: Disable nodes after processing all node variants for export
  Neos.ContentRepository.LegacyNodeMigration/Classes/Processors/EventExportProcessor.php
Labels: Bug, 9.0

#5572 BUGFIX: Prevent sharing splitString between node routings
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
Labels: Bug, 9.0

#5573 BUGFIX: Reimplement missing node route handler options from previous Neos versions
  Neos.Neos/Classes/FrontendRouting/EventSourcedFrontendNodeRoutePartHandler.php
Labels: Bug, 9.0

#5583 TASK: update shell commands in contributing guide according to Neos 9
  CONTRIBUTING.md
Labels: T: Documentation, 9.0, Task

#5569 BUGFIX: Use cached node uris
  Neos.Neos/Classes/FrontendRouting/CatchUpHook/RouterCacheHook.php
  Neos.Neos/Classes/FrontendRouting/NodeUriBuilder.php
Labels: Bug, 9.0

#5547 BUGFIX: Standalone Core - move `AuthProviderFactoryInterface` to correct packgage
  Neos.ContentRepository.Core/Classes/Factory/AuthProviderFactoryInterface.php
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositoryFactory.php
  Neos.ContentRepository.TestSuite/Classes/Fakes/FakeAuthProviderFactory.php
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
  Neos.ContentRepositoryRegistry/Classes/Factory/AuthProvider/AuthProviderFactoryInterface.php
  Neos.ContentRepositoryRegistry/Classes/Factory/AuthProvider/StaticAuthProviderFactory.php
  Neos.Neos/Classes/Security/ContentRepositoryAuthProvider/ContentRepositoryAuthProviderFactory.php
Labels: Bug, 9.0

#5551 BUGFIX: Expose internal `CRBehavioralTestsSubjectProvider` via `Neos.ContentRepository.TestSuite`
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.Export/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRBehavioralTestsSubjectProvider.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/ContentRepositorySecurityTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/WorkspaceServiceTrait.php
  Neos.TimeableNodeVisibility/Tests/Behavior/Bootstrap/FeatureContext.php
Labels: 9.0

#5582 TASK: Add tree rendering
  Neos.Neos/Resources/Private/Fusion/Backend/Configuration.Ui/Common/Tree.fusion
  Neos.Neos/Resources/Private/Styles/Modules/Administration/_Configuration.scss
Labels: Task, feature/configuration-ui
