Repository neos/neos-development-collection, pull requests merged in 2025-03, with the labels that each got.

#5491 BUGFIX: Add hierarchical level tracking for ancestor node queries
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
Labels: Bug, 9.0

#5447 BUGFIX: Fix return type error with `getUriForThumbnail()`
  Neos.Media/Classes/Domain/Service/ThumbnailService.php
Labels: Bug, 8.3

#5457 BUGFIX: Recognize removed-state while reducing
  Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
Labels: Bug, 8.3

#5463 FEATURE: Soft removal subtree tag `removed`
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/ContentHypergraph.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/01-RemoveNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/02-RemoveNodeAggregate_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/03-RemoveNodeAggregate_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/11-NodeTypeChange/02-ChangeNodeAggregateType_DeleteStrategy.feature
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/ParallelWritingInWorkspaces/ParallelWritingInWorkspacesTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/WorkspacePublicationDuringWriting/WorkspacePublicationDuringWritingTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/WorkspaceWritingDuringRebase/WorkspaceWritingDuringRebaseTest.php
  Neos.ContentRepository.Core/Classes/Feature/Common/ConstraintChecks.php
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeCreationInternals.php
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeTypeChangeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeVariationInternals.php
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/DimensionSpaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/NodeMove.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/Command/RemoveNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/Event/NodeAggregateWasRemoved.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/NodeRemoval.php
  Neos.ContentRepository.Core/Classes/Feature/Security/StaticAuthProvider.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Dto/SubtreeTags.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/VisibilityConstraints.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ContextOperation.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DisallowedChildNodeAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
  Neos.ContentRepository.TestSuite/Classes/Fakes/FakeAuthProvider.php
  Neos.ContentRepository.TestSuite/Classes/Unit/NodeSubjectProvider.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentCommandController.php
  Neos.Media.Browser/Classes/Controller/UsageController.php
  Neos.Neos/Classes/AssetUsage/AssetUsageIndexingProcessor.php
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHook.php
  Neos.Neos/Classes/Controller/Backend/ContentController.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Classes/Controller/Service/NodesController.php
  Neos.Neos/Classes/Domain/Service/NeosSubtreeTag.php
  Neos.Neos/Classes/Domain/Service/NeosVisibilityConstraints.php
  Neos.Neos/Classes/Domain/Service/NodeDuplicationService.php
  Neos.Neos/Classes/Domain/Service/WorkspacePublishingService.php
  Neos.Neos/Classes/PendingChangesProjection/Change.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeFinder.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  Neos.Neos/Classes/PendingChangesProjection/Changes.php
  Neos.Neos/Classes/Security/Authorization/ContentRepositoryAuthorizationService.php
  Neos.Neos/Classes/Security/ContentRepositoryAuthProvider/ContentRepositoryAuthProvider.php
  Neos.Neos/Configuration/Policy.yaml
  Neos.Neos/Tests/Behavior/Features/ContentRepository/NodeCopying/CopyNode_NoDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/NodeSoftRemoval/01-SoftRemoveNodeAggregate_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/PendingChanges/NodeSoftRemoval/02-SoftRemoveNodeAggregate_WithDimensions.feature
  Neos.Neos/Tests/Unit/Fusion/Helper/CachingHelperTest.php
  Neos.TimeableNodeVisibility/Classes/Service/TimeableNodeVisibilityService.php
  Neos.TimeableNodeVisibility/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.TimeableNodeVisibility/Tests/Behavior/Features/HandleExceeded.feature
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
Labels: Feature, 9.0, Task

#5496 TASK: Discourage `DisableNodeAggregate` and remove duplicated command handling
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/01-DisableNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/04-EnableNodeAggregate_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/06-NodeDisabling/Rebase_Legacy_DisableAndEnableNodeAggregate.feature
  Neos.ContentRepository.Core/Classes/Feature/NodeAggregateCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/DisableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/EnableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Exception/NodeAggregateIsAlreadyDisabled.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Exception/NodeAggregateIsAlreadyEnabled.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/NodeDisabling.php
  Neos.ContentRepository.Core/Classes/Feature/RebaseableCommands.php
  Neos.ContentRepository.Core/Classes/Feature/Security/StaticAuthProvider.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Dto/SubtreeTag.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/SubtreeTagging.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Processors/EventExportProcessor.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ContextOperation.php
  Neos.Neos/Classes/Domain/Service/NeosSubtreeTag.php
  Neos.Neos/Classes/Domain/Service/NeosVisibilityConstraints.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Classes/Security/ContentRepositoryAuthProvider/ContentRepositoryAuthProvider.php
  Neos.Neos/Classes/Service/LinkingService.php
  Neos.TimeableNodeVisibility/Classes/Service/TimeableNodeVisibilityService.php
  Neos.TimeableNodeVisibility/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
Labels: 9.0, Task

#5468 TASK: Add onAfterHandle to CommandHookInterface
  Neos.ContentRepository.BehavioralTests/Configuration/Testing/Settings.yaml
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Extensibility/AbstractExtensibilityTestCase.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Extensibility/CommandHookTest.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandHookInterface.php
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandHooks.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/EventStore/Events.php
  Neos.ContentRepository.Core/Classes/EventStore/PublishedEvents.php
  Neos.ContentRepository.TestSuite/Classes/Fakes/FakeCommandHookFactory.php
Labels: Feature, 9.0, Task

#5490 TASK: Remove misleading `NodeAggregate::getNodeByCoveredDimensionSpacePoint()`
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentGraph.PostgreSQLAdapter/src/Domain/Repository/NodeFactory.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeAggregate.php
Labels: 9.0, Task

#5456 TASK: Use proper version checks for contentStream events
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/DeleteAndRecreateWorkspace.feature
  Neos.ContentRepository.Core/Classes/Feature/DimensionSpaceAdjustment/DimensionSpaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/SubtreeTagging.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
Labels: 9.0, Task

#4938 TASK: Disallow disabling tethered nodes
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/SubtreeTagging/TagSubtree_ConstraintChecks.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/SubtreeTagging/TagSubtree_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/SubtreeTagging/TagSubtree_WithoutDimensions.feature
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Dto/SubtreeTag.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/VisibilityConstraints.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Processors/EventExportProcessor.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ContextOperation.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
  Neos.Neos/Classes/Domain/Service/NodeDuplicationService.php
  Neos.Neos/Classes/Domain/SubtreeTagging/NeosSubtreeTag.php
  Neos.Neos/Classes/Domain/SubtreeTagging/NeosSubtreeTaggingConstraintChecks.php
  Neos.Neos/Classes/Domain/SubtreeTagging/NeosSubtreeTaggingConstraintChecksFactory.php
  Neos.Neos/Classes/Domain/SubtreeTagging/NeosVisibilityConstraints.php
  Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  Neos.Neos/Classes/Security/Authorization/ContentRepositoryAuthorizationService.php
  Neos.Neos/Classes/Service/LinkingService.php
  Neos.Neos/Configuration/Settings.ContentRepositoryRegistry.yaml
  Neos.Neos/Tests/Behavior/Features/ContentRepository/NodeDisabling.feature
  Neos.TimeableNodeVisibility/Classes/Service/TimeableNodeVisibilityService.php
  Neos.TimeableNodeVisibility/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
Labels: 9.0, Task

#5499 TASK: Render attributes in Neos.Neos:Content as HTML attributes string
  Neos.Neos/Classes/Fusion/Helper/ArrayHelper.php
  Neos.Neos/Resources/Private/Fusion/Prototypes/Content.fusion
Labels: 9.0, Task

#5479 FEATURE: Soft removal garbage collection
  Neos.ContentRepository.Core/Classes/DimensionSpace/InterDimensionalVariationGraph.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/NodeRemoval.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/NodeAggregates.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Nodes.php
  Neos.ContentRepository.Core/Tests/Unit/DimensionSpace/InterDimensionalVariationGraphTest.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/ProjectedNodeAggregateTrait.php
  Neos.Neos/Classes/Domain/Service/WorkspacePublishingService.php
  Neos.Neos/Classes/Domain/Service/WorkspaceService.php
  Neos.Neos/Classes/Domain/SubtreeTagging/NeosSubtreeTaggingConstraintChecks.php
  Neos.Neos/Classes/Domain/SubtreeTagging/SoftRemoval/ImpendingHardRemovalConflict.php
  Neos.Neos/Classes/Domain/SubtreeTagging/SoftRemoval/ImpendingHardRemovalConflictDetectionHook.php
  Neos.Neos/Classes/Domain/SubtreeTagging/SoftRemoval/ImpendingHardRemovalConflictDetectionHookFactory.php
  Neos.Neos/Classes/Domain/SubtreeTagging/SoftRemoval/ImpendingHardRemovalConflictRepository.php
  Neos.Neos/Classes/Domain/SubtreeTagging/SoftRemoval/ImpendingHardRemovalConflicts.php
  Neos.Neos/Classes/Domain/SubtreeTagging/SoftRemoval/SoftRemovalGarbageCollector.php
  Neos.Neos/Classes/Domain/SubtreeTagging/SoftRemoval/SoftRemovedNode.php
  Neos.Neos/Classes/Domain/SubtreeTagging/SoftRemoval/SoftRemovedNodes.php
  Neos.Neos/Configuration/Settings.ContentRepositoryRegistry.yaml
  Neos.Neos/Migrations/Mysql/Version20250224180749.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/SoftRemovalGarbageCollectionTrait.php
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/00-WithoutImpendingConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/02-NodeCreationConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/03-NodeVariationConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/04-NodeModificationConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/05-NodeReferencingConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/06-SubtreeTaggingConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/07-NodeRemovalConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/08-NodeMoveConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/09-ChangeNodeAggregateNameConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/11-ChangeNodeAggregateTypeConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/DebugWip.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/MultiDimensionalNodeChangeConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/MultiSoftRemovedAncestorNodeChangeConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/MultiWorkspaceConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/SoftRemovalConstraints.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/WorkspaceConflictsCleanup.feature
Labels: Feature, 9.0

#5502 TASK: Remove obsolete possibly expensive `getContentGraph()`
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHook.php
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
Labels: 9.0, Task

#5500 TASK: Add the new login wallpaper for Neos 9 after discuss voting
  Neos.Neos/Resources/Public/Images/Login/Wallpaper.jpg
  Neos.Neos/Resources/Public/Images/Login/Wallpaper.webp
Labels: 9.0, Task

#5508 BUGFIX: Improve workspace module change handling
  Neos.Neos/Classes/Domain/Service/WorkspacePublishingService.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  Neos.Neos/Tests/Behavior/Features/PendingChanges/NodeSoftRemoval/02-SoftRemoveNodeAggregate_WithDimensions.feature
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
Labels: Bug, 9.0

#5497 TASK: Code style adjust 5 internal usages of `Object::none()` to `::createEmpty()`
  Neos.ContentRepository.Core/Classes/CommandHandler/CommandHooks.php
  Neos.ContentRepository.Core/Classes/Factory/ContentRepositorySubscriberFactories.php
  Neos.ContentRepository.Core/Classes/Projection/Projections.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscriber/Subscribers.php
  Neos.ContentRepository.Core/Classes/Subscription/SubscriptionIds.php
  Neos.ContentRepository.Core/Classes/Subscription/Subscriptions.php
  Neos.ContentRepositoryRegistry/Classes/Factory/SubscriptionStore/DoctrineSubscriptionStore.php
  Neos.Fusion/Classes/Core/FusionGlobals.php
  Neos.Fusion/Classes/Core/FusionSourceCodeCollection.php
  Neos.Fusion/Tests/Benchmark/RuntimeBench.php
  Neos.Fusion/Tests/Functional/FusionObjects/ExpressionsTest.php
  Neos.Fusion/Tests/Functional/FusionObjects/ReservedKeysTest.php
  Neos.Fusion/Tests/Unit/Core/FusionSourceCodeDtosTest.php
  Neos.Fusion/Tests/Unit/Core/RuntimeTest.php
  Neos.Neos/Classes/Domain/Import/LiveWorkspaceCreationProcessor.php
  Neos.Neos/Classes/Domain/Model/WorkspaceDescription.php
  Neos.Neos/Classes/Domain/Service/FusionSourceCodeFactory.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.Neos/Classes/Domain/Service/WorkspaceService.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/WorkspaceServiceTrait.php
Labels: 9.0, Task

#5506 TASK: Remove `markStale()` and `WithMarkStaleInterface` && Fully remove dead caching for `DocumentUriPathFinder`
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphReadModelInterface.php
  Neos.ContentRepository.Core/Classes/Projection/ProjectionInterface.php
  Neos.ContentRepository.Core/Classes/Projection/WithMarkStaleInterface.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathFinder.php
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Classes/Package.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  Neos.Neos/Classes/Routing/Cache/RouteCacheFlusher.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/Basic.feature
Labels: Bug, 9.0, Task

#5515 FEATURE: Custom label for auto created child nodes
  Neos.ContentRepositoryRegistry/Resources/Private/Schema/NodeTypes.schema.yaml
  Neos.Neos/Classes/Domain/NodeLabel/ExpressionBasedNodeLabelGenerator.php
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
Labels: Feature, 9.0

#5524 BUGFIX: Inject persistence manager where necessary
  Neos.Media.Browser/Classes/Controller/AssetController.php
  Neos.Media/Tests/Functional/Fixtures/Controller/ImageController.php
Labels: Bug, 9.0

#5521 BUGFIX: Allow boolean values for hidden properties in nodetype schema
  Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
Labels: Bug, 8.3

#5526 TASK: Attempt to fix parallel tests
  Neos.ContentRepository.BehavioralTests/Tests/Parallel/AbstractParallelTestCase.php
Labels: 9.0, Task

#5519 TASK: Allow variation of tethered root children
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/03-NodeVariation/01-CreateNodeVariant_ConstraintChecks.feature
  Neos.ContentRepository.Core/Classes/Feature/NodeVariation/NodeVariation.php
Labels: 9.0, Task

#5525 TASK: Optimize cache flushing on CR booting
  Neos.Neos/Classes/Fusion/Cache/GraphProjectorCatchUpHookForCacheFlushing.php
Labels: 9.0, Task

#5516 TASK: Remove obsolete affected source dsp from node aggregate was removed
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/02-RemoveNodeAggregate_WithoutDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/07-NodeRemoval/03-RemoveNodeAggregate_WithDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/11-NodeTypeChange/02-ChangeNodeAggregateType_DeleteStrategy.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeRemoval/RemoveNodeAggregateAfterDisabling.feature
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeTypeChangeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/Event/NodeAggregateWasRemoved.php
  Neos.ContentRepository.Core/Classes/Feature/NodeRemoval/NodeRemoval.php
  Neos.ContentRepository.Core/Classes/SharedModel/Node/NodeVariantSelectionStrategy.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/DisallowedChildNodeAdjustment.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/RemoveNodeAggregateTrait.php
  Neos.Neos/Classes/PendingChangesProjection/ChangeProjection.php
  Neos.Neos/Tests/Behavior/Features/PendingChanges/06-NodeRemoval/02-RemoveNodeAggregate_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/00-WithoutImpendingConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/02-NodeCreationConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/03-NodeVariationConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/04-NodeModificationConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/05-NodeReferencingConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/06-SubtreeTaggingConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/07-NodeRemovalConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/08-NodeMoveConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/09-ChangeNodeAggregateNameConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/11-ChangeNodeAggregateTypeConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/DebugWip.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/MultiWorkspaceConflicts.feature
  Neos.Neos/Tests/Behavior/Features/SoftRemovalGarbageCollection/WorkspaceConflictsCleanup.feature
Labels: 9.0, Task

#5512 TASK: Improve and fix usage of subgraph cache pool
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindChildNodesFilter.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ContextOperation.php
  Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/ContentSubgraphWithRuntimeCaches.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/FlushSubgraphCachePoolCatchUpHook.php
  Neos.ContentRepositoryRegistry/Classes/SubgraphCachingInMemory/SubgraphCachePool.php
  Neos.Neos/Classes/Controller/Frontend/ContentSubgraphCacheWarmup.php
  Neos.Neos/Classes/Controller/Frontend/NodeController.php
Labels: 9.0, Task

#5501 TASK: Elaborate deprecations in `VisibilityConstraints`
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/DisableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/NodeDisabling/Command/EnableNodeAggregate.php
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Dto/SubtreeTag.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/VisibilityConstraints.php
Labels: 9.0, Task

#5511 BUGFIX: Reset asset usages on replay
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHook.php
  Neos.Neos/Tests/Behavior/Features/AssetUsage/DimensionSpacePoints/01-MoveDimensionSpacePoints.feature
Labels: Bug, 9.0

#5528 BUGFIX: Boot media module flash-messages correctly if rendered outside Neos module
  Neos.Media.Browser/Resources/Private/Layouts/Default.html
  Neos.Media.Browser/Resources/Private/Layouts/EditImage.html
  Neos.Media.Browser/Resources/Private/Layouts/UploadImage.html
Labels: Bug, 8.3

#5529 FEATURE: Introduce `SubscriptionEngine::reactivate`
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/ProjectionErrorTest.php
  Neos.ContentRepository.BehavioralTests/Tests/Functional/Subscription/SubscriptionDetachedStatusTest.php
  Neos.ContentRepository.Core/Classes/Service/ContentRepositoryMaintainer.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/SubscriptionEngine.php
  Neos.ContentRepositoryRegistry/Classes/Command/SubscriptionCommandController.php
Labels: Feature, 9.0

#5517 FEATURE: Add option to emit warnings before handling node migrations
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/ChangePropertyValue_Dimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/ChangePropertyValue_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/RemoveProperty_NoDimensions.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/EventSourced/Migration/UpdateRootNodeAggregateDimensions.feature
  Neos.ContentRepository.Core/Classes/CommandHandler/Commands.php
  Neos.ContentRepository.NodeMigration/src/Command/ExecuteMigration.php
  Neos.ContentRepository.NodeMigration/src/NodeMigrationRequireConfirmationException.php
  Neos.ContentRepository.NodeMigration/src/NodeMigrationService.php
  Neos.ContentRepository.NodeMigration/src/Transformation/AddDimensionShineThroughTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/AddNewPropertyConverterAwareTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/ChangeNodeTypeTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/ChangePropertyValueConverterAwareTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/GlobalTransformationInterface.php
  Neos.ContentRepository.NodeMigration/src/Transformation/MoveDimensionSpacePointTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/NodeAggregateBasedTransformationInterface.php
  Neos.ContentRepository.NodeMigration/src/Transformation/NodeBasedTransformationInterface.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RemoveNodeTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RemovePropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RenameNodeAggregateTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/RenamePropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/StripTagsOnPropertyTransformationFactory.php
  Neos.ContentRepository.NodeMigration/src/Transformation/TransformationStep.php
  Neos.ContentRepository.NodeMigration/src/Transformation/TransformationSteps.php
  Neos.ContentRepository.NodeMigration/src/Transformation/Transformations.php
  Neos.ContentRepository.NodeMigration/src/Transformation/UpdateRootNodeAggregateDimensionsTransformationFactory.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/MigrationsTrait.php
  Neos.ContentRepositoryRegistry/Classes/Command/NodeMigrationCommandController.php
Labels: Feature, 9.0

#5498 [BUGFIX] Find nodes marked as removed in other dimension
  Neos.ContentRepository/Classes/Domain/Model/NodeData.php
Labels: 8.3
