Repository neos/neos-development-collection, pull requests merged in 2025-08, with the labels that each got.

#5602 BUGFIX: Reload node if hidden state is updated via inspector
  Neos.Neos/NodeTypes/Mixin/Hidable.yaml
Labels: Bug, 8.3

#5613 TASK: New build of neos/neos css assets
  Neos.Neos/Resources/Public/Styles/Lite.css
  Neos.Neos/Resources/Public/Styles/Lite.css.map
  Neos.Neos/Resources/Public/Styles/Main.css
  Neos.Neos/Resources/Public/Styles/Main.css.map
  Neos.Neos/Resources/Public/Styles/Minimal.css
  Neos.Neos/Resources/Public/Styles/Minimal.css.map
  Neos.Neos/Resources/Public/Styles/RawContentMode.css
  Neos.Neos/Resources/Public/Styles/RawContentMode.css.map
  Neos.Neos/package.json
Labels: 8.3, Task

#5611 Upmerge 8.4
  Neos.Media.Browser/composer.json
  Neos.Neos/Classes/Command/UserCommandController.php
  Neos.Neos/NodeTypes/Mixin/Hidable.yaml
  Neos.Neos/Resources/Private/Fusion/Backend/Views/Login.fusion
  Neos.Neos/Resources/Private/Styles/Modules/_Modules.scss
  Neos.Neos/Resources/Private/Styles/Modules/_Widget.scss
  Neos.Neos/Resources/Public/JavaScript/Main.min.js
  Neos.Neos/Resources/Public/JavaScript/Main.min.js.map
  Neos.Neos/Resources/Public/Styles/Error.css.map
  Neos.Neos/Resources/Public/Styles/Lite.css
  Neos.Neos/Resources/Public/Styles/Lite.css.map
  Neos.Neos/Resources/Public/Styles/Login.css.map
  Neos.Neos/Resources/Public/Styles/Main.css
  Neos.Neos/Resources/Public/Styles/Main.css.map
  Neos.Neos/Resources/Public/Styles/Minimal.css
  Neos.Neos/Resources/Public/Styles/Minimal.css.map
  Neos.Neos/Resources/Public/Styles/RawContentMode.css.map
  Neos.Neos/Resources/Public/Styles/Welcome.css.map
  Neos.Neos/package.json
  Neos.NodeTypes.BaseMixins/Resources/Private/Translations/pt_BR/NodeTypes/ImageCaptionMixin.xlf
  composer.json
Labels: 9.0

#5616 Revert "BUGFIX: Reload node if hidden state is updated via inspector"
  Neos.Neos/NodeTypes/Mixin/Hidable.yaml
Labels: 8.3
