Repository neos/neos-development-collection, pull requests merged in 2025-04, with the labels that each got.

#5531 BUGFIX: Correct error in fusion code generated by site kickstarter
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/Fusion/Document/AbstractPage.fusion
Labels: Bug, 9.0

#5532 TASK: Move fusion of kickstarted site into NodeTypes folder
  Neos.SiteKickstarter/Classes/Generator/AfxTemplateGenerator.php
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/Fusion/Content/.gitkeep
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/Fusion/Root.fusion
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/NodeTypes/Document/AbstractPage.fusion
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/NodeTypes/Document/Homepage.fusion
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/NodeTypes/Document/Homepage.yaml
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/NodeTypes/Document/Page.fusion
  Neos.SiteKickstarter/Resources/Private/AfxGenerator/NodeTypes/Document/Page.yaml
Labels: 9.0, Task

#5534 BUGFIX: Ensure workspace module can correctly handle workspace name a…
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/WorkspaceName.php
Labels: Bug, 9.0

#5536 FEATURE: Add login wallpaper attribution
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/Resources/Private/Fusion/Backend/Views/Login.fusion
  Neos.Neos/Resources/Private/Styles/Login.scss
  Neos.Neos/Resources/Public/JavaScript/Main.min.js
  Neos.Neos/Resources/Public/JavaScript/Main.min.js.map
  Neos.Neos/Resources/Public/Styles/Error.css
  Neos.Neos/Resources/Public/Styles/Error.css.map
  Neos.Neos/Resources/Public/Styles/Lite.css
  Neos.Neos/Resources/Public/Styles/Lite.css.map
  Neos.Neos/Resources/Public/Styles/Login.css
  Neos.Neos/Resources/Public/Styles/Login.css.map
  Neos.Neos/Resources/Public/Styles/Main.css
  Neos.Neos/Resources/Public/Styles/Main.css.map
  Neos.Neos/Resources/Public/Styles/Minimal.css
  Neos.Neos/Resources/Public/Styles/Minimal.css.map
  Neos.Neos/Resources/Public/Styles/RawContentMode.css
  Neos.Neos/Resources/Public/Styles/RawContentMode.css.map
  Neos.Neos/Resources/Public/Styles/Shortcut.css
  Neos.Neos/Resources/Public/Styles/Shortcut.css.map
  Neos.Neos/Resources/Public/Styles/Welcome.css
  Neos.Neos/Resources/Public/Styles/Welcome.css.map
Labels: Feature, 9.0

#5537 TASK: Allow MySQL back to the party
  .github/workflows/build.yml
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Bootstrap/ProjectionIntegrityViolationDetectionTrait.php
  Neos.ContentGraph.DoctrineDbalAdapter/Tests/Behavior/Features/Projection/ProjectionIntegrityViolationDetection/SubtreeTagsAreInherited.feature
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/Feature/SubtreeTagging.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/ProjectionIntegrityViolationDetector.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php
  Neos.ContentGraph.DoctrineDbalAdapter/src/NodeQueryBuilder.php
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/ChildNodes.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/NodeTraversal/DescendantNodes.feature
  Neos.ContentRepository.Core/Classes/Infrastructure/DbalSchemaFactory.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/Helpers/DimensionSpacePointSetSorter.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.Neos/Classes/AssetUsage/Domain/AssetUsageRepository.php
  Neos.Neos/Classes/PendingChangesProjection/Change.php
  Neos.Neos/Migrations/Mysql/Version20231012072631.php
  Neos.Neos/Migrations/Mysql/Version20240425223900.php
  Neos.Neos/Migrations/Mysql/Version20240906102606.php
  Neos.Neos/Migrations/Mysql/Version20241212000000.php
  Neos.Neos/Migrations/Mysql/Version20250224180749.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
Labels: 9.0, Task

#5540 TASK: Overhaul last 90 deprecations and dead code
  Neos.ContentRepository.BehavioralTests/Classes/PhpstanRules/InternalMethodsNotAllowedOutsideContentRepositoryRule.php
  Neos.ContentRepository.Core/Classes/Dimension/ContentDimension.php
  Neos.ContentRepository.Core/Classes/Dimension/ContentDimensionValue.php
  Neos.ContentRepository.Core/Tests/Unit/Dimension/ConfigurationBasedContentDimensionSourceTest.php
  Neos.ContentRepositoryRegistry/Classes/Command/CrCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/MigrateEventsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php
  Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationServiceFactory.php
Labels: 9.0, Task

#5543 BUGFIX: Skip reference properties in AssetExportProcessor
  Neos.ContentRepository.LegacyNodeMigration/Classes/Processors/AssetExportProcessor.php
Labels: Bug, 9.0

#5546 BUGFIX: Fix publishing for `Neos.Neos:RestrictedEditor` from 3rd level workspace
  Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
Labels: Bug, 8.3
