Repository neos/neos-development-collection, pull requests merged in 2025-01, with the labels that each got.

#5415 BUGFIX: Ensure cache flushing for asset changes works with foreign workspaces
  Neos.Neos/Classes/Fusion/Cache/AssetChangeHandlerForCacheFlushing.php
Labels: Bug, 9.0

#5422 BUGFIX: Raw content mode for nodes without node type
  Neos.Neos/Resources/Private/Fusion/RawContent/NodeProperties.fusion
Labels: Bug, 9.0

#5418 TASK: Properly re-remove obsolete legacy `userInformation.personalWorkspaceName` in policy for workspaces
  Neos.Neos/Classes/Service/UserService.php
  Neos.Neos/Configuration/Policy.yaml
Labels: 9.0, Task

#5340 TASK: Remove obsolete `findContentStream(s)`
  Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphReadModelAdapter.php
  Neos.ContentGraph.PostgreSQLAdapter/src/ContentHyperGraphReadModelAdapter.php
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentGraphReadModelInterface.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/ContentStream.php
  Neos.ContentRepository.Core/Classes/SharedModel/Workspace/ContentStreams.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/CRTestSuiteTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/ContentRepositorySecurityTrait.php
Labels: 9.0, Task

#5424 TASK: Remove policy for removed `Neos\Neos\Service\Controller\NodeController`
  Neos.Neos/Configuration/Policy.yaml
Labels: 9.0, Task

#5426 BUGFIX: Correct node naming scheme in nodetype definition example
  Neos.Neos/Documentation/References/NodeTypeDefinition.rst
Labels: T: Documentation, Bug, 8.3

#5206 BUGFIX: Share same role details when adding user as when editing them
  Neos.Neos/Resources/Private/Partials/Module/Shared/EditAccount.html
  Neos.Neos/Resources/Private/Partials/Module/Shared/RolesSelection.html
  Neos.Neos/Resources/Private/Templates/Module/Administration/Users/New.html
Labels: Bug, 8.3, P: User Management

#5432 BUGFIX: Fixed table view of asset editor
  Neos.Media.Browser/Resources/Public/JavaScript/select.js
Labels: Bug, 8.3

#5442 TASK: Make nullable parameter explicit to become PHP 8.4 compatible
  Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php
  Neos.ContentRepository.BehavioralTests/Classes/ProjectionRaceConditionTester/Command/RaceConditionTrackerCommandController.php
  Neos.ContentRepository.Core/Classes/DimensionSpace/InterDimensionalVariationGraph.php
  Neos.ContentRepository.Core/Classes/EventStore/DecoratedEvent.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/Command/CreateNodeAggregateWithNodeAndSerializedProperties.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/Normalizer/ArrayNormalizer.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/Normalizer/CollectionTypeDenormalizer.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/Normalizer/ScalarNormalizer.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/Normalizer/UriNormalizer.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/Normalizer/ValueObjectArrayDenormalizer.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/Normalizer/ValueObjectBoolDenormalizer.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/Normalizer/ValueObjectFloatDenormalizer.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/Normalizer/ValueObjectIntDenormalizer.php
  Neos.ContentRepository.Core/Classes/Infrastructure/Property/Normalizer/ValueObjectStringDenormalizer.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountAncestorNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountBackReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountDescendantNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/CountReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindAncestorNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindBackReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindChildNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindDescendantNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindPrecedingSiblingNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindReferencesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindRootNodeAggregatesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindSubtreeFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindSucceedingSiblingNodesFilter.php
  Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Timestamps.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/SubscriptionEngine.php
  Neos.ContentRepository.Core/Classes/Subscription/Engine/SubscriptionEngineCriteria.php
  Neos.ContentRepository.Core/Classes/Subscription/Store/SubscriptionCriteria.php
  Neos.ContentRepository.Export/Tests/Behavior/Features/Bootstrap/CrImportExportTrait.php
  Neos.ContentRepository.LegacyNodeMigration/Classes/Command/SiteCommandController.php
  Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Bootstrap/FeatureContext.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/GenericCommandExecutionAndEventPublication.php
  Neos.ContentRepository.TestSuite/Classes/Behavior/Features/Bootstrap/NodeTraversalTrait.php
  Neos.ContentRepository.TestSuite/Classes/Unit/NodeSubjectProvider.php
  Neos.ContentRepositoryRegistry/Classes/Command/ContentGraphIntegrityCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Command/StructureAdjustmentsCommandController.php
  Neos.ContentRepositoryRegistry/Classes/Infrastructure/Property/Normalizer/DoctrinePersistentObjectNormalizer.php
  Neos.Fusion/Classes/Core/Cache/FusionContextSerializer.php
  Neos.Neos/Classes/AssetUsage/AssetUsageIndexingProcessor.php
  Neos.Neos/Classes/Command/SiteCommandController.php
  Neos.Neos/Classes/Command/WorkspaceCommandController.php
  Neos.Neos/Classes/Domain/Service/UserService.php
  Neos.Neos/Classes/FrontendRouting/NodeUriBuilder.php
  Neos.Neos/Classes/Fusion/Cache/NeosFusionContextSerializer.php
  Neos.Neos/Classes/TypeConverter/NodeAddressToNodeConverter.php
  Neos.Neos/Classes/TypeConverter/NodeAddressToStringConverter.php
  Neos.Neos/Classes/TypeConverter/NodeToNodeAddressStringConverter.php
  Neos.Neos/Classes/ViewHelpers/Rendering/InPreviewModeViewHelper.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/BrowserTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/ExceptionsTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/FlowSecurityTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/RoutingTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/UserServiceTrait.php
  Neos.Neos/Tests/Behavior/Features/Bootstrap/WorkspaceServiceTrait.php
Labels: 9.0, Task

#5412 BUGFIX: Handle nodes with missing UriPathSegments in uriPathProjection
  Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/MissingPathSegments.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/NodeCreationEdgeCases.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/NodeVariationEdgeCases.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/PartialPublish.feature
  Neos.Neos/Tests/Behavior/Features/FrontendRouting/UnknownNodeTypes.feature
Labels: Bug, 9.0

#5281 BUGFIX: Force direct access on setting node properties in node data similarize
  Neos.ContentRepository/Classes/Domain/Model/NodeData.php
  Neos.ContentRepository/Tests/Unit/Domain/Model/NodeDataTest.php
Labels: Bug, 8.3

#5343 BUGFIX: Add missing event emitters to internal node properties
  Neos.ContentRepository/Classes/Domain/Model/Node.php
Labels: Bug, 8.3

#5325 TASK: Allow setting itemsPerPage in user administration listing
  Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
  Neos.Neos/Configuration/Settings.yaml
  Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Index.html
Labels: 8.3, Task

#4236 TASK: Fix MySQL migration differences on fresh setup
  Neos.ContentRepository/Migrations/Mysql/Version20230430183156.php
  Neos.Media/Migrations/Mysql/Version20230430183157.php
  Neos.Neos/Classes/EventLog/Domain/Model/NodeEvent.php
Labels: 8.3, Task

#5443 TASK: Render command references
  Neos.Neos/Configuration/Settings.yaml
Labels: 8.3, Task

#5130 FEATURE: Reintroduce FlowQuery `context()` operation
  Neos.ContentRepository.Core/Classes/Feature/SubtreeTagging/Dto/SubtreeTags.php
  Neos.ContentRepository.NodeAccess/Classes/FlowQueryOperations/ContextOperation.php
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery.feature
  Neos.Neos/Tests/Behavior/Features/Fusion/FlowQuery_Advanced.feature
Labels: Feature, 9.0, Task

#5449 BUGFIX: fix error during site import
  Neos.Media/Classes/Domain/Model/Adjustment/CropImageAdjustment.php
Labels: Bug, 8.3

#5446 TASK: Check if index need to be renamed
  Neos.ContentRepository/Migrations/Mysql/Version20230430183156.php
Labels: 8.3, Task

#5406 BUGFIX: Asset usage prevent orphaned asset usage entries in case of a rebase with conflicts
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W6-WorkspaceRebasing/01-BasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W6-WorkspaceRebasing/03-RebasingWithConflictingChanges.feature
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/ConflictingEvents.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Event/WorkspaceWasRebased.php
  Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHook.php
Labels: Bug, 9.0

#5396 BUGFIX: Ensure that its not attempted to publish 0 events
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/04-NodeModification/01-SetNodeProperties_ConstraintChecks.feature
  Neos.ContentRepository.Core/Classes/EventStore/Events.php
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeTypeChangeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/Common/NodeVariationInternals.php
  Neos.ContentRepository.Core/Classes/Feature/Common/TetheredNodeInternals.php
  Neos.ContentRepository.Core/Classes/Feature/NodeCreation/NodeCreation.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Command/SetNodeProperties.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/Dto/PropertyValuesToWrite.php
  Neos.ContentRepository.Core/Classes/Feature/NodeModification/NodeModification.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/Command/SetNodeReferences.php
  Neos.ContentRepository.Core/Classes/Feature/NodeReferencing/NodeReferencing.php
  Neos.ContentRepository.Core/Classes/Feature/NodeTypeChange/NodeTypeChange.php
  Neos.ContentRepository.Core/Classes/Feature/RebaseableCommand.php
  Neos.ContentRepository.Core/Classes/Feature/RootNodeCreation/RootNodeHandling.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/NodeType/TetheredNodeTypeDefinitions.php
  Neos.ContentRepository.StructureAdjustment/src/Adjustment/TetheredNodeAdjustments.php
Labels: Bug, 9.0

#5337 !!! TASK: Throw exceptions in unnecessary rebase and publish cases
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W10-IndividualNodeDiscarding/02-BasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W11-ChangeBaseWorkspace/02-BasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W6-WorkspaceRebasing/01-BasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W7-WorkspacePublication/02-PublishWorkspace.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/02-BasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W8-IndividualNodePublication/03-MoreBasicFeatures.feature
  Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/W9-WorkspaceDiscarding/02-DiscardWorkspace.feature
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandSkipped.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceModification/Exception/WorkspaceIsNotEmptyException.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Command/DiscardIndividualNodesFromWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspacePublication/Command/PublishIndividualNodesFromWorkspace.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Dto/RebaseErrorHandlingStrategy.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Exception/WorkspaceRebaseFailed.php
  Neos.Neos/Classes/Domain/Service/WorkspacePublishingService.php
  Neos.Neos/Tests/Behavior/Features/AssetUsage/01-NodeCreation/01-CreateNodeAggregateWithNode_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/01-NodeCreation/02-CreateNodeAggregateWithNode_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W01-WorkspacePublication/01-PublishWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W01-WorkspacePublication/02-PublishWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W01-WorkspacePublication/03-PublishIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W01-WorkspacePublication/04-PublishIndividualNodesFromWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/01-DiscardWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/02-DiscardWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/03-DiscardIndividualNodesFromWorkspace_WithoutDimensions.feature
  Neos.Neos/Tests/Behavior/Features/AssetUsage/W02-WorkspaceDiscarding/04-DiscardIndividualNodesFromWorkspace_WithDimensions.feature
  Neos.Neos/Tests/Behavior/Features/ContentRepository/Security/WorkspacePermissions.feature
Labels: 9.0

#5440 BUGFIX: Remove import site from site creation module and fix delete sites (9.0)
  Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
  Neos.Neos/Classes/Domain/Service/SiteService.php
  Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
  Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/NewSite.html
  Neos.Neos/Resources/Private/Translations/en/Modules.xlf
Labels: Bug, 9.0

#5388 TASK: Document that scatter does NOT move fallbacks!
  Neos.ContentRepository.Core/Classes/Feature/NodeMove/Dto/RelationDistributionStrategy.php
Labels: 9.0, Task

#5451 TASK: Add correlation id and debug metadata to events
  Neos.ContentRepository.Core/Classes/ContentRepository.php
  Neos.ContentRepository.Core/Classes/EventStore/EventNormalizer.php
  Neos.ContentRepository.Core/Classes/Feature/ContentStreamHandling.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceCommandHandler.php
  Neos.ContentRepository.Core/Classes/Feature/WorkspaceRebase/Exception/WorkspaceRebaseFailed.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner.php
  Neos.ContentRepository.Core/Classes/Service/ContentStreamPruner/ContentStreamForPruning.php
  Neos.ContentRepository.Export/src/Processors/EventStoreImportProcessor.php
  Neos.ContentRepository.StructureAdjustment/src/StructureAdjustmentService.php
Labels: 9.0, Task

#5450 FEATURE: Add Rebase Workspace button to Workspace UI
  Neos.Workspace.Ui/Classes/Controller/WorkspaceController.php
  Neos.Workspace.Ui/Resources/Private/Fusion/Features/Workspace/Actions/Rebase.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Features/Workspace/Components/WorkspaceTableRow.fusion
  Neos.Workspace.Ui/Resources/Private/Fusion/Features/Workspace/Modals/Rebase.fusion
  Neos.Workspace.Ui/Resources/Private/Translations/en/Main.xlf
Labels: Feature, 9.0

#5151 TASK: Deprecate additional site kickstart generators and show helpful output for default afx case
  Neos.SiteKickstarter/Classes/Command/KickstartCommandController.php
  Neos.SiteKickstarter/Classes/Generator/AfxTemplateGenerator.php
  Neos.SiteKickstarter/Classes/Generator/SitePackageGeneratorInterface.php
  Neos.SiteKickstarter/Classes/Service/FusionRecursiveDirectoryRenderer.php
  Neos.SiteKickstarter/Classes/Service/SimpleTemplateRenderer.php
  Neos.SiteKickstarter/Classes/Service/SiteGeneratorCollectingService.php
  Neos.SiteKickstarter/Classes/Service/SitePackageGeneratorNameService.php
Labels: 9.0, Task

#5452 TASK: Followup #4236 remove legacy core migration
  Neos.ContentRepository/Migrations/Mysql/Version20230430183156.php
Labels: 9.0, Task
